### PR TITLE
Add irq plugin implementation for NetBSD

### PR DESCRIPTION
**Pull request by efuss**
ChangeLog: irq plugin: added an implementation for NetBSD.

Implement the irq plugin for NetBSD.
Written by Håvard Eidnes <he@NetBSD.org>

This PR also contains the addition of a `BUILD_NETBSD` definition I intended to request separately.

### CODE REVIEW

**Comment by efuss** [comment]
I don't get why the "The Travis CI build is in progress" since four days.

**Comment by efuss** [comment]
Close and re-open because Travis CI build claims to be in progress.

**Comment by sunkuranganath** [comment]
@efuss  CI doesnt necessarily have NetBSD environment.
Is it right to assume that you had opportunity to test this in your NetBSD environment?

**Comment by efuss** [comment]
> CI doesnt necessarily have NetBSD environment.
It definitely lacks it. Otherwise, it would have spotted a modification to my implementation of the NFS plugin for NetBSD that made it fail to compile.

> Is it right to assume that you had opportunity to test this in your NetBSD environment?
All the NetBSD plugin implementations sans the NFS one were written by Håvard Eidnes about four years ago and have lived as pkgsrc patches ever since.
So about anyone using collectd on NetBSD will have been using these for years in case he enabled that specific plugin.
Speaking specifically of the irq plugin, I must admit I don't have that enabled myself (I also currently use neither entropy nor netstat_udp).
I guess that Håvard Eidnes himself must have been using them, otherwise, he wouldn't have gone into the trouble of writing them.

**Pull request merged**
