### PR TITLE
routeros: Add support for temperature and voltage data

### PR DESCRIPTION
**Pull request by manio**
This has to be merged after my changes in librouteros (https://github.com/manio/routeros-api). Maybe some additional ifdefs regards librouteros version will be needed - it's up to you.

### CODE REVIEW

**Comment by manio** [comment]
bump (you've got my email about librouteros pull request)?

**Comment by mfournier** [comment]
@manio I think the first step would be to get your changes to routeros accepted into the upstream project. No problem to keep this issue open in the meantime, but I don't think it makes sense to include it before that.

**Comment by manio** [comment]
@mfournier 
regarding librouteros: I've sent a PR to @octo almost month ago (to his e-mail), but no reply so far - is there some other way to include my PR upstream?

**Comment by octo** [comment]
Sorry this is blocked on me. I'll take a look at your patch and come back to this PR.

**Comment by manio** [comment]
Hello @octo, can you review the https://github.com/manio/routeros-api, merge it, and finally merge also this PR? I have some plans to bring some other features to this library and a plugin but all stuck at the beginning (it is now over a year since the changes) :(

**Comment by octo** [comment]
Hi @manio,

thank you very much for your work! I'm not really active with the *librouteros* project, so I've invited you as a collaborator to [octo/librouteros](https://github.com/octo/librouteros).

Best regards,
—octo

**Comment by manio** [comment]
This is great, thank you very much! :)
Ok, so first I'll rebase my changes and push to octo/librouteros...

**Comment by manio** [comment]
@octo,
I've pushed the changes in https://github.com/octo/librouteros, so I believe this PR can now be merged as well.

**Comment by manio** [comment]
@octo 
Bump :)
Can you please now merge this?

**Comment by manio** [comment]
I've just rebased the changes to apply cleanly on current master (added cosmetic fixes to match the master tree after clang-cleanup commits).

**Comment by rpv-tomsk** [comment]
This PR works!

Still awaiting for new release of librouteros, then it needs to be a bit polished before merge.

Let's release all these?

**Comment by rpv-tomsk** [comment]
cc @manio 

Hi, Mariusz!

Can you please "Allow edits from maintainers." for this PR?

I will push some updates (rebase to master, and ifdefs added) and merge this then.
I don't want to open new PR for this )

Thanks.

**Comment by rpv-tomsk** [comment]
Added ifdefs looks like `#if ROS_VERSION >= ROS_VERSION_ENCODE(1, 1, 3)`.
So, they reference to 1.1.3 which is still unreleased.

Maybe it will be good to rise version in librouteros master branch so Collectd will be correctly built?

**Comment by rpv-tomsk** [comment]
As a maintainer, I just merged my PR to master )
Yes, there are many long-waiting patch requests in Collectd, but I'm working on this. )

>I don't have nothing against creating new librouteros version (would be great if we also have new login authorization support in place)

At the moment I propose to bump versions in librouteros master branch so anybody will be able to build library from master tarball / git and build soft in the same way as it will be after release - ROS_VERSION will have expected value. That will not be possible to build Collectd with this feature merged unless ROS_VERSION is bumped - that is the goal.

>(I never did this so far, it was always done by @octo). I can only make changes in the librouteros repo itself as a collaborator.

I understand that, unfortunately I got no news from @octo for a while...

**Comment by manio** [comment]
Closing as this was superseded with #2851. Thanks!

**Comment by rpv-tomsk** [comment]
Thanks for your work on Collectd, Mariusz!

**Pull request closed without merging**
