### PR TITLE
Allowed custom plugin name in 'dbi', 'oracle' and 'postgresql' plugins.

### PR DESCRIPTION
**Pull request by rpv-tomsk**
Like added in  #1558,  #1563 and #1681, added option 'PluginName' to dbi-related plugins: 'dbi', 'oracle' and 'postgresql'.

### CODE REVIEW

**Comment by tokkee** [comment]
Please see my comment in https://github.com/collectd/collectd/pull/1681#issuecomment-213991806: I think it should be possible to fetch the plugin name from the query result.

**Comment by rpv-tomsk** [comment]
> That said, instead of (or in addition to) a static name, I wonder if it would be better to fetch the name from a query result. In SQL plugins (e.g., #1707), this would be easy, because a static name could also be provided by the query. For the plugins in this PR, this may not always be feasible, though.

I think that feature will be excessive. I think, plugin name is toо static (unlike the plugin instance) to query it from database. In my practice, it is enough to get plugin instance from SQL/curl/so on and no need to get plugin name same way.

Can you provide an use-case of such feature? 

Also I think what all 'generic' plugins should behave in similar manner, so 'static plugin name' option is required.

**Comment by tokkee** [comment]
I was thinking along the lines of adding `PluginNameFrom` to the `Query` block instead of the `Database` block. A query may provide information about multiple databases and similar to how you'd want to configure different plugin names per database, you'd then want the same feature for these queries. In fact, I even wonder if `PluginName` should be a query or database option (or both?) since the plugin name is supposed to describe the data (which is provided by the query) instead of where it comes from (the database which issues many queries).

I'll have to think about this a little more because I think we should make sure to get the semantics right. Again, a central place to discuss this might be a good idea.

**Comment by octo** [comment]
As noted in #1681, please use `Plugin` (and potentially `PluginFrom`) as the option name. Also as noted in #1681 and by @tokkee above, please open a feature-request issue so we have a non-plugin-specific place to talk about this.

**Comment by rpv-tomsk** [comment]
Renamed 'PluginName' option to unified 'Plugin' and rebased.

**Comment by rpv-tomsk** [comment]
ping

**Comment by rpv-tomsk** [comment]
Ping me if you want this PR to be merged, I will rebase it to current master.

**Comment by rpv-tomsk** [comment]
The PR rebased to current master.

Please take a look and merge it.

**Comment by octo** [comment]
@tokkee A `PluginFrom` option SGTM, but I'm happy to postpone implementation until users request it. Does that work for you?

Best regards,
—octo

**Pull request merged**
