### PR TITLE
Plugin for  PCIe Advanced Error Reporting

### PR DESCRIPTION
**Pull request by kwiatrox**
The pcie_errors plugin collects PCI Express errors from Device Status in Capability
structure and from Advanced Error Reporting Extended Capability where available.
At every read it polls config space of PCI Express devices and dispatches
notification for every error that is set. It can be configured to parse log file
for system reported AER errors.
This plugin uses message log parser util so it depends on pull request #2154 .

### CODE REVIEW

**Comment by kwiatrox** [comment]
The build error is in part of code that previously passed.
It is probably wrong warning about universal zero initializer {0}.
Seems to be a known gcc bug - https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119.
I'm working on workaround for that issue.

**Comment by octo** [comment]
Hi @kwiatrox, thank you very much for your patch!

A new build issue popped up:

```
src/utils_message_parser.c:89:5: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'size_t' [-Werror=format=]
```

This can be fixed by using the `%zu` format.

**Comment by maryamtahhan** [comment]
@octo I think @kwiatrox  pushed a fix. Can you please review?

**Comment by kwiatrox** [comment]
@octo Fix for build problems is pushed. Do you have any other comments? I would appreciate any feedback. Thanks

**Comment by kwiatrox** [comment]
Hi @octo , as collectd release 5.8 is ready is there any chance to move forward with this request? I would appreciate any feedback. Let me know if there is anything I can do or any help/support is needed. Thanks.

**Comment by kwiatrox** [comment]
@octo, @rpv-tomsk is there any chance for this change being eventually reviewed and merged?
I'm not sure if there is any sense in rebasing and cleaning up this request.
The plugin is expected by opnfv [barometer](https://wiki.opnfv.org/display/fastpath/Barometer+Home) project.
If it is too big I can split it into smaller functional parts and open separate PRs for each to make it simpler to review.

**Comment by kwiatrox** [comment]
New version of plugin for PCIe errors #2733, closing this one.

**Pull request closed without merging**
