### PR TITLE
python plugin: Various shutdown fixes.

### LINKED ISSUE #1645: SIGSEGV in python module on 5.5.1
We're seeing occasional SIGSEGVs on a few of our 5.5.1 compilation of collectd.  We have a few commits on top of 2bda2a5648c87a2c5b8304238cd80ff17984c5cd but nothing related to the python plugin.  Details below.  We have one python plugin  module running.  Nothing is outputted in the log file other than collectdmon restarting it.  Any help would be appreciated.

[Thread debugging using libthread_db enabled] 
Using host libthread_db library \"/lib/x86_64-linux-gnu/libthread_db.so.1\". 
Core was generated by `collectd -C /etc/collectd/collectd.conf -f'. 
Program terminated with signal SIGSEGV, Segmentation fault. 
#0 0x00007f2999379aca in PyErr_Fetch () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 
#0 0x00007f2999379aca in PyErr_Fetch () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 
#1 0x00007f299930fc15 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 
#2 0x00007f299930d28b in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 
#3 0x00007f2999765403 in ?? () from /usr/lib/collectd/python.so 
#4 0x000000000040acbd in ?? () 
#5 0x000000000040ae44 in ?? () 
#6 0x000000000040e149 in plugin_shutdown_all () 
#7 0x0000000000406562 in main ()

Thread 1 (Thread 0x7f299c332740 (LWP 1498)): 
#0 0x00007f2999379aca in PyErr_Fetch () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 
#1 0x00007f299930fc15 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 
#2 0x00007f299930d28b in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 
#3 0x00007f2999765403 in ?? () from /usr/lib/collectd/python.so 
#4 0x000000000040acbd in ?? () 
#5 0x000000000040ae44 in ?? () 
#6 0x000000000040e149 in plugin_shutdown_all ()

### PR DESCRIPTION
**Pull request by trenkel**
None of these commits actually fixes #1645 but they're all necessary in order to get a fix.

### CODE REVIEW

**Comment by octo** [comment]
LGTM, thanks Sven! Could you please rebase on master, I think we already have the `SIGINT` commit there?

**Comment by trenkel** [comment]
This is based on master and the SIGINT stuff is not in this pull request.

**Comment by mfournier** [comment]
The latest build error is due to the jenkins server gone wild. I'll re-trigger the job manually in a moment.

**Comment by rubenk** [comment]
@trenkel I'm sorry, but the SIGINT stuff really is in your pull request.

I see that you're merging from octo/master, are you sure this is the right remote or are you merging from octo's personal copy of collectd/collectd?

**Comment by trenkel** [comment]
Well, fixed the usual way: Deleted both my github and my local client, made a fresh copy, reapplied patches, tried again, worked.
It's really paying off that I started keeping manual diffs in .patch files around in case git does random shit.

**Pull request closed without merging**
