### PR TITLE
collection3: Add Type for smart_temperature

### PR DESCRIPTION
**Pull request by cjmayo**
collection3: Add Type for smart_temperature

### CODE REVIEW

**Comment by cjmayo** [comment]
Copied from Type temperature.

I don't understand what the ChangeLog check is asking for. I've ended up with the commit title duplicated in the commit body, that must need to go.

**Comment by octo** [comment]
Hi @cjmayo,

thank you very much for your PR! The "ChangeLog" check is very new, so it is in our best interest to document it well. Could you tell me what you find confusing so we can improve? Did you click the "Details" link yet?

Best regards,
—octo

**Comment by cjmayo** [comment]
I did click on Details - I think the only truly ambiguous thing there is if the body should contain **only** the one-line description.
I managed to miss that it is was talking about the PR and not the commit, maybe I was rushing, maybe body made me think of commit - although it looks like that is what the GitHub API calls field, the help article:
https://help.github.com/articles/about-pull-requests/
calls it a summary.

Anyway, I've fixed the commit body. Let's see how the ChangeLog check goes...

**Comment by octo** [comment]
Hi @cjmayo, thanks for your feedback! I created #3061 to hopefully cause less confusion.

The "ChangeLog:" line needs to go into the PR description, not the commits. Changes in contrib/ we don't usually mention, so this PR is going to be excempt.

**Pull request merged**
