### PR TITLE
.cirrus.yml: Read expected plugins from branch specific config file.

### PR DESCRIPTION
**Pull request by octo**
This is an attempt to configure different expected plugins based on the branch.

### CODE REVIEW

**Comment by eero-t** [comment]
Branch specific lists of plugins could be added within this PR too, so we could see whether tests pass then.

**Comment by eero-t** [comment]
Option 1. sounds fine to me.

Is there some base set of plugins that should always succeed regardless of branch or distro?    I.e. would it make sense to split the list to 2 parts?

**Comment by eero-t** [comment]
@octo are you waiting on comment from @mrunge?

**Comment by octo** [comment]
Closing in favor of #4208

**Comment by octo** [comment]
@eero-t @mrunge Thanks for your input! Option 1 it is.

**Pull request closed without merging**
