### PR TITLE
snmp plugin: HostOID and FilterOID options

### PR DESCRIPTION
**Pull request by rpv-tomsk**
Issue: #174

Also a bug found and fixed:  `Ignore` option was ignored for numeric Instance OIDS.

Added new options FilterOID, FilterValues and FilterIgnoreSelected.
These allows to ignore parts of the MIB by its values.

### CODE REVIEW

**Comment by faxm0dem** [comment]
I just tested this branch successfully

**Comment by faxm0dem** [comment]
I tried both `TypeInstanceOID` and `PluginInstanceOID`.
I also tested using both simultaneously for which the config parser fails as expected

**Comment by rpv-tomsk** [comment]
Just finished a /big/ refactoring.

**Comment by rpv-tomsk** [comment]
Fabien, you can prepare documentation updates, if you have a time. 
Thanks
)

**Comment by faxm0dem** [comment]
sure thing! will you add HostOID or shall I give it a shot?

**Comment by rpv-tomsk** [comment]
Question to discuss  #1: 

Should we add `NOTICE`  when table row is skipped (`suffix_skipped = 1`) ?

Question to discuss #2:

Highly probable we should disable `TypeInstanceOID` by default (when not set explicitly) when `HostOID` is set. In current implementation `TypeInstanceOID` behaves sending 'SUBID' as `type_instance`.

**Comment by faxm0dem** [comment]
works like a charm, thanks a bunch!
BTW is there a good reason why we prohibit both Type and Plugin InstanceOID at the same time?

**Comment by rpv-tomsk** [comment]
>BTW is there a good reason why we prohibit both Type and Plugin InstanceOID at the same time?

Existed implementation (before `*InstanceOID` options added) supported only one column with string value.
At that point there was no reasons (use-cases) to support both options at the same time and I tried to do minimal changes.

This patch reworks plugin to support multiple columns with string values.
Using this new scheme it is possible to allow (implement support of) both `TypeInstanceOID` and `PluginInstanceOID`.

**Comment by rpv-tomsk** [comment]
@rubenk 

Ruben, what do you think:

The `csnmp_dispatch_table()` function.  It intended to submit 'rows' from table of values, got by SNMP.
Only 'full' rows (when all columns has data with same suffix aka subid) are submitted - implemented via `suffix_skipped` flag. When one of columns has no more data - `have_more` flag stops submission.

Why then we determine suffix in different ways depending on whether the instance is configured?
I think the result will be the same if we will determine suffix from first value column in all cases.

Is I'm correct?

**Comment by rpv-tomsk** [comment]
Fabien, can you please test debug output of this code?

I'm trying to check if `OID_TYPE_VARIABLE` should check for `SNMP_ENDOFMIBVIEW` like `OID_TYPE_INSTANCE` and `OID_TYPE_HOST`. 

My equipment behaves in a wrong way, so I can't check this:
```
# snmpwalk -v2c -c public 192.168.0.100 iso.3.6.1.2.1.7.5.1.1.192.168.0.100
iso.3.6.1.2.1.7.5.1.1.192.168.0.100.64518 = IpAddress: 192.168.0.100
iso.3.6.1.2.1.7.5.1.1.192.168.0.100.64515 = IpAddress: 192.168.0.100
Error: OID not increasing: iso.3.6.1.2.1.7.5.1.1.192.168.0.100.64518
 >= iso.3.6.1.2.1.7.5.1.1.192.168.0.100.64515
```

The goal is to put OID of last MIB branch to `Values` as last option value and disable `Instance`, and check for `is_endofmib = true` in debug output.

Can you please do this?

**Comment by rpv-tomsk** [comment]
How `Ignore` option should behave if we allow to set `PluginInstanceOID` and `TypeInstanceOID` simultaneously?

**Comment by faxm0dem** [comment]
so you just want to see the output of collectd in debug mode for a config using TypeInstanceOID?

**Comment by faxm0dem** [comment]
compilation fails when using `--enable-debug`:

```
In file included from ./src/daemon/common.h:33:0,
                 from src/snmp.c:29:
src/snmp.c: In function ‘csnmp_read_table’:
src/snmp.c:1668:13: error: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘size_t {aka long unsigned int}’ [-Werror=format=]
             "snmp plugin: src.oid_len = %d root.oid_len = %d is_endofmib = %s",
             ^
./src/daemon/plugin.h:396:42: note: in definition of macro ‘DEBUG’
 #define DEBUG(...) plugin_log(LOG_DEBUG, __VA_ARGS__)
                                          ^~~~~~~~~~~
src/snmp.c:1668:13: error: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘size_t {aka long unsigned int}’ [-Werror=format=]
             "snmp plugin: src.oid_len = %d root.oid_len = %d is_endofmib = %s",
             ^
./src/daemon/plugin.h:396:42: note: in definition of macro ‘DEBUG’
 #define DEBUG(...) plugin_log(LOG_DEBUG, __VA_ARGS__)
                                          ^~~~~~~~~~~
```

**Comment by rpv-tomsk** [comment]
>so you just want to see the output of collectd in debug mode for a config using TypeInstanceOID?

No, for simple config with `Value` and without any other OIDs set.
`Value` should point to OID prefix which will be prefix for 'last variables' as per `snmpwalk` output.

**Comment by rpv-tomsk** [comment]
>compilation fails when using --enable-debug:

Replace that with:

```
DEBUG(
            "snmp plugin: src.oid_len = %" PRIsz " root.oid_len = %" PRIsz " is_endofmib = %s",
            vb_name.oid_len, (data->values + i)->oid_len,
            (vb->type == SNMP_ENDOFMIBVIEW) ? "true" : "false");
```

**Comment by faxm0dem** [comment]
ack. so my device's response to snmpwalk ends like this:

```
[...]
iso.3.6.1.2.1.11.27.0 = Counter32: 0
iso.3.6.1.2.1.11.28.0 = Counter32: 8686545
iso.3.6.1.2.1.11.29.0 = Counter32: 462836
iso.3.6.1.2.1.11.30.0 = INTEGER: 1
iso.3.6.1.2.1.11.31.0 = Counter32: 0
iso.3.6.1.2.1.11.32.0 = Counter32: 0
```

which `Value` should I use?

**Comment by rpv-tomsk** [comment]
Can you please do two tries:

1) `Values "iso.3.6.1.2.1.11.32"`
2) `Values "iso.3.6.1.2.1.11"`

Thanks/

**Comment by faxm0dem** [comment]
with table = true? (sorry for all the questions ;))

**Comment by rpv-tomsk** [comment]
>with table = true? (sorry for all the questions ;))

Yes, we almost do not touch code for `table = false` case.

**Comment by rpv-tomsk** [comment]
Added new commits, code and documentation are nearby ready to release.
Please check all these carefully. Also, it should be fully backwards-compatible.

**Comment by faxm0dem** [comment]
### iso.3.6.1.2.1.11.32
```
Created new plugin context.
[2018-06-15 11:45:59] plugin_load: plugin "logfile" successfully loaded.
[2018-06-15 11:45:59] type = logfile, key = File, value = STDOUT
[2018-06-15 11:45:59] type = logfile, key = LogLevel, value = debug
[2018-06-15 11:45:59] plugin_load: plugin "unixsock" successfully loaded.
[2018-06-15 11:45:59] type = unixsock, key = DeleteSocket, value = true
[2018-06-15 11:45:59] type = unixsock, key = SocketFile, value = /tmp/collectd-sock
[2018-06-15 11:45:59] type = unixsock, key = SocketPerms, value = 0770
[2018-06-15 11:45:59] plugin_load: plugin "snmp" successfully loaded.
[2018-06-15 11:45:59] snmp plugin: dd = { name = if_octets, type = gauge, is_table = true, values_len = 1,
[2018-06-15 11:45:59] snmp plugin:        plugin_instance = (null), type_instance = (null),
[2018-06-15 11:45:59] snmp plugin:        instance_by_oid = SUBID, to_plugin_instance = false }
[2018-06-15 11:45:59] snmp plugin: Collect: host = plop, data[0] = if_octets;
[2018-06-15 11:45:59] snmp plugin: hd = { name = plop, address = ccapc-b01, community = public, version = 2 }
[2018-06-15 11:45:59] Done parsing `/opt/collectd/share/collectd/types.db'
[2018-06-15 11:45:59] interval_g = 10.000;
[2018-06-15 11:45:59] timeout_g = 2;
[2018-06-15 11:45:59] hostname_g = localhost;
[2018-06-15 11:45:59] Created new plugin context.
[2018-06-15 11:45:59] unixsock plugin: socket path = /tmp/collectd-sock
[2018-06-15 11:45:59] plugin_read_thread: Handling `snmp-plop'.
[2018-06-15 11:45:59] Created new plugin context.
[2018-06-15 11:45:59] Initialization complete, entering read-loop.
[2018-06-15 11:45:59] unixsock plugin: No such group: `collectd'
[2018-06-15 11:45:59] unixsock plugin: Calling accept..
[2018-06-15 11:45:59] snmp plugin: csnmp_read_table (host = plop, data = if_octets)
[2018-06-15 11:46:00] snmp plugin: src.oid_len = 9 root.oid_len = 8 is_endofmib = false
[2018-06-15 11:46:00] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:46:00] snmp plugin: src.oid_len = 14 root.oid_len = 8 is_endofmib = false
[2018-06-15 11:46:00] snmp plugin: host = plop; data = if_octets; i = 0; Value probably left its subtree.
[2018-06-15 11:46:00] snmp plugin: all variables have left their subtree
[2018-06-15 11:46:00] plugin_read_thread: read-function of the `snmp-plop' plugin took 0.051339 seconds.
[2018-06-15 11:46:00] plugin_read_thread: Effective interval of the `snmp-plop' plugin is 300.000 seconds.
[2018-06-15 11:46:00] Created new plugin context.
[2018-06-15 11:46:00] plugin_read_thread: Next read of the `snmp-plop' plugin at 1529056259.471.
[2018-06-15 11:46:00] plugin_dispatch_values: No write callback has been registered. Please load at least one output plugin, if you want the collected data to be stored.
[2018-06-15 11:46:00] plugin_dispatch_values: time = 1529055959.525; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 0;
[2018-06-15 11:46:00] uc_insert: Added plop/snmp/gauge-0 to the cache.
```

### iso.3.6.1.2.1.11

```
Created new plugin context.
[2018-06-15 11:47:03] plugin_load: plugin "logfile" successfully loaded.
[2018-06-15 11:47:03] type = logfile, key = File, value = STDOUT
[2018-06-15 11:47:03] type = logfile, key = LogLevel, value = debug
[2018-06-15 11:47:03] plugin_load: plugin "unixsock" successfully loaded.
[2018-06-15 11:47:03] type = unixsock, key = DeleteSocket, value = true
[2018-06-15 11:47:03] type = unixsock, key = SocketFile, value = /tmp/collectd-sock
[2018-06-15 11:47:03] type = unixsock, key = SocketPerms, value = 0770
[2018-06-15 11:47:03] plugin_load: plugin "snmp" successfully loaded.
[2018-06-15 11:47:03] snmp plugin: dd = { name = if_octets, type = gauge, is_table = true, values_len = 1,
[2018-06-15 11:47:03] snmp plugin:        plugin_instance = (null), type_instance = (null),
[2018-06-15 11:47:03] snmp plugin:        instance_by_oid = SUBID, to_plugin_instance = false }
[2018-06-15 11:47:03] snmp plugin: Collect: host = plop, data[0] = if_octets;
[2018-06-15 11:47:03] snmp plugin: hd = { name = plop, address = ccapc-b01, community = public, version = 2 }
[2018-06-15 11:47:03] Done parsing `/opt/collectd/share/collectd/types.db'
[2018-06-15 11:47:03] interval_g = 10.000;
[2018-06-15 11:47:03] timeout_g = 2;
[2018-06-15 11:47:03] hostname_g = localhost;
[2018-06-15 11:47:03] Created new plugin context.
[2018-06-15 11:47:03] unixsock plugin: socket path = /tmp/collectd-sock
[2018-06-15 11:47:03] Initialization complete, entering read-loop.
[2018-06-15 11:47:03] plugin_read_thread: Handling `snmp-plop'.
[2018-06-15 11:47:03] Created new plugin context.
[2018-06-15 11:47:03] unixsock plugin: No such group: `collectd'
[2018-06-15 11:47:03] unixsock plugin: Calling accept..
[2018-06-15 11:47:03] snmp plugin: csnmp_read_table (host = plop, data = if_octets)
[2018-06-15 11:47:03] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:03] snmp plugin: Parsed int32 value is 8687916.
[2018-06-15 11:47:03] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:03] snmp plugin: Parsed int32 value is 8687904.
[2018-06-15 11:47:03] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:03] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:03] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:03] snmp plugin: Parsed int32 value is 24.
[2018-06-15 11:47:03] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:03] snmp plugin: Parsed int32 value is 1001905.
[2018-06-15 11:47:03] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:03] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:03] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:03] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 10151392.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 2202741.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 6485177.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 1001905.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 8687928.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 463058.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 1.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 9 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: Parsed int32 value is 0.
[2018-06-15 11:47:04] snmp plugin: src.oid_len = 14 root.oid_len = 7 is_endofmib = false
[2018-06-15 11:47:04] snmp plugin: host = plop; data = if_octets; i = 0; Value probably left its subtree.
[2018-06-15 11:47:04] snmp plugin: all variables have left their subtree
[2018-06-15 11:47:04] Created new plugin context.
[2018-06-15 11:47:04] Created new plugin context.
[2018-06-15 11:47:04] plugin_dispatch_values: No write callback has been registered. Please load at least one output plugin, if you want the collected data to be stored.
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 2.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-2.0 to the cache.
[2018-06-15 11:47:04] Filter subsystem: Built-in target `write': Dispatching value to all write plugins failed with status 2 (ENOENT). Most likely this means you didn't load any write plugins.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] Created new plugin context.
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 1.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-1.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] Created new plugin context.
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 4.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-4.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] Created new plugin context.
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 5.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-5.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 3.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-3.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 6.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-6.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 12.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-12.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 13.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-13.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 14.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-14.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 15.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-15.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 16.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-16.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 17.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-17.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 18.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-18.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 19.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-19.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 20.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-20.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 21.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-21.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 22.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-22.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 24.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-24.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 25.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-25.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 26.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-26.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 27.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-27.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 28.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-28.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 29.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-29.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 30.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-30.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 31.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-31.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 32.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-32.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 10.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-10.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 11.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-11.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 8.0;
[2018-06-15 11:47:04] plugin_read_thread: read-function of the `snmp-plop' plugin took 0.731178 seconds.
[2018-06-15 11:47:04] plugin_dispatch_values: time = 1529056024.055; interval = 300.000; host = plop; plugin = snmp; plugin_instance = ; type = gauge; type_instance = 9.0;
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-8.0 to the cache.
[2018-06-15 11:47:04] Available write targets: [none]
[2018-06-15 11:47:04] uc_insert: Added plop/snmp/gauge-9.0 to the cache.
```

**Comment by rpv-tomsk** [comment]
Ok, so there is no `is_endofmib = true`...
Thanks!

**Comment by rpv-tomsk** [comment]
And one more feature implemented, as requested in #2637.

Added new options `FilterOID`, `FilterValues` and `FilterIgnoreSelected`.
These allows to ignore parts of the MIB by its values.

**Comment by rpv-tomsk** [comment]
@rubenk 

Hi, Ruben!

I just finished working on this. 
Please take a look.

Thanks!

**Comment by faxm0dem** [comment]
thanks so much @rpv-tomsk

**Comment by rpv-tomsk** [comment]
This PR is waiting for feedbacks and reviews!

**Pull request merged**
