### PR TITLE
Cleanup dpdk detection

### PR DESCRIPTION
**Pull request by rubenk**

### CODE REVIEW

**Comment by rubenk** [comment]
@taraschornyi could you give this PR a try? I'm having trouble doing a custom build from dpdk git to a different location.

**Comment by rubenk** [comment]
Supersedes #2038

**Comment by taraschornyi** [comment]
hi @rubenk ,
I like these changes.  
Taras 
P.S.
I've tested them with latest dpdk on Ubuntu 16.04

**Comment by rubenk** [comment]
Very well, thank you both @maryamtahhan and @taraschornyi.

**Pull request merged**
