### PR TITLE
Revert "Remove grpc from Mac builds for now"

### PR DESCRIPTION
**Pull request by mrunge**
This reverts commit e95e850a1688e6bee4ee87b27f92f2a4ffaf7a91.

This reverts https://github.com/collectd/collectd/pull/3353 which was done in attempt to fix https://travis-ci.org/collectd/collectd/jobs/625893485 seen in https://github.com/collectd/collectd/pull/3350

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
You can't revert your changes? he-he
Nobody can.
Be happy because you have no permissions to merge.

Welcome to untrusted maintainers community.

**Comment by rubenk** [comment]
Hmm, seems I can't override CI and merge this, sorry.

**Comment by rpv-tomsk** [comment]
@rubenk, Welcome to untrusted maintainers community too.

**Comment by mrunge** [comment]
> Hmm, seems I can't override CI and merge this, sorry.

Thank you for trying! We'll figure this out.

**Comment by mrunge** [comment]
https://github.com/collectd/collectd/pull/3350 was rebased and CI passed then. Xcode apparently blocks us here and *this* PR seems to be the workaround until the underlying grpc issue is fixed.

**Pull request closed without merging**
