### PR TITLE
Adjust SFOS build scripts

### PR DESCRIPTION
**Pull request by rinigus**
This makes it possible to build on local SDK and OBS

### CODE REVIEW

**Comment by rinigus** [comment]
Sorry, PR sent to wrong repository

**Comment by mrunge** [comment]
Thank you for your PR. There are a few additional plugins included, which may be useful in collectd in general. Would you mind to propose them here as addition?

**Comment by rinigus** [comment]
I could. which plugins are of interest? I suspect some of them were already proposed, but never got merged.

**Comment by mrunge** [comment]
This was more an offer to get the additional plugins upstream, i.e. reduce the delta between your fork and upstream.

**Comment by rinigus** [comment]
I will have to look through. Some plugins are Sailfish specific as well as rewrite of the main loop of the daemon. The latter was needed to allow mobile device to suspend/resume for collectd to get the stats as intended.

As for plugins that maybe of interest for others, that I have to check.

**Pull request closed without merging**
