### PR TITLE
statsd plugin: Implement the "CounterSum" option.

### PR DESCRIPTION
**Pull request by octo**
CC: @jamtur01, @pyr, @duylong
Issues: #929, #1282, #1311

### CODE REVIEW

**Comment by mfournier** [comment]
@octo, would this patch be merged in, keep in mind that @pyr's patch from #1311 was cherry-picked to collectd-5.4 & collectd-5.5 (but not part of any release yet).

The reasoning we had was that it qualified as a bugfix as it intended to make collectd's statsd compatible with the reference implementation.

So either this one would need to get backported too, or @pyr's patch reverted, for the sake of a consistent upgrade from 5.4/5.5 to 5.6.

**Comment by octo** [comment]
@mfournier Thanks for the heads up! I'm a bit on the fence, to be honest: on the one hand #1311 is already in the 5.4 branch, on the other hand I don't really want to push new config options to that branch …

**Comment by jamtur01** [comment]
I'm not fussed about the 5.4 branch. I asked @pyr to back port to 5.5 because that's the version where our collectd is likely to sit for a while.

**Comment by jamtur01** [comment]
And thanks for this fix!

**Comment by rj33** [comment]
What was the final decision on merging this into 5.5.x? Are we waiting for 5.6.0 at this stage to see this fix in a release?

**Pull request merged**
