### PR TITLE
Add changelog entries for collectd 5.8.1

### PR DESCRIPTION
**Pull request by mrunge**
Add a changelog for collectd 5.8.1

I could also add this to the wiki, once I get an account there. The file has also been sent some days ago via email

### CODE REVIEW

**Comment by sunkuranganath** [comment]
Double checking that all contributions (fixes, etc.) from our team are available on 5.8. Will update shortly.

**Comment by octo** [comment]
Thanks Matthias!

We usually write the change log in the wiki and then there are scripts to generate the ChangeLog file, Github release and homepage announcements from there. I've converted your work to the wiki markup, it's here: https://collectd.org/wiki/index.php/Version_5.8#Release_5.8.1

I'll double check that this is up to date and then update the ChangeLog in the 5.8 branch.

**Comment by mrunge** [comment]
Thank you @octo . Until recently, I didn't had an account to the wiki. That has been fixed now.
When we met in Munich, you explained to me, there is a script to create a changelog from the wiki page, so using the script should be preferred over creating a changelog directly.

**Comment by octo** [comment]
Superseeded by #2965

**Pull request closed without merging**
