### PR TITLE
ChangeLog: python: Fix compile-time errors about deprecation via ifdefs.

### PR DESCRIPTION
**Pull request by systemcrash**
ChangeLog: python: Fix compile-time errors about deprecation via ifdefs.

### CODE REVIEW

**Comment by mrunge** [comment]
Thank you for your PR. I took the liberty to update the description (there was a space in front of "ChangeLog".) Apparently, the parser was a bit picky.

**Review by mrunge — APPROVED** [review]
Thank you, this will safe us (and package maintainers for distributions) some headaches, when python-3.11 comes out.

Unfortunately, this is currently blocked by CI, let's see what we can do about this.

**Comment by systemcrash** [comment]
Hmm, does this mean you can move forward with collectd here, or did you get just enough PRs approved to.. fork?

**Comment by mrunge** [comment]
We can more forward with *this* project here, I'm going to remove the clone. That is great news.

**Pull request merged**
