### PR TITLE
Allow custom plugin name for 'curl', 'memcachec', 'tail' and 'tail_csv' plugins.

### PR DESCRIPTION
**Pull request by rpv-tomsk**
Like added in  #1558 and #1563 , added option 'PluginName' to other Collectd plugins:

tail plugin: Allow custom plugin name for file instances
tail_csv: Allow custom plugin name for file instances
curl plugin: Allow custom plugin name for each Page block
memcachec: Allow custom plugin name for each Page block

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
Hi @toni-moreno ,

>Could be a great idea recover the this change to use in all general purpose pugins.

Stay tuned.

----

If someone knows about other generic plugins I missed in this work, please inform me, I will update this PR.

**Comment by rpv-tomsk** [comment]
Hi @toni-moreno ,

>Could be a great idea recover the this change to use in all general purpose pugins.

Stay tuned.

----

If someone knows about other general purpose plugins I missed in this work, please inform me, I will update this PR.

**Comment by mfournier** [comment]
I'm a bit concerned about adding a per-plugin config option to change the plugin name. With the filter chains system, we already have a generic way to rename the host, plugin, plugin_instance and type_instance on the fly.

Agreed it's not as simple as a one-line configuration option, but it works for all current and future plugins, without adding any code.

Am I missing something ? What's the motivation behing this change ?

**Comment by rpv-tomsk** [comment]
Existence of generic way for renaming is good, but for 'general purpose' plugins configuration by per-plugin option is _much_ simplier. 

As for me, as sysadm, I _never_ touched Collectd 'filters' configuration at all. Its usage (for renaming), as for me (again), is like using iptables to redirect HTTP port 80 when 'webserver' listens 65079 and that value is unchangeable.

Currently, other general-purpose plugins allows to specify PluginName: 'exec'; 'java' ('GenericJMX'), 'python', 'perl'  bindings. And there is no requirement to rename fixed 'exec' / 'java' / 'python' / 'perl' plugin name to required value via filters - that plugins just works. That is simple and simply works - that is what expected by people.

I see no problems about adding PluginName option to curl*, tail* and memcachec plugins (and to possible future general-purpose plugins too).

**Comment by toni-moreno** [comment]
Hi @mfournier I agree with @rpv-tomsk . 

Anyway 2 years ago I was playing with filters and I was not able to configure filters to change plugin name for combined plugins and instanceid.  how can be done now?

I think also this code could be easily maintainable , since there is no much generic purpose plugins, and there is not much code to change.

I can help if you need. 

Thank you very much.

**Comment by tokkee** [comment]
On another note, there are now a bunch of PRs all related to this topic. @rpv-tomsk could you open a separate issue as a feature request for this and collecting all information (and conversations) in one place?

**Comment by octo** [comment]
I tend to agree with @mfournier here: changing the plugin name is not essential, since in all the rather generic plugins you can control large parts of the identifier already. If you have a good use case, you can change the *plugin* with generic tools (i.e. filter chains) that work for *all* metrics.

**Comment by rpv-tomsk** [comment]
>changing the plugin name is not essential

Completely disagreed. Did you look into #1558 and #1563, especially into https://github.com/collectd/collectd/pull/1563/commits/0dcb6a619165d4ae16d19773399c8618b37e2fc7 ?

>If you have a good use case, you can change the plugin with generic tools (i.e. filter chains) that 
>work for all metrics.

* There is MANY good use-cases. These (with patch proposed) plugins are 'generic', so people can use them for gathering metrics from different part of their systems. That is their common use, they are implemented for this, so there is many use cases exists. For example, some metrics from curl_json can be sent as 'phpfpm' plugin name and some as another plugin name. I use  'Tail' plugin for gathering metrics which are sent as 'postfix' and 'apache' plugin names.

*  That looks too complex to use filters for these simple tasks. It is much easier to put one directive to set 'PluginName' than write complex filter with matches and sets. Filters is not convenient for this as configuration split is inconvenient in practice.  

//As for me, I do not use 'filters' in none of my servers, and I have 50+ of them. 
//I think many peoples does not use that too. 

* The possibility to set 'plugin instance' value from the values obtained by plugin is required.
And the possibility to set 'plugin name' makes things (configuration) holistic.

So, proposed possibility to set 'PluginName' is very useful, powerful and easy to use.

Also this feature is easily implemented and does not require efforts to support it in future.

**Comment by octo** [comment]
You're right in that there is no "service" label in *collectd* and *plugin* can kind of fill that position.

Please use the config option `Plugin` for this purpose everywhere. Open an umbrella issue, like @tokkee suggested, to keep track of all ongoing work in this direction and then create one PR per plugin, referencing that tracking issue.

Thanks and best regards,
—octo

**Comment by rpv-tomsk** [comment]
>and then create one PR per plugin, referencing that tracking issue.

Hi! I'm going to continue this work. 
Which branch should I use as PR target?

**Comment by octo** [comment]
Hi @rpv-tomsk, thanks for looking into this! Please open PRs implementing new features against the *master* branch.

**Comment by rpv-tomsk** [comment]
Renamed 'PluginName' option to unified 'Plugin' form.

**Comment by rpv-tomsk** [comment]
Hi guys! 

There is some buildbot problem, the CI check has failed for this PR. Please take care.

Thanks!

**Comment by rpv-tomsk** [comment]
Rebased to current master branch.

**Comment by rpv-tomsk** [comment]
ping

**Comment by rpv-tomsk** [comment]
Ping me if you want this PR to be merged, I will rebase it to current master.

**Comment by rpv-tomsk** [comment]
The PR rebased to current master.

Please take a look and merge it.

**Pull request merged**
