### PR TITLE
fix openldap segfault when ldapi is used

### PR DESCRIPTION
**Pull request by marekbecka**
If LDAPI protocol is used in configuration, e.g. URL "ldapi://", ldap_url_parse returns NULL in `ludpp->lud_host`. Strdup has undefined behaviour if NULL argument is used and segmentation fault can also occur.

### CODE REVIEW

**Comment by octo** [comment]
LGTM, though I'd prefer to lose the `else`, i.e.:

```c
if (ldap_url_parse ()) != 0) {
  // error handling
}

st->host = (ludpp->lud_host != NULL)
    ? strdup (ludpp->lud_host)
    : NULL;
```

**Comment by marekbecka** [comment]
I have updated patch. I'm not sure if conditional assignment should be used, a cldap_t structure is zeroed at cldap_config_add.

**Comment by octo** [comment]
LGTM, thanks @marekbecka!

@mfournier since you assigned yourself, do you have any further comments?

**Comment by mfournier** [comment]
Thanks @marekbecka ! I just merged this now to the collectd-5.5 branch,

**Pull request closed without merging**
