### PR TITLE
Cppflags backport

### PR DESCRIPTION
**Pull request by mrunge**
This is a backport of https://github.com/collectd/collectd/pull/3207/

### CODE REVIEW

**Comment by mrunge** [comment]
It would be nice to be able to merge this.

**Comment by rpv-tomsk** [comment]
Why do you use "unlisted change" here?
As this is bugfix, it must me included into new 5.9 release changelog.

**Comment by mrunge** [comment]
As in the last backport, I cherry-picked the patches and included the changes in the changelog manually. 

Of course, it's debatable how we are doing this. In the past, bugfixes had to go to the stable release first, and octo used to merge them to master from time to time. Indeed, I did this as unlisted change, as I don't want to steal credit from original authors.

**Comment by rpv-tomsk** [comment]
>Indeed, I did this as unlisted change, as I don't want to steal credit from original authors.

Reasonable, I missed such behavior of this mech.

**Comment by mrunge** [comment]
Thank you!

**Pull request merged**
