### PR TITLE
Remove section about self-approve patches

### PR DESCRIPTION
**Pull request by mrunge**
We moved away from that model and every commit should go
through a review.

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
I wish you good luck, while you doing rule changes by fact of technical changes.
Also, I wish you good luck waiting for minor changes review and recommend to do not approve changes until at least three reviewers will approve PR.

**Comment by mrunge** [comment]
I am changing the documentation to reflect the current state.

**Comment by rpv-tomsk** [comment]
By this, you state what current state is something that should really be.
But, maybe, current state should be changed to match existing rules, and not rules should be changed.

**Comment by rpv-tomsk** [comment]
@octo, I think you lost control on project.

**Comment by rpv-tomsk** [comment]
>We moved away from that model and every commit should go through a review.

Then you also must remove following section too:

```
### Repository access

You have write access to the *collectd/collectd* repository. Please use it
responsibly.
```

**Pull request merged**
