### PR TITLE
[collectd 6] Misc "gpu_sysman" plugin fixes & improvements

### PR DESCRIPTION
**Pull request by eero-t**
ChangeLog: Misc "gpu_sysman" plugin fixes & improvements

Changes:
* Fix memory corruption / crashes with latest L0 backend versions
  * Resulting from backend implementation API change to a previously under-specified behavior, that is documented now in L0 spec
* Improve error logging by reporting the related Sysman API error code
   * This is by far the largest change, but helps debugging metric reporting errors a lot
* Avoid (unlikely) issues of:
   * Reporting incorrect metric labels
   * Disabling power ratio reporting unnecessarily
* Add support for memory "health", frequency "throttled_by", and metric "pci_dev" labels
  * First 2 are especially useful for GPU issue monitoring / alerts on servers
* Minor code consistency improvements
* Slight increase in tests code coverage
* Code comment fixes

### CODE REVIEW

**Comment by eero-t** [comment]
@mrunge crash / memory corruption fix is rather important to get in.

I was also wondering whether you have any comments on how I'm avoiding stale labels (see commit message in https://github.com/collectd/collectd/pull/4079/commits/1ef67081d39479c8de77e449d548c8cd5021f763)?

----

As to plugin dependencies...

RedHat includes now Level-Zero frontend package, but does not build compute-runtime with L0 backend yet (due to issues with LLVM15?), while Debian Testing just started providing both.  More distro support info at: https://github.com/oneapi-src/level-zero/issues/73

Seems that Intel driver package repositories [1], Debian and RedHat packaging, all use different package names for those...

[1] https://dgpu-docs.intel.com/installation-guides/index.html

**Comment by mrunge** [comment]
> As to plugin dependencies...
> 
> RedHat includes now Level-Zero frontend package, but does not build compute-runtime with L0 backend yet (due to issues with LLVM15?), while Debian Testing just started providing both. More distro support info at: [oneapi-src/level-zero#73](https://github.com/oneapi-src/level-zero/issues/73)
> 
> Seems that Intel driver package repositories [1], Debian and RedHat packaging, all use different package names for those...
> 
> [1] https://dgpu-docs.intel.com/installation-guides/index.html

The easiest path to get dependencies into Red Hat repositories would go through Fedora and then get it added to CentOS Stream. Stream is what will become the next CentOS, and CentOS is the upstream for RHEL. RockyLinux/Alma/? will then inherit their packages from CentOS.

I don't necessarily see package naming differences as an issue, since you'd require the dependencies in e.g the collectd .spec file (for Fedora/RHEL/compatible distributions)

**Comment by mrunge** [comment]
> @mrunge crash / memory corruption fix is rather important to get in.
> 
> I was also wondering whether you have any comments on how I'm avoiding stale labels (see commit message in [1ef6708](https://github.com/collectd/collectd/commit/1ef67081d39479c8de77e449d548c8cd5021f763))?

Unfortunately, I do not have a good answer to that. I will take a look at this PR, and since it fixes an important issue, I'd be inclined to get it in and fix potential issues as follow-up.

**Review by mrunge — APPROVED** [review]

**Comment by eero-t** [comment]
> The easiest path to get dependencies into Red Hat repositories would go through Fedora and then get it added to CentOS Stream. Stream is what will become the next CentOS, and CentOS is the upstream for RHEL. RockyLinux/Alma/? will then inherit their packages from CentOS.

Fedora driver packages owners are the ones doing this.  I would assume those changes to eventually trickle down to long term RH distros automatically.

My point was more that:
* L0 header/frontend package (from fedora/debian/ubuntu, or Intel repos) is enough to build the plugin and run tests (which fake L0 Sysman APIs)
* Backend is needed only to actually use the Sysman plugin, and that should be also in Fedora soon

**Pull request merged**
