### PR TITLE
configure.ac: Fix include of "utils/mount/mount.h".

### PR DESCRIPTION
**Pull request by octo**
Fixes a regression introduced in 6378ec288f34ff250b2971a1452338a2b34c240a.

### CODE REVIEW

**Comment by octo** [comment]
Oh, sorry, I rebased on top of your POD fix, hoping to make Cirrus CI happy ;)

**Comment by rubenk** [comment]
Hah, no worries :-)

**Comment by octo** [comment]
Looks like we're getting somewhere :)

**Comment by rubenk** [comment]
woohoo \o/

**Pull request merged**
