### PR TITLE
lua plugin: Make it possible to register more than one reader/writer; bugfixes; cleanup.

### PR DESCRIPTION
**Pull request by rpv-tomsk**
Changelog: lua plugin: Make it possible to register more than one reader/writer (bug)
Changelog: lua plugin: Don't destroy interpreter too early (bug)
Changelog: lua plugin: free mutex on callback destroy (issue)
Changelog: lua plugin: Cleanup

Closes: #2379
Closes: #3139

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
Hi, @rubenk 

Ruben, can you please review this? Especially interested in
"Added possibility to pass LUA callback as global-scope function name.  In this case callback name is built using function name, not callback index."

**Comment by rpv-tomsk** [comment]
cc @feckert 

Florian, can you please take a look on this?

**Comment by rpv-tomsk** [comment]
Thanks!

**Comment by feckert** [comment]
Thanks for your work is working as expected.

**Pull request merged**
