### PR TITLE
Update master with 5.11 changelog

### PR DESCRIPTION
**Pull request by kkepka**
Merge collectd-5.11 back to master

### CODE REVIEW

**Comment by rubenk** [comment]
Why can't we just merge the 5.11 branch back into master instead of cherrypicking?

**Comment by kkepka** [comment]
> Why can't we just merge the 5.11 branch back into master instead of cherrypicking?

That could also be the way, thank you for suggestion Ruben, will remember for future.
Do you want me to fix/change PR? If that's preferred way I'd be happy to follow.

**Comment by rubenk** [comment]
Yes, please open a new PR that merges 5.11 into master.

**Comment by kkepka** [comment]
> Yes, please open a new PR that merges 5.11 into master.

Updated this one, hope it's ok?

**Comment by rpv-tomsk** [comment]
No matter how it looks, it’s important what’s inside.

**Pull request merged**
