### PR TITLE
exec plugin: replace select with poll

### PR DESCRIPTION
**Pull request by kwiatrox**
ChangeLog: exec plugin: replace select with poll

Replace select with poll to allow big File Descriptors values on systems which allow more than 1024 open FDs. Other than that there is no any change in functionality.
This fixes issue #3322.

### CODE REVIEW

**Comment by rubenk** [comment]
Thank you. Did you test this on all OS's we support?

**Comment by kkepka** [comment]
I think verification of this patch may not been so comprehensive and broad in terms of multiple OS's, but will let @kwiatrox to let know about details where it has been checked.

Out of curiosity - what is actually the list of "all OS's we support"?
few of them are mentioned on https://collectd.org/features.shtml , like `Linux, Solaris, Mac OS X, AIX, FreeBSD, NetBSD, and OpenBSD`, but is there any more specific e.g. particular linux distributions and ver of releases?

**Comment by kwiatrox** [comment]
> Thank you. Did you test this on all OS's we support?

I had a chance to test it only on Ubuntu so far.

**Comment by sunkuranganath** [comment]
I would assume at this point we would go with CI checks. If CI passes and there are no pending review comments, I would think it can be merged.
As per our meetup discussions, exec plugin is part of "core plugins" list. So we require a release manager or core reviewers to accept this bug fix. Adding core reviewers (that I know of) to the review.
The sooner we accept this bug fix the better.

**Comment by dago** [comment]
Ok, I'll merge this one, but we need to keep in mind that strict release testing on all supported platforms is done.

**Pull request merged**
