### PR TITLE
Disk pending operation data is missing

### PR DESCRIPTION
**Pull request by bufadu**
Hello,
I noticed that disk `pending_operation` datasource is missing on some of my servers. On these servers `in_progress` value is nearly always 0. I made a quick fix to allow `in_progress` value to be dispatched when equal to zero but I don't know if is it safe to compare with `NAN`..

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
Hi!

On some 'not real' block devices (such as md raid) 'pending_operations' is _always_ equal to zero.
There is no practical use to send these zeroes as metrics and this is the reason for solution you see.  

Collectd does periodical polls, reading data from kernel. Not each of these polls will return non-zero value if you have fast hardware and small load which is not enough to fill kernel operations queue. 

After first occurence, when 'pending operations' is not zero, there is a flag set, so even zero values will be send as metric.

**Comment by bufadu** [comment]
Ok, it makes sense. But depending of the server load, after collectd starts, you may have no pending operation dispatched until the value becomes non-zero. Once the value changes, collectd dispatches the value even if it's zero. So if you use rrd with collectd you will see holes in your graphs if collectd restarts.. 
More over, as you stated, some block devices have always pending operation equal to zero; but the value is actually provided by the kernel so why ignore it ?

That's my 2 cents. Up to you to choose which data collection strategy collectd should have. But IMHO, a monitoring system should be as agnostic as possible.

**Comment by rpv-tomsk** [comment]
>But depending of the server load, after collectd starts, you may have no pending operation dispatched until the value becomes non-zero. 
...until the value becomes non-zero and Collectd _catch_ this value. This value go back to zero when no pending operations in queue.

>but the value is actually provided by the kernel so why ignore it?

Because it is not the actual value. It just placeholder in output format and _always_ is zero.

>But IMHO, a monitoring system should be as agnostic as possible.
Why we need to send unuseful (empty) metrics?

>So if you use rrd with collectd you will see holes in your graphs if collectd restarts.

On mine systems collectd restarts are rare.
If that metric has real data, then collectd catch non-zero values quickly and hole will be small.
If that metric has no real data then hole size is not critical.

Sometimes we need in compromises.

**Comment by bufadu** [comment]
Ok. I close the pull request.
Thanks for your time !

**Pull request closed without merging**
