### PR TITLE
FreeBSD disk plugin

### PR DESCRIPTION
**Pull request by rubenk**
I took the liberty to rebase what @delphij wrote on master and made the changes @octo suggested in #341

This could really do with some review and testing since I'm not entirely convinced I did it right ;)

### CODE REVIEW

**Comment by rubenk** [comment]
I noticed the disk plugin is still linked with libstatgrab if you have it installed. I don't immediately know how to fix that.

**Comment by brd** [comment]
This looks good. I talked to one of the devstat authors and he confirms we can access the struct directly. So can you cherry pick this change in? https://github.com/brd/collectd/commit/0fdd51138abce6c305ecb94c0b655578d9f26667

**Comment by rubenk** [comment]
Thanks a lot @brd! I just did.

**Comment by mfournier** [comment]
Many thanks for your work on this @delphij, @brd and @rubenk ! This will be part of upcoming version 5.6.

Sorry it took so long :-( Any advice on how we could make FreeBSD-related patches move forward faster would be very welcome !

**Comment by brd** [comment]
If you want to flag them with a label then I should be able to subscribe to that label?

I am pretty interested in Metrics and use collectd quite a bit and I am a FreeBSD developer.

**Comment by mfournier** [comment]
@brd great, thanks for the offer ! There's this (loosely used) label: https://github.com/collectd/collectd/labels/bsd%20only

**Comment by brd** [comment]
Sadly I can't subscribe to labels with github :(

**Comment by brd** [comment]
Incase anyone stumbles upon this... I Committed this to FreeBSD ports as 5.5.0_1 in r394253.

**Pull request merged**
