### PR TITLE
Fix coding style

### PR DESCRIPTION
**Pull request by dago**
ChangeLog: plugin df: Coding style fixes

### CODE REVIEW

**Comment by dago** [comment]
This PR fixes coding style issues introduced in #2910 
@rpv-tomsk thanks for noticing!

**Comment by kwiatrox** [comment]
Looks very good, but shouldn't it go to collectd-5.11 branch? @mrunge can you response on that?

**Comment by rpv-tomsk** [comment]
You overplayed with rules and policies.
You need managers who will point you what to do, or you will simply do what will work? Or you do not trust yourself?

**Comment by rpv-tomsk** [comment]
Ah, I forget - you have no permissions to merge your own PR....  Sorry...
Really serious change - eight parenthesis removed from code, such a critical change.

**Comment by mrunge** [comment]
> Looks very good, but shouldn't it go to collectd-5.11 branch? @mrunge can you response on that?

Should go to both.

**Comment by mrunge** [comment]
> Ah, I forget - you have no permissions to merge your own PR.... Sorry...
> Really serious change - eight parenthesis removed from code, such a critical change.

Could you please stop that behaviour. It does not help anything.

**Comment by rpv-tomsk** [comment]
I will not stop at your request. You can ignore it if you want and you can.

**Comment by rpv-tomsk** [comment]
3 hours to remove eight parenthesis. Really fast work.
Will see how much time takes to implement real code changes.

**Pull request merged**
