### PR TITLE
python pllugin: Some fixes for interactive sessions

### PR DESCRIPTION
**Pull request by trenkel**
I have no idea why the shutdown fix is in here, I though that was already merged?

### CODE REVIEW

**Comment by rubenk** [comment]
@trenkel yeah it is.

Is the only commit we need 8b6cead? If so I can fix that up and put it in 5.6

**Comment by trenkel** [comment]
Yes, that's the one. Also, that's some incredibly silly compiler warning.

**Comment by rubenk** [comment]
> Also, that's some incredibly silly compiler warning.

What is?

**Comment by trenkel** [comment]
The thing some of the tests are complaining about:
python.c:1028:7: error: ignoring return value of 'read', declared with attribute warn_unused_result [-Werror=unused-result]
Interestingly it's not complaining about the ignored return value of close, does it have a list of functions with above average important return values?

**Comment by rubenk** [comment]
Ah, that's glibc's doing. It has deemed read() more important than close() indeed ;)
It does this by adding `__attribute__((warn_unused_result))`.

**Comment by rubenk** [comment]
Ok, how does #1899 look?

I fixup a typo and casted the result of read and close to void.

**Comment by rubenk** [comment]
Should be fixed by 89be8ccf23c003d22d112de0fe5417d747fa20a4

**Pull request closed without merging**
