### PR TITLE
Copy MetaData to Riemann events in write_riemann

### LINKED ISSUE #2940: Support metadata in write_riemann
It would be awesome to support metadata in riemann.
Of course, all values would need to be converted to strings.

### PR DESCRIPTION
**Pull request by smortex**
Make it possible to capture information using filters in collectd and use this information in Riemann for deciding what to do with the event.

ChangeLog: write_riemann plugin: MetaData is copied to Riemann events

This is basically a rewrite of #1675 opened a few years ago but which has never been merged.  It relies on the current MetaData API.

Cc @faxm0dem 
Closes #1675
Closes #2940

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
@rubenk ,

Hi, 
Ruben, have you anything agains this PR? If not, I propose to do merge.

**Comment by faxm0dem** [comment]
@octo I'd love to have the rights to approve the changes here, can we help @rpv-tomsk a little?

**Comment by faxm0dem** [comment]
I just successfully tested this over 5.8.1 with the following config:

```XML
LoadPlugin match_regex
LoadPlugin target_set
<Chain "PreCache">
        <Rule "cpu">
               <Match "regex">
                Plugin "^cpu$"

               </Match>
               <Target "set">
                 MetaData "processor" "Westmere E56xx/L56xx/X56xx (Nehalem-C)"
               </Target>
        </Rule>
</Chain>
```

**Comment by rpv-tomsk** [comment]
Thanks for your work on Collectd!

**Pull request merged**
