### PR TITLE
Python plugin: use `PyConfig` to set argv.

### PR DESCRIPTION
**Pull request by octo**
`PySys_SetArgv` has been deprecated in Python 3.11.

ChangeLog: Python plugin: The initialization logic has been updated to work with Python ≥3.11.

### CODE REVIEW

**Review by mrunge — APPROVED** [review]
thank you, looks good.

**Comment by octo** [comment]
Debian 12 ("Bookworm") is happy now \o/

**Review by mrunge — APPROVED** [review]
now looks even better

**Comment by octo** [comment]
Thanks Matthias!

**Pull request merged**
