### PR TITLE
write_http: in cleanup handler free http headers

### PR DESCRIPTION
**Pull request by skinowski**
slist of http headers require cleanup. See libcurl
example:

https://curl.haxx.se/libcurl/c/httpcustomheader.html

### CODE REVIEW

**Comment by skinowski** [comment]
xmms error? This sounds like a bogus failure.

**Comment by rubenk** [comment]
@skinowski yes, this is bogus. The EPEL7 builders needs to be rebuild.

**Comment by rubenk** [comment]
Thanks for the patch. Storing the headers in cb->headers seems unrelated to what your commit message says this PR does. What is the advantage of this? That might need a separate commit.

**Comment by rpv-tomsk** [comment]
>What is the advantage of this?

There is no other correct way to pass 'headers' value to  wh_callback_free() -> curl_slist_free_all();.

IMHO: I think this should be marked as a 'Bug' and applied to all supported branches.

**Comment by rubenk** [comment]
@rpv-tomsk I missed that. Github making function definitions light gray in a diff isn't helping.

@skinowski this is indeed a bug, can you please close this PR and open a new one against the 5.4 branch?

**Comment by skinowski** [comment]
closing and opening a new one against 5.4.

**Pull request closed without merging**
