### PR TITLE
Memcached plugin: hits and misses statistics for command: delete

### PR DESCRIPTION
**Pull request by theairkit**
This patchset implements statistics about memcached command **delete**, adding hits/misses

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
Hi. 

Please describe your PR more detailed. It is unclean what it is about `memcached` and nobody unable to find it by search.

**Comment by theairkit** [comment]
@rpv-tomsk I describe more detailed, if needs to supplement somethings - I'll do

**Comment by Rpsl** [comment]
up

**Comment by octo** [comment]
Rebased and merged as 1a244261c7eed35f4af7295339865944c322605c.

**Pull request closed without merging**
