### PR TITLE
Disable ancient distributions

### PR DESCRIPTION
**Pull request by mrunge**

### CODE REVIEW

**Comment by eero-t** [comment]
"master" -> "main" change is obvious, but are you going to add newer RH distros in a separate PR?

(Remaining Fedora 36 goes soon out of support too.)

**Comment by mrunge** [comment]
I am well aware that e.g F36 will go out of life really soon. Having them enabled will require building images under https://github.com/collectd/ci-docker/pulls. Unfortunately, that doesn't pass so easy.

**Comment by eero-t** [comment]
Ok, so (at least) AMQP fix needs to get in first, before adding newer distros: https://github.com/collectd/collectd/pull/4111

**Comment by mrunge** [comment]
Obsoleted by https://github.com/collectd/collectd/pull/4162

**Pull request closed without merging**
