### PR TITLE
[ci][cirrus] Make Valgrind error on definite memory leaks only

### PR DESCRIPTION
**Pull request by elfiesmelfie**

### CODE REVIEW

**Comment by mrunge** [comment]
I thought we already removed the trusty check?

**Comment by elfiesmelfie** [comment]
> I thought we already removed the trusty check?

You have a PR open to do this in collectd-6.0: https://github.com/collectd/collectd/pull/3972.
I initially removed trusty in GHA only, and forgot about cirrus.

**Review by mrunge — APPROVED** [review]
This looks good to me, thank you!

**Comment by eero-t** [comment]
@mrunge Could you merge this?

PS. Is there somebody else who I could ask to accept / merge  PRs?

**Comment by elfiesmelfie** [comment]
@eero-t you can ask me, usually. I can merge,  but I don't do it for my own changes, or for changes that have reviews from less than 2 others.

**Review by kwiatrox — APPROVED** [review]

**Comment by mrunge** [comment]
I didn't merge this, as it is still waiting on the clang-format status.

**Comment by mrunge** [comment]
Obviously, clang-format doesn't really matter here, this is no c code change.

**Pull request merged**
