### PR TITLE
Merge 5.10 branch into 5.11

### PR DESCRIPTION
**Pull request by rubenk**

### CODE REVIEW

**Comment by rubenk** [comment]
@mrunge any idea why Travis failing on the varnish plugin?

**Comment by mrunge** [comment]
I think the CI is running on ancient Ubuntu, which does not provide the necessary varnish-devel version.
So, either use a newer Ubuntu for CI or skip varnish there. I know @kkepka already looked into that, but I don't know if there's a final outcome.

**Comment by rubenk** [comment]
Travis is running on Bionic, which is not ancient at all. Next to that the varnish plugin has been compiling for ages, so something recent must have broken this.

**Comment by rubenk** [comment]
@mrunge has the 5.11 branch ever been built in CI? I can't find any logs for at least Travis.

**Comment by mrunge** [comment]
I think this patch https://github.com/collectd/collectd/commit/afde89dc802b416c55cfae3a902c1f5ffff897b8 causes the issue. Let's revert it. That is in 5.11 and master

**Comment by rubenk** [comment]
Ok let's see what CI says, then I'll rebase this.

**Comment by mrunge** [comment]
CI liked this now :)

**Comment by rubenk** [comment]
All good, please merge :-)

**Pull request merged**
