### PR TITLE
Fix memory leak in write_riemann

### PR DESCRIPTION
**Pull request by mrunge**

### CODE REVIEW

**Comment by rubenk** [comment]
People, come on, just merge 5.9 into master. If you merge this into the 5.10 branch the branch will diverge from what's tagged into 5.10, and it's going to be more messy than it already is.

What should have happened is that we made sure all fixes in older branches were in master before making a new branch. Too late for that now. Having to open a PR for each forward merge doesn't make this easier either, while you apparently can create a branch without any review.

**Comment by mrunge** [comment]
The policy of merging fixes into stable branch, features into master becomes a bit messy from time to time, and this is an example for that.

I'd prefer to get all in master and to backport fixes then into stable branches. That way, it can not be forgotten to merge something into master or other stable branches (as we see here).
Most PRs are opened against master anyways.

**Comment by rubenk** [comment]
I agree with you, and although backporting by cherry picking is not without issues too I prefer that model. That's different from what has been done until now by @octo and @tokkee so if we'd like to change that let's write something up to propose.

**Comment by mrunge** [comment]
Yes, writing something up and to ask for comments is a good idea, I can do that. Would you think, the mailing list would be the best place for that kind of discussion, or shall we bring this up in the biweekly call?

**Comment by rpv-tomsk** [comment]
>I'd prefer to get all in master and to backport fixes then into stable branches. That way, it can not be forgotten to merge something into master or other stable branches (as we see here).

Disagreed. 
In your scheme, there is also a place to “forget” - to forget to merge something into supported stable branch. How your scheme avoids that?  In no way.

That just a rules. We have existing rules, but as always you try to "introduce something new", breaking all what was before.

>That way, it can not be forgotten

Just select which branches are supported, and do merges periodically ( from oldest supported branch to newer). This way that really can't be forgotten. Just put critical fixes into oldest supported branch. While doing merge branch2branch you can't forget nothing, just don't forget doing these merges. And your scheme requires more merges (`cricical PRS * supported branches`)  while existing requires only (`critical PRs + supported branches`).

Oh,yes. Before "code owners" that all was done much more easily, so was done more often.
Now any merges between branches are headache. they needs to be hardly reviewed and need handwritten signature with the stamp.

>Most PRs are opened against master anyways.

We don't discuss "most PRs" here, only just really critical ones.

**Comment by mrunge** [comment]
When a patch fixes an issue, we would then pick that patch to a stable branch. That works well in other (and also bigger) projects, such as OpenStack, https://docs.openstack.org/project-team-guide/stable-branches.html#proposing-fixes


This has nothing to do with you beloved "code-owners" change.

I was speaking from observation, nearly all contributions are opened against master branch, only a small number (like the one this is about) was opened for an older branch, when the next release was already out.

**Comment by rpv-tomsk** [comment]
Project has rules: https://collectd.org/development/submitting-patches.shtml
https://collectd.org/wiki/index.php/Repository#Organization

How you try to maintain the project while you not follow it's rules?

However, it's typical for you to hate existing rules and rewrite them in form how that be  more convenient for you...

**Comment by mrunge** [comment]
I am stating my observation, that these rules are somewhat unexpected for outside contributors and are different from what they are used to. With that, I am opening up the discussion for a change on that topic. I am not proposing a change for the sake of having a change, but for a change to be more predictable, compared to other projects. There are more (and prominent projects) following the same strategy as I am proposing:

1. kubernetes https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md
2. OpenStack, already mentioned https://docs.openstack.org/project-team-guide/stable-branches.html#proposing-fixes
3. https://brunoscopelliti.com/my-personal-bugfixing-workflow/

I am not blind, there are other models, like https://nvie.com/posts/a-successful-git-branching-model/ , which seems to be a bit popular as well. In the linux kernel world, you have people supervising "their" part of the tree to make sure, patches land in the appropriate branches and locations. We are not in that situation here.

I get that you are opposed to all changes coming in. Our life is full of changes, but when you stop changing and adjusting, you are dead. That is true for all of us.

**Comment by rpv-tomsk** [comment]
>I am stating my observation, that these rules are somewhat unexpected for outside contributors

These rules should not be expected by outside contributors.
New features mostly sent to master branch, so no collisions between expectations and rules.

>I get that you are opposed to all changes coming in. 

Yes, I am against all the changes that bother me.
And also, I don’t know people who got real convenience from these changes.

The changes are actually inconsistent with their arguments and have negative drawback, but you don't want to see it.

**Pull request merged**
