### PR TITLE
Fix memory leak in write_riemann

### PR DESCRIPTION
**Pull request by mrunge**

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
You should merge this into collectd-5.10 and then merge 5.10 into 5.11.

**Comment by kkepka** [comment]
@rpv-tomsk you mean for more clear tree history? that make sense +1

**Comment by rubenk** [comment]
Why would you want to merge this into 5.11? It's not that we're going to branch 5.12 of off the 5.11 branch.

**Comment by mrunge** [comment]
I'd want to merge this fix into 5.11, since it was not on master, and thus not in 5.11, i.e. 5.11 was released without this fix.

**Comment by rubenk** [comment]
Yes but since it's already relesased, what's the point?

**Comment by mrunge** [comment]
don't we do a 5.11.1 for bugfixes?

**Comment by rubenk** [comment]
That would be 5.12 then

**Comment by faxm0dem** [comment]
what's the point in keeping a bugfix number in version then ?
I think it's sad if we don't keep bugfix releases

**Comment by mrunge** [comment]
I was planning to do bugfix releases if needed.

**Pull request closed without merging**
