### PR TITLE
Add changelog to prepare 5.9.2 release

### PR DESCRIPTION
**Pull request by mrunge**

### CODE REVIEW

**Comment by mrunge** [comment]
Thank you!

**Comment by rpv-tomsk** [comment]
When will you update project website about new release exists?

**Comment by mrunge** [comment]
Unfortunately, I can't.

The website is running on a infrastructure kindly hosted by @octo . I am happy to add a note to the wiki though.

**Comment by rpv-tomsk** [comment]
Wow, you released 5.9.2 w/o #3283 where collectdctl.c (second occurence of ssnprintf issue) was fixed? 
Excellent release quality again....

**Comment by mrunge** [comment]
probably connected to https://github.com/collectd/collectd/issues/3293

**Pull request merged**
