### PR TITLE
Postgresql plugin: Add application name option

### PR DESCRIPTION
**Pull request by jakubjedelsky**
You can specify application name with AppName option for better
differentiation of your monitoring app in postgresql.

### CODE REVIEW

**Comment by mfournier** [comment]
Good idea! Do you know if this would be compatible with ancient versions of postgresql/libpq?

**Comment by mfournier** [comment]
So it appears this parameter is only supported since postgresql 9.x. When building against libpq4 (postgresql client library shipped with 8.x), collectd crashed as soon as I mentioned `AppName` in the configuration.

```
#0  0x00007ffff67b61de in connectDBStart (conn=0x670e00) at fe-connect.c:798
#1  0x00007ffff67b63f6 in PQreset (conn=0x670e00) at fe-connect.c:2039
#2  0x00007ffff69cdc3d in c_psql_check_connection (db=0x65f490) at postgresql.c:385
#3  0x00007ffff69cf10e in c_psql_read (ud=<value optimized out>) at postgresql.c:637
#4  0x000000000040f5e3 in plugin_read_thread (args=<value optimized out>) at plugin.c:525
#5  0x00007ffff773f83d in start_thread (arg=<value optimized out>) at pthread_create.c:301
#6  0x00007ffff72b0fcd in clone () from /lib64/libc.so.6
```

**Comment by mfournier** [comment]
On the other hand, it looks like libpq will set the application name to the value defined in the `PGAPPNAME` environment variable: http://www.postgresql.org/docs/9.4/static/libpq-envars.html
This would obviously be ignored by older versions of libpq.

Would this be sufficient for your use-case @jakubjedelsky ?

**Comment by jakubjedelsky** [comment]
Well, I didn't check the backward compatibility :/ Env variable is perfect solution I think. Is there any file where this variables can be placed and load? Or do we need to edit the postgresql.c source again?

**Comment by mfournier** [comment]
@jakubjedelsky, somewhere in the collectd initscript seems the right place for this.

Using the debian/ubuntu package, I was able to set the appname in postgresql by adding `export PGAPPNAME=foobar` to `/etc/default/collectd` (so without touching anything in the collectd source code).

Does this solution seem good enough to you ? Do you agree we can close this issue ?

**Pull request closed without merging**
