### PR TITLE
intel_rdt: bugfix configuration

### PR DESCRIPTION
**Pull request by maryamtahhan**
Fix the configuration to stop collectd bombing out and deal with configuration
errors gracefully. Otherwise collectd will fail at the configuration phase
with: "Error: Reading the config file failed!".

Change-Id: I7854c1cf4b99775e6e26a820a28110572e334ee5
Signed-off-by: Tahhan, Maryam <maryam.tahhan@intel.com>

### CODE REVIEW

**Comment by maryamtahhan** [comment]
Hi @rubenk @octo,
sorry to ask for this, but any chance of a quick review and merge? would like to include this in OPNFV release D and code freeze is friday, fix will need to be validated with Fuel before then...

Thanks in advance
Maryam

**Comment by maryamtahhan** [comment]
@rubenk Any update folks? anything I can do to help expedite this?

**Comment by rubenk** [comment]
@maryamtahhan would you mind reopening this against the oldest branch that contains intel_rdt? You can pick the branch on github when you open a pull request. That would save us some time cherry-picking, since we then can just forward-merge the stable branch into master.

**Comment by maryamtahhan** [comment]
ok will do

**Pull request closed without merging**
