### PR TITLE
openvpn plugin: Fix parsing empty fields

### PR DESCRIPTION
**Pull request by rpv-tomsk**
Closes: #3424

Changelog: openvpn plugin: Fix parsing empty fields 

I have some another improvements too, but I'm not interested in publishing them due to lack of fast response from "trusted maintainers" and I'm not trusted enough to merge my own changes myself.

### CODE REVIEW

**Comment by NikolayTsvetkov** [comment]
Hi Pavel, Thank you for the contribution !
I'm sure the community and all the users would be thankful profiting from the further improvements you can provide to the plugin. 
Merging your own PR has never been a good practice in any project, as code review doesn't only check the code quality, but in most cases leads to better ideas and improvements.
Looking forward seeing the new features here or in a separate PR.

Cheers !

**Comment by rpv-tomsk** [comment]
>as code review doesn't only check the code quality, 

Code review in this project does nothing: 
Examples:
#3381 - merged non-working implementation.
#1339 - (merged recently) - implementation effectively replaced by a const value
#2910 - (merged recently) - implemenation violates codestyle

... also I have another examples of review quality.

I do not believe that someone really checks the code. They simply push "approve"+"merge" buttons, and I able to do that myself, w/o third-party help.

**Comment by rpv-tomsk** [comment]
>... but in most cases leads to better ideas and improvements.

In most cases it leads to worthless waiting.

There was examples of 6+ months waiting. It takes so much time to review?
No, it simply just shows the attitude towards the developers, like the other endless problems of CI  and `clang-format` infrastructure.

**Comment by faxm0dem** [comment]
Hi Pavel, what's your rationale behind also changing the version detection?

**Comment by rpv-tomsk** [comment]
>Hi Pavel, what's your rationale behind also changing the version detection?
Versions 2 and 3 differs only by delimiter.
We need to detect delimiter to use it in parser.

**Comment by faxm0dem** [comment]
according to manpage, strsep also supports a string as separator:

       that  is  delimited  by one of the bytes in the string delim.
       This token is terminated by overwriting the delimiter

**Comment by rpv-tomsk** [comment]
This implementation not uses `strsep`.

**Comment by faxm0dem** [comment]
oh sorry, I misread.
oki doki, makes sense.
I'll test your patch ritght away, thanks

**Comment by faxm0dem** [comment]
successfully tested on Centos7

**Pull request merged**
