### PR TITLE
Protocols plugin: Add Solaris support.

### PR DESCRIPTION
**Pull request by octo**
ChangeLog: protocols plugin: Add Solaris support

Import of Cosmin Ioiart's changes.

### CODE REVIEW

**Comment by NikolayTsvetkov** [comment]
Hi @octo, After so many years is this request for Solaris support in thee protocols plugin still valid ?

**Comment by dago** [comment]
@NikolayTsvetkov I'll take a look.

**Comment by octo** [comment]
Hi @dago, can you give an update on this?

**Comment by dago** [comment]
Hi @octo  I would need to forward-port and recheck, but in general I think the PR is still useful. I see what I can do this week.

**Comment by dago** [comment]
This has been forward-ported to PR #3515

**Pull request closed without merging**
