### PR TITLE
Fix issues reporting statsd timers into rrd files

### PR DESCRIPTION
**Pull request by tmm1**
closes https://github.com/collectd/collectd/issues/1038

### CODE REVIEW

**Comment by octo** [comment]
If `vl.time` is zero, `plugin_dispatch_values()` will populate it with the current time, which is the usual way to go. Timer metrics report multiple values, so we populate `vl.time` here so the reported metrics all have the same time stamp.

If there was not a single timer event in the last interval, reporting an average latency is meaningless (what time did you spent answering those zero requests?). The same goes for min, max, percentile … That's why dispatching any metric is skipped in this case.

#1038 looks very much like an RRD issue to me.

**Comment by tmm1** [comment]
> If there was not a single timer event in the last interval, reporting an average latency is meaningless (what time did you spent answering those zero requests?). The same goes for min, max, percentile … That's why dispatching any metric is skipped in this case.

That makes sense, but as I discovered in #1038 librrd will not flush values from the PDP into the RRAs unless you report something every heartbeat interval. Reporting 0s latency when zero requests were handled makes sense to me, and replicates the behavior of other statsd implementations. However if you have a better solution to the rrd issue I'm happy to give it a shot.

**Comment by octo** [comment]
Try this, it will emit `NAN` when the timer was not updated, indicating to RRDtool that there *is* an update, but that the update is essentially "no information available".

```diff
diff --git a/src/statsd.c b/src/statsd.c
index 0885e23..3434225 100644
--- a/src/statsd.c
+++ b/src/statsd.c
@@ -753,39 +753,42 @@ static int statsd_metric_submit_unsafe (char const *name, /* {{{ */
   else if (metric->type == STATSD_TIMER)
   {
     size_t i;
+    _Bool have_events = (metric->updates_num > 0);
 
-    if (metric->updates_num == 0)
-      return (0);
-
+    /* Make sure all timer metrics share the *same* timestamp. */
     vl.time = cdtime ();
 
     ssnprintf (vl.type_instance, sizeof (vl.type_instance),
         "%s-average", name);
-    values[0].gauge = CDTIME_T_TO_DOUBLE (
-        latency_counter_get_average (metric->latency));
+    values[0].gauge = have_events
+      ? CDTIME_T_TO_DOUBLE (latency_counter_get_average (metric->latency))
+      : NAN;
     plugin_dispatch_values (&vl);
 
     if (conf_timer_lower) {
       ssnprintf (vl.type_instance, sizeof (vl.type_instance),
           "%s-lower", name);
-      values[0].gauge = CDTIME_T_TO_DOUBLE (
-          latency_counter_get_min (metric->latency));
+      values[0].gauge = have_events
+        ? CDTIME_T_TO_DOUBLE (latency_counter_get_min (metric->latency))
+        : NAN;
       plugin_dispatch_values (&vl);
     }
 
     if (conf_timer_upper) {
       ssnprintf (vl.type_instance, sizeof (vl.type_instance),
           "%s-upper", name);
-      values[0].gauge = CDTIME_T_TO_DOUBLE (
-          latency_counter_get_max (metric->latency));
+      values[0].gauge = have_events
+        ? CDTIME_T_TO_DOUBLE (latency_counter_get_max (metric->latency))
+        : NAN;
       plugin_dispatch_values (&vl);
     }
 
     if (conf_timer_sum) {
       ssnprintf (vl.type_instance, sizeof (vl.type_instance),
           "%s-sum", name);
-      values[0].gauge = CDTIME_T_TO_DOUBLE (
-          latency_counter_get_sum (metric->latency));
+      values[0].gauge = have_events
+        ? CDTIME_T_TO_DOUBLE (latency_counter_get_sum (metric->latency))
+        : NAN;
       plugin_dispatch_values (&vl);
     }
 
@@ -793,9 +796,9 @@ static int statsd_metric_submit_unsafe (char const *name, /* {{{ */
     {
       ssnprintf (vl.type_instance, sizeof (vl.type_instance),
           "%s-percentile-%.0f", name, conf_timer_percentile[i]);
-      values[0].gauge = CDTIME_T_TO_DOUBLE (
-          latency_counter_get_percentile (
-            metric->latency, conf_timer_percentile[i]));
+      values[0].gauge = have_events
+        ? CDTIME_T_TO_DOUBLE (latency_counter_get_percentile (metric->latency, conf_timer_percentile[i]))
+        : NAN;
       plugin_dispatch_values (&vl);
     }
 
```

**Comment by tmm1** [comment]
Thanks @octo. Your patch kind of works, but instead of `5, nan, nan, 5, nan, nan`, I'm ending up with `5, 5, nan, 5, 5, nan` in the rrd file:

```
bash-3.2$ while true; do date +%s; echo "timing_test:5000|ms" > /dev/udp/127.0.0.1/8125; sleep 30; done
1433137431
1433137461
1433137491
1433137521
1433137551


$ rrdtool fetch /tmp/rrd/tmm1-air.local/statsd/latency-timing_test-average.rrd AVERAGE -s end-3min
                          value

1433137410: nan
1433137420: nan
1433137430: nan
1433137440: 5.0000000000e+00
1433137450: nan
1433137460: 5.0000000000e+00
1433137470: 5.0000000000e+00
1433137480: nan
1433137490: 5.0000000000e+00
1433137500: 5.0000000000e+00
1433137510: nan
1433137520: 5.0000000000e+00
1433137530: 5.0000000000e+00
1433137540: nan
1433137550: 5.0000000000e+00
1433137560: 5.0000000000e+00
1433137570: nan
1433137580: nan
1433137590: nan

$ /tmp/collectd/sbin/collectd -C test.conf -f
[2015-06-01 14:44:05] uc_update: tmm1-air.local/statsd/latency-timing_test-average: ds[0] = nan
[2015-06-01 14:44:15] uc_update: tmm1-air.local/statsd/latency-timing_test-average: ds[0] = nan
[2015-06-01 14:44:25] uc_update: tmm1-air.local/statsd/latency-timing_test-average: ds[0] = 5.000000
[2015-06-01 14:44:35] uc_update: tmm1-air.local/statsd/latency-timing_test-average: ds[0] = nan
[2015-06-01 14:44:45] uc_update: tmm1-air.local/statsd/latency-timing_test-average: ds[0] = nan
[2015-06-01 14:44:55] uc_update: tmm1-air.local/statsd/latency-timing_test-average: ds[0] = 5.000000
[2015-06-01 14:45:05] uc_update: tmm1-air.local/statsd/latency-timing_test-average: ds[0] = nan
[2015-06-01 14:45:15] uc_update: tmm1-air.local/statsd/latency-timing_test-average: ds[0] = nan
[2015-06-01 14:45:25] uc_update: tmm1-air.local/statsd/latency-timing_test-average: ds[0] = 5.000000
[2015-06-01 14:45:35] uc_update: tmm1-air.local/statsd/latency-timing_test-average: ds[0] = nan
[2015-06-01 14:45:45] uc_update: tmm1-air.local/statsd/latency-timing_test-average: ds[0] = nan
[2015-06-01 14:45:55] uc_update: tmm1-air.local/statsd/latency-timing_test-average: ds[0] = 5.000000
[2015-06-01 14:46:05] uc_update: tmm1-air.local/statsd/latency-timing_test-average: ds[0] = nan
```

**Comment by octo** [comment]
Is this an RRD file as *collectd* would generate it by default, i.e. with `heartbeat = 20`? In that case you're getting two consecutive non-NaN datapoints because the value is "valid" for that long. See http://oss.oetiker.ch/rrdtool/doc/rrdcreate.en.html#IThe_HEARTBEAT_and_the_STEP for a more in-depth explanation.

**Comment by octo** [comment]
Hi @tmm1, I've just pushed the patch we discussed earlier. I suggest we continue our discussion of the statsd + timer + RRDtool variant in #1038, and the "normalization" of intervals that might be required for RRDtool in #1040.

Thanks and best regards,
—octo

**Pull request closed without merging**
