### PR TITLE
[intel_rdt] Added support for LLC references event

### PR DESCRIPTION
**Pull request by aleksinx**
Added llc_ref metric

### CODE REVIEW

**Review by mrunge — APPROVED** [review]
thank you, looks good to me

**Comment by mrunge** [comment]
the failures in CI are not related to this PR.

**Comment by lurkr2** [comment]
hey hey hey, fix broken builds
--- a/src/intel_rdt.c
+++ b/src/intel_rdt.c
@@ -44,10 +44,15 @@
 
 #define RDT_PLUGIN "intel_rdt"
 
+#if PQOS_VERSION >= 40400
 #define RDT_EVENTS                                                             \
   (PQOS_MON_EVENT_L3_OCCUP | PQOS_PERF_EVENT_IPC | PQOS_MON_EVENT_LMEM_BW |    \
    PQOS_MON_EVENT_TMEM_BW | PQOS_MON_EVENT_RMEM_BW | PQOS_PERF_EVENT_LLC_REF)
-
+#else
+#define RDT_EVENTS                                                             \
+  (PQOS_MON_EVENT_L3_OCCUP | PQOS_PERF_EVENT_IPC | PQOS_MON_EVENT_LMEM_BW |    \
+   PQOS_MON_EVENT_TMEM_BW | PQOS_MON_EVENT_RMEM_BW)
+#endif
 
 #define RDT_MAX_SOCKETS 8
 #define RDT_MAX_SOCKET_CORES 64

**Comment by lurkr2** [comment]
> perf_event_lcc_ref created at  `PQOS_VERSION >= 40300`
in commit
```commit 6ee8ee7fddce835e3e387a40b027c7d0f34d4462
Author: Michał Aleksiński <michalx.aleksinski@intel.com>
Date:   Thu Mar 17 19:02:46 2022 +0100
```

**Pull request merged**
