### PR TITLE
Connectivity plugin

### PR DESCRIPTION
**Pull request by abays**
Red Hat NFVPE network interface status monitoring plugin

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
Hi!

Please review a set of files of your PR. There is a new file `clean` which should not be merged, IMHO.

Also, there is two files with plugin documentation: `src/collectd-connectivity.pod` and `src/collectd.conf.pod`. I think, the first one also should not be merged. (And it's content has some typos).

Can you please say some words about this plugin, what info it provides? Only interface status (up/down)? 
I see, it has many 'meta' submitted. Can you please share your experience, how do you use that?

Thanks!

**Comment by rpv-tomsk** [comment]
Sorry for a dumb question, what is the 'NFVPE'?

**Comment by octo** [comment]
Hi @abays,

thank you very much for your PR! I think this functionality could quite easily be added to the existing *netlink plugin* which already implements dealing with netlink sockets, avoiding a big amount of overhead.

Best regards,
—octo

**Comment by abays** [comment]
Hello all!  We've created a Google doc in an attempt to explain why we created a separate plugin as opposed to trying to merge the functionality into the existing netlink plugin.  Please see the link below.  Thank you.

https://docs.google.com/document/d/1dmz6TV-Tq0zVrtC1c5-De6GbgFT2yDxMt35QuDuo7g4/edit?usp=sharing

**Comment by abays** [comment]
Cleaning and re-requesting

**Pull request closed without merging**
