### PR TITLE
swap plugin: Removed extra call to swap_submit_usage.

### PR DESCRIPTION
**Pull request by VikingExpat**
swap plugin: remove extra call to swap_submit_usage.
ChangeLog: swap plugin: remove extra call to swap_submit_usage.

### CODE REVIEW

**Comment by eero-t** [comment]
@VikingExpat Please add the required ChangeLog one-liner to PR description (see other PRs for an example).

@mrunge  `swap_submit_usage()` is already called in a loop above these lines, so removing the extra call is obvious bug fix which can be merged right after the PR description is fixed.

**Comment by VikingExpat** [comment]
@eero-t I have updated the comment in the initial pull request, I hope that will be sufficient.

**Comment by eero-t** [comment]
Thanks!

@mrunge This seems ready for merge.

(CI seems to be having new problems, unrelated to this PR.)

**Review by mrunge — APPROVED** [review]
Thank you!

**Comment by mrunge** [comment]
CI issues are not related to this PR.

**Pull request merged**
