### PR TITLE
[collectd 6] Fix some gcc warnings with more strict checks

### PR DESCRIPTION
**Pull request by eero-t**
ChangeLog: Build: Fix some gcc warnings with more strict checks

Fixes are based on "-O3 -Werror -Wall -Wextra -Wformat-security" output, and partly shared with the v5 fixes in https://github.com/collectd/collectd/pull/3917:

* Properly initialize complex struct
* Fix signed vs unsigned comparison warnings
* Correct "write_prometheus" comment and fix metric family freeing in a loop
* Remove unused functions and function arguments, and when latter cannot be removed, tell compiler that they're not used

### CODE REVIEW

**Comment by eero-t** [comment]
If you want some of the commits to be moved to another PR or dropped, just tell which ones.

PS. If somebody wants to do similar thing for rest of collectd code, I've filed https://github.com/collectd/collectd/issues/3969 for some additional issues in plugins that this does not handle.

**Comment by eero-t** [comment]
> debian_default_toolchain container:collectd/ci:trusty_amd64 Failing

@mrunge could you apply v5 fix for this CI issue also to v6 branch?

**Comment by mrunge** [comment]
> > debian_default_toolchain container:collectd/ci:trusty_amd64 Failing
> 
> @mrunge could you apply v5 fix for this CI issue also to v6 branch?

Yes, of course.

**Comment by mrunge** [comment]
Proposed the change here: https://github.com/collectd/collectd/pull/3972

**Comment by eero-t** [comment]
Rebased to latest v6 branch to get tests passing.  It might be better to merge v5 version of these fixes (https://github.com/collectd/collectd/pull/3917) first to make sure these branches do not get out of sync.

**Review by mrunge — APPROVED** [review]
thank you, looks good

**Comment by eero-t** [comment]
Used "Fix" label because some of the warnings were actually visible to users as build errors.

**Pull request merged**
