### PR TITLE
bug#3924  fix

### PR DESCRIPTION
**Pull request by Supali-Kash**
plugin stops collecting data after the deletion of port due to invalid incremental condition and if condition

### CODE REVIEW

**Comment by mrunge** [comment]
Thank you for your PR. Please reformat the code as noted in the clang-format check.

I understand the desire to add features, but can we please keep them separate from bug fixes?

**Comment by Supali-Kash** [comment]
Hi ,
thank you for the response, I have created a separate PR ( #3926 )for the bug.

**Comment by mrunge** [comment]
Thank you, I'll take a look

**Comment by Supali-Kash** [comment]
Hi Mrugne,

Could you please help here in getting some comments for these changes.

**Pull request closed without merging**
