### PR TITLE
network plugin: Optimize metadata "network:ip_address" adding

### PR DESCRIPTION
**Pull request by rpv-tomsk**
Changelog: network plugin: Optimize metadata "network:ip_address" adding
Changelog: network plugin: Optimize network_receive()
Changelog: network plugin: Add client address into error messages

There is no need in some `memcpy` and `memset` calls.

Issue: #3191

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
Closed due to lack of interested from community and trusted maintainers.

**Comment by yousong** [comment]
Me not a person good at comforting words or such things, esp. not in another tongue...  But please hang on for another little while.  I think these are good work improving the code base and really like it.

My experience with multiple projects indicate that it's very common for contributions sit there for weeks, months, some even circulating outside the known repo for years.  It's just how this distributed way of cooperation works in open source world.  But eventually we make things better and people all around the world benefit.  So please don't feel frustrated, keep the spirit up.

**Comment by rpv-tomsk** [comment]
My experience in this project shows me the opposite.

Previously, I had the opportunity to merge my own PR, and that allows me "to make things better". You can look into PR history where author is me.

Now project decided to change rules. These changes has no real profit as I see, but nobody cares.
As result, I see my work is not really required.

You can open your own PR and wait while somebody will do review after weeks, months, years, centuries and so on.  I'm not interested in a such waiting.

**Comment by mrunge** [comment]
> Closed due to lack of interested from community and trusted maintainers.

You can not expect someone to jump when you are calling out. This has been sitting here for 9 days, and we are busy otherwise.

It's also not the best strategy to both ask someone to do something for you and at the same time behaving badly with regards to the community.

**Comment by rpv-tomsk** [comment]
> we are busy otherwise.

Who - "we"?

>It's also not the best strategy to both ask someone to do something for you and at the same time 
behaving badly with regards to the community.

You saying about yourself, right?
Yes, that is not the best strategy to ask developers to do something for you and at the same time ignore their needs. You absolutely right here.

**Comment by rpv-tomsk** [comment]
>You can not expect someone to jump when you are calling out.

That was not required before your team appeared here and introduced policy changed.
I was able to merge my changes myself. 
And nobody say any words against quality of that work.

**Comment by sunkuranganath** [comment]
> Me not a person good at comforting words or such things, esp. not in another tongue... But please hang on for another little while. I think these are good work improving the code base and really like it.
> 
> My experience with multiple projects indicate that it's very common for contributions sit there for weeks, months, some even circulating outside the known repo for years. It's just how this distributed way of cooperation works in open source world. But eventually we make things better and people all around the world benefit. So please don't feel frustrated, keep the spirit up.

Well said @yousong 100% right!

**Comment by sunkuranganath** [comment]
> > You can not expect someone to jump when you are calling out.
> 
> That was not required before your team appeared here and introduced policy changes.
> I was able to merge my changes myself.
> And nobody say any words against quality of that work.

@rpv-tomsk seems like this is the main issue you are really frustrated about. I see the same comments repeat every where in every review! 
Is self-merge option the main thing that want and for lack of it now, go on ranting everywhere?

**Comment by rpv-tomsk** [comment]
You unable to do fast and qualified reviews.

Fast is required for my PR, and for other persons PR - qualified.

That is the main problem: you was unable to review this simple PR for a week.
That is unacceptable by me, so I prefer to have a option to do merges myself, yes.

**Comment by rpv-tomsk** [comment]
@sunkuranganath 

>Well said @yousong 100% right!

Nobody is right on 100%.
So go and write PR yourself. Start working on code. Start pushing PR and sit and wait then, looking what your work is not accepted.

You have no commits in this project, but you allow yourself too much.

**Pull request closed without merging**
