### PR TITLE
Restrict use of sys/systl to BSD variants in alignment with gclib deprecation on Linux

### PR DESCRIPTION
**Pull request by zebity**
Changelog: Contain use of sysctl / sysctrlbyname to BSD variants, as deprecated on Linux

With pending deprecation warning of gclib sys/sysctl.h and associated functions, refactor code that used sysctl so it constrains use to BSD variants.

As per analysis in of @kraj PR: https://github.com/collectd/collectd/pull/3234

The sysctl & sysctlbyname (declared in sys/sysctl.h) are BSD based functions, available in: FreeBSD, NetBSD and macOS. OpenBSD appears to be exception as it only has sysctl and no sysctlbyname declared.

Refactored code: cpu.c, memory.c, swap.c & uuid.

Changes have maintained existing precedence of use between sysctl / sysctrlbyname

Logic is based on:

HAVE_SYSCTL && HAVE_SYSCTLBYNAME == most BSDs or
__OpenBSD__ == OpenBSD which does not have sysctlbyname

TESTING:

Operationally tested on Linux (Ubuntu 19.10)

Build tested on FreeBSD 11.3

OUTSTANDING:

Need to look at detail of metrics collected to see if there are being returned ok

EDIT - Validated cpu, memory, swap on Linux (Ubuntu), metrics being collected and reported.

Looking to close issue: https://github.com/collectd/collectd/issues/3338
Follows up on this PR, without changing configure system: https://github.com/collectd/collectd/pull/3234

### CODE REVIEW

**Comment by zebity** [comment]
Hi @efuss given that you are working on sysctl (BSD) related code, could you possibly do review of this set of updates on NetBSD and advise if all is ok.

I have done build test on FreeBSD but not an operate test.

I will also give your code (https://github.com/collectd/collectd/pull/3334) a build test on FreeBSD.

Thanks

Zebity

**Comment by qingling128** [comment]
@efuss @mrunge @rpv-tomsk - Could someone help review this PR and hopefully merge it? We are running into the same issue. And this PR, while cherry-picked, fixed it for us. It would be nice to see it merged to upstream.

**Comment by rpv-tomsk** [comment]
Hi,
I'm not trusted contributor so unable to do merges.

Thanks for using Collectd.

**Comment by zebity** [comment]
@mrunge ,

as always thanks for folding in pull request.

I will do  further testing on FreeBSD (now that the issue with FreeBSD on KVM is resolved) just to be extra safe side.

Cheers,

Zebity

**Pull request merged**
