### PR TITLE
 lua: add missing notification callback

### PR DESCRIPTION
**Pull request by kenhys**
ChangeLog: lua: add missing notification callback

* register_notification

In this version, it support callback function something like:

```
      function notification(notif)
         print(inspect(notif))
         return 0
      end

      collectd.register_notification(notification)
```

It accepts PUTNOTIF event via plugin_dispatch_notification then you can  handle it.

### CODE REVIEW

**Comment by kenhys** [comment]
This PR is a follow up of https://github.com/collectd/collectd/pull/3779

**Comment by kenhys** [comment]
How to verify:

* use test-notification.sh via exec plugin
* /tmp/local/sbin/collectd -f -C test-notification.conf

```
$ cat test-notification.sh
#!/usr/bin/bash
SECONDS=$(LANG=C date +"%s")
echo "PUTNOTIF severity=failure time=$SECONDS host=jet plugin=lua s:foo=\"bar baz\" message=\"Dummy notification failure message\""
```

```
$ cat test-notification.conf
PluginDir   "/tmp/local/lib/collectd"

LoadPlugin exec
<Plugin exec>
  Exec "kenhys" "/legacy/collectd/test-notification.sh"
</Plugin>

<LoadPlugin lua>
  Globals true
</LoadPlugin>

<Plugin lua>
  BasePath "/legacy/collectd/"
  Script "test-notification.lua"
</Plugin>
```

```
$ cat test-notification.lua
local inspect = require("inspect")

function notification(notif)
   print(inspect(notif))
   return 0
end

collectd.register_notification(notification)
```

lua script should print a notification event something like:

```
{                                                                                                                                           
  host = "jet",                                                                                                                             
  message = "Dummy notification failure message",                                                                             
  meta = {                                                                                                                                  
    foo = "bar baz2"                                                                                                                        
  },                                                                  
  plugin = "lua",                                                                                                                           
  plugin_instance = "",                                               
  severity = "failure",                                                                                                                     
  time = 1705145184,                                                                                                                        
  type = "",                                                                                                                                
  type_instance = ""                                                  
}                                                                     
```

**Review by octo — APPROVED** [review]
LGTM, thanks @kenhys!

**Comment by eero-t** [comment]
> How to verify:

@kenhys Have you considered what would be required for turning this into a unit test for the Lua plugin?

(Florian's recent PRs have been adding unit-tests for quite a few things, but I'm not sure whether those can be used as examples for something like this.)

**Comment by kenhys** [comment]
> Have you considered what would be required for turning this into a unit test for the Lua plugin?

No. It's a out of scope this PR.

But, it is bad state that there is no test at all for Lua plugin, I've created a PR as a first step.
 (not fully covered yet, but it improve a situation a bit)

**Pull request merged**
