### PR TITLE
Remove LVM plugin

### PR DESCRIPTION
**Pull request by rubenk**
ChangeLog: Remove LVM plugin, liblvm2app has been deprecated

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
Why do you completely remove code,  instead of disable it by default?

**Comment by rubenk** [comment]
It's easier ;-)
Disabled code is broken code, this is only for master so by the time we ship this it's 2030 and every distro removed liblvm2app.

**Comment by mrunge** [comment]
I'm not opposed to remove broken code. Otherwise it'd hint, we are still "supporting" it.

**Comment by larsf** [comment]
This didn't make it into 5.10

**Pull request merged**
