### PR TITLE
[collectd 6] df: migration to v6.0

### PR DESCRIPTION
**Pull request by manuelluis**
ChangeLog: df plugin: migration to v6.0

### CODE REVIEW

**Comment by hnez** [comment]
Hi,

In the last few weeks I have tested some collectd 6 ports of plugins to check if they are still up to date with `main` (e.g. there are no new commits in `main` that are not in the port), if they work and if they throw any errors with address sanitization enabled (compiled with `-fsanitize=address`) or when looking for data races with `helgrind`.

This plugin was one of them. And it …

- [x] … is up to date with `main`.
- [x] … does not show issues when used with address sanitization.
- [x] … looks fine to `helgrind` and me with regards to data races¹.

I would thus suggest merging it into `collectd-6` and closing #3619.

Best regards
Leonard

**Comment by eero-t** [comment]
@hnez Any comments on this PR dropping "ReportByDevice" option / feature, and internal duplicate removal logic?

**Review by mrunge — APPROVED** [review]

**Comment by mrunge** [comment]
thank you very much!

**Comment by eero-t** [comment]
> @hnez Any comments on this PR dropping "ReportByDevice" option, and related duplicate removal logic?

@hnez ping?

**Comment by octo** [comment]
Fixes #3619

**Pull request merged**
