### PR TITLE
fix build with librabbitmq 0.6.0

### PR DESCRIPTION
**Pull request by remicollet**
See
* https://github.com/alanxz/rabbitmq-c/releases
* https://github.com/alanxz/rabbitmq-c/commit/9626dd5cd5f78894f1416a1afd2d624ddd4904ae

Just a trivial fix (but perhaps not the best)

### CODE REVIEW

**Comment by rubenk** [comment]
Looks good to me. This fixes building on Fedora Rawhide.

**Comment by mfournier** [comment]
Thanks a lot @remicollet !

This doesn't introduce any regression from what I can tell.

It looks like `AMQP_VERSION` was added in rabbitmq-c v0.4.0. Current this change is part of an macro which prevents it from getting built when an older version of rabbitmq-c is found. But to be on the safe side (in case the part of the code gets refactored at some point), could you please change this to read:

```#if defined(AMQP_VERSION) && AMQP_VERSION >= 0x00060000```

Thanks !

**Comment by remicollet** [comment]
done

**Comment by mfournier** [comment]
Thanks a lot @remicollet ! I also cherry-picked your patchset to the collectd-5.3 branch.

**Comment by remicollet** [comment]
@mfournier thanks.

> also cherry-picked your patchset to the collectd-5.3 branch.

Not in 5.4 ?

**Comment by mfournier** [comment]
@remicollet, yes it will eventually get merged to 5.4 too.

**Pull request merged**
