### PR TITLE
Adding IPV6 support to ip_vs plugin

### PR DESCRIPTION
**Pull request by ben-loadbalancer**
To retrieve IPV6 stats from ipvs requires the use of netlink as well as a newer ip_vs.h than what is in most systems. We check for different versions of netlink and have included a newer ip_vs header to work with netlink.
This is based on the work by Vince Busam adding IPV6 support to ipvsadm.

### CODE REVIEW

**Comment by octo** [comment]
Hi @ben-loadbalancer, thank you very much for your patch! I'm a bit skeptical about including a copy of system headers in collectd. I take it that newer distributions have the required header? If so, I'd prefer not to support old distributions over copying system header files.

**Comment by ben-loadbalancer** [comment]
Hi octo, I started out by copying what was done in IPVSADM which the original plugin is based on. Here they included ip_vs.h which I thought was compatibility issues across versions. However after looking further the included version does not match any of the system files across the versions. 
The version included has the necessary data structures required for IPV6 so unfortunately is required or needs to be split up which will require additional work to maintain. I've also approached one of the kernel dev's to look at updating the system header but if this happens it will not be for a while.

**Comment by rubenk** [comment]
@ben-loadbalancer are you planning on following up on this?

**Comment by ben-loadbalancer** [comment]
@rubenk Yes I do, Unfortunately the workload has pilled up so I hope to get back to it soon/

**Comment by rubenk** [comment]
@ben-loadbalancer, no problem, please open a new PR whenever you're ready.

**Pull request closed without merging**
