### PR TITLE
Collectd 5.9

### PR DESCRIPTION
**Pull request by mrunge**
merge back fixes in master branch to collectd-5.9 branch

### CODE REVIEW

**Comment by mrunge** [comment]
this should include the fixes from master branch in preparation of 5.9.1 release.

**Comment by rpv-tomsk** [comment]
Why #3156 not included into?
That is a bugfix, details are inside #3145.

**Comment by rpv-tomsk** [comment]
Also, I think we really need to fix #3198 -like issues before new release.

**Comment by mrunge** [comment]
Ouch, yes! That was an oversight from my side.

**Comment by mrunge** [comment]
@rpv-tomsk Pavel, did I forget anything else on your mind here?

**Comment by rpv-tomsk** [comment]
Hi,

I think you don't )

However, you can take your own look on https://github.com/collectd/collectd/milestone/13

**Comment by mrunge** [comment]
@rpv-tomsk Will do!

**Comment by mrunge** [comment]
[collectd - rebase to 5.9](https://trello.com/c/iutpv3e5/562-collectd-rebase-to-59)

**Comment by rpv-tomsk** [comment]
>Waiting on code owner review from anaudx, rjablonx, kwiatrox, and/or sunkuranganath. 
>clang-format — Please run: contrib/format.sh src/amqp.c src/utils/common/commo

Enjoy playing this game.

**Comment by mrunge** [comment]
This clang-format is really, really annoying me. It's not clear, which files are affected, and even if you ran the file through contrib/format.sh, it is still likely to fail again.

**Comment by rpv-tomsk** [comment]
Level completed, go to next level.

:-)))

**Comment by mrunge** [comment]
> Level completed, go to next level.
> 
Without having to face the final opponent?

**Pull request merged**
