### PR TITLE
Mysql plugin: remove double reported metrics

### PR DESCRIPTION
**Pull request by rubenk**
This is a rebased version of #1111

### CODE REVIEW

**Comment by octo** [comment]
LGTM

**Comment by octo** [comment]
Please check if these patches apply to *collectd-5.5* before merging into *master*.

**Comment by rubenk** [comment]
While technically this is a bugfix, if we apply this to 5.5.x it might surprise some people who don't have InnodbStats set, but expect these metrics to be there.

**Comment by octo** [comment]
Fair enough, *master* it is then.

**Pull request merged**
