### PR TITLE
Skip non-existing, but configured sockets

### PR DESCRIPTION
**Pull request by mrunge**
ChangeLog: ceph: skip non-existing ceph sockets

Otherwise collectd will continue to work, but e.g the unixsock plugin does not.

### CODE REVIEW

**Comment by octo** [comment]
Hi Matthias,

thanks for this PR. I'm a bit confused how the "unixsock plugin" relates to this change?

Best regards,
—octo

**Comment by mrunge** [comment]
In our tests, we have seen that the unixsock plugin stops working as a side-effect of the ceph plugin complaining about errors. What I did is: load the unixsock plugin, load the ceph plugin and e.g configure the csv plugin to have a write plugin. If there is no ceph socket available (but configured), then collectd will misbehave.

**Comment by octo** [comment]
Thanks Matthias!

I've tracked it down to the *ceph plugin* initializing a file descriptor to zero, then calling `close(0)` if establishing the connection fails. #3459 fixes this.

Due to this bug, the *socket(2)* call in the *unixsock plugin* returned zero. While the *unixsock plugin* was calling *accept(2)* on FD 0, the *ceph plugin* closed FD 0 again. This causes *accept(2)* to return `EBADF`.

I'd prefer to merge #3459 *instead* of this PR: using *access(2)* (very slightly) changes the behavior, because the permission check is done with the real user ID, not the effective user ID. What do you think?

Best regards,
—octo

**Comment by mrunge** [comment]
https://github.com/collectd/collectd/pull/3459 is a cleaner approach. I've merged that one. Thank you for your help!

**Pull request closed without merging**
