### PR TITLE
Merge collectd 5.10 back into master

### PR DESCRIPTION
**Pull request by mrunge**
this fixes also one mentioned issue in https://github.com/collectd/collectd/issues/3400

### CODE REVIEW

**Comment by mrunge** [comment]
Varnish fails to build.

https://travis-ci.org/github/collectd/collectd/jobs/660965154#L31893

**Comment by dago** [comment]
I think this is an artefact of #3360 and should have been fixed with https://github.com/collectd/ci-docker/pull/3

**Comment by mrunge** [comment]
Right, so shall I skip this for now? I'd say, let's drop it in CI, but I'd leave that to any reviewer to decide.

**Comment by kkepka** [comment]
just quick note without diving into details (yet) - https://github.com/collectd/ci-docker/pull/3 have only effect in cirrusci checks (as trusty base image)
here build has failed on travis check based on bionic, from logs, we can see varnish in ver 5.2.1-1

**Comment by mkobyli** [comment]
In my opinion if it possible we should update varnish to latest stable and supported version (6.0) on CI

**Comment by rpv-tomsk** [comment]
>mrunge wants to merge 29 commits into collectd:master from mrunge:master

1) Why do you open your PR from your own repo?
I think, such PR should be opened directly from collectd repo, w/o any third-party repos.

2) collectd-5.11 is already branched. By branching model, used in Collectd, you should merge collectd-10 into collectd-11 and then merge collectd-11 into master.

**Comment by mrunge** [comment]
I am following the documentation mentioned here: https://collectd.org/wiki/index.php/Submitting_patches

**Comment by rubenk** [comment]
Normally this should go via 5.11 indeed, to preserve a linear history but in practice it doesn't matter much as long as you merge 5.10 in 5.11 too.

**Comment by rpv-tomsk** [comment]
I'm happy to see how fast work on Collectd project is done now.

**Comment by mrunge** [comment]
fails due to varnish compile issues

**Comment by rubenk** [comment]
Shall we handle #3408 first and then merge 5.11 into master?

**Comment by mrunge** [comment]
Makes sense to me

**Comment by rubenk** [comment]
No need for this anymore.

**Pull request closed without merging**
