### PR TITLE
[collectd 6.0] gpu_sysman: Add more metric output variants and better control for them

### PR DESCRIPTION
**Pull request by eero-t**
ChangeLog: gpu_sysman: Add more metric output variants and better control for them

Changes:
* Add "rate" variant flag (3rd one) for MetricsOutput option, and change that option to a bitmask
* Rename MetricsOutput "raw" + "derived" flag names to "counter" + "ratio" ones matching metric names [1]
* Add "ratio" variant to all metric types where L0 API provides limit / max value for the metric (frequency, power, temperature)
* Add "rate" variant for memory BW metric type, in addition to already existing "counter" and "ratio" variants
* All metric types that submit multiple variants, check now these flags, and if metric type is enabled, but none of its output variants are enabled, warning is logged
* Tests for the new metrics + related improvements to the generic sysman plugin test code

Because this adds quite a bit of code to the plugin (231 added, 71 removed lines), main question is whether providing multiple variants for same metric is fine (e.g. for memory bandwidth: increasing counter, bytes per second value, and a ratio for how much that is from max BW)?

(Things like Prometheus can provide rate data based on counter data only, but if one is consuming metric data directly, providing rate directly from collectd would be preferred.)

[1] As there has been no release with this plugin, this API change should be fine.

### CODE REVIEW

**Review by mrunge — APPROVED** [review]

**Comment by eero-t** [comment]
Review for my dev branch (https://github.com/eero-t/collectd/pull/2) resulted in few minor things that apply to these changes too.  I'll cherry-pick them here later this week, so merging this could be post-poned until that.

**Comment by eero-t** [comment]
@mrunge I've cherry-picked the applicable 2 review commits from dev branch, and this PR can be merged now.

Would you like me to squash fix commits to the earlier changes in the PR before merge, to get nicer description generated for it?

PS. Plugin code in PR is checked both with Klocwork (static analysis) and Valgrind memcheck tool (dynamic analysis for running tests[1]).

[1] Gcov coverage stats for test run, when code is built with -O3 [2]:
* `gpu_sysman.c`: 92%
  * Some error checks and part of gpu info option output at startup are not covered
* `gpu_sysman_test.c`: 88%
  * Some error checks and tracing code for debugging testing failures are not covered by valgrinded test runs

[2] Higher optimization level increases coverage, because code has a lot of switch-cases, and gcc can turn most of the cases into lookup tables (so all case values in a switch do not need to be separately tested, for related code to be covered).

**Comment by eero-t** [comment]
> Would you like me to squash fix commits to the earlier changes in the PR before merge, to get nicer description generated for it?

@mrunge?

**Comment by mrunge** [comment]
A squash would be much easier to cherry-pick. But that's not going to happen. Thank you for the offer, I'd think this is good to go as is.

**Comment by eero-t** [comment]
> Thank you for the offer, I'd think this is good to go as is.

@mrunge Merge?

**Review by mrunge — APPROVED** [review]
Thank you, and sorry to keep you waiting. This looks good to me.

**Pull request merged**
