### PR TITLE
snmp plugin: Add support for SHA224, SHA256, SHA384 and SHA512

### PR DESCRIPTION
**Pull request by minfrin**
ChangeLog: snmp plugin: Add support for SHA224, SHA256, SHA384 and SHA512.

### CODE REVIEW

**Comment by minfrin** [comment]
> What happens when you if (strcasecmp("SHA224", buffer) == 0) and char buffer[4];? 🤔

Bad things - good catch, I've just fixed that.

> Also, does strcasecmp behave as expected with two strings, where one will potentially always match?
I'm thinking:
if (strcasecmp("SHA", buffer) == 0) {
and
if (strcasecmp("SHA224", buffer) == 0) {

strcasecmp works on whole strings rather than string prefixes, so the order doesn't matter in this case.

> Is it possible to IFDEF multiple HMACs? In which case, I propose not multiple IFDEF but chaining with ELSEIF.

Defining multiple HMACs is typical yes, you'll typically get SHA224, SHA256, SHA384 and SHA512 all at the same time.

> Does status get coerced to int? Some earlier definitions define int, but some don't. Probably safer to define.

This patch doesn't modify the behaviour of status, but can submit a separate PR for it? Good opportunity for a cleanup if you think it's needed.

**Comment by systemcrash** [comment]
> > What happens when you if (strcasecmp("SHA224", buffer) == 0) and char buffer[4];? thinking
> 
> Bad things - good catch, I've just fixed that.
> 
> > Also, does strcasecmp behave as expected with two strings, where one will potentially always match?
> > I'm thinking:
> > if (strcasecmp("SHA", buffer) == 0) {
> > and
> > if (strcasecmp("SHA224", buffer) == 0) {
> 
> strcasecmp works on whole strings rather than string prefixes, so the order doesn't matter in this case.
> 
> > Is it possible to IFDEF multiple HMACs? In which case, I propose not multiple IFDEF but chaining with ELSEIF.
> 
> Defining multiple HMACs is typical yes, you'll typically get SHA224, SHA256, SHA384 and SHA512 all at the same time.
> 
> > Does status get coerced to int? Some earlier definitions define int, but some don't. Probably safer to define.
> 
> This patch doesn't modify the behaviour of status, but can submit a separate PR for it? Good opportunity for a cleanup if you think it's needed.

I think if we can make the behaviour consistent throughout the file, that would be worth striving for. Would it be unusual to do it in this PR?

**Comment by systemcrash** [comment]
How about a (rough pseudocode) `int maxbuf = strlen( "SHA512" ) + 1;` and use that locally, instead of a global DEFINE? Then the local code is a bit more easily readable for the next programmer who comes along :smile: a strlen doesn't strike me as too big a cost. Your call.

**Comment by systemcrash** [comment]
@mrunge Looks OK to me.

**Review by mrunge — APPROVED** [review]
Thank you, looks okay to me.

**Pull request merged**
