### PR TITLE
Fix compile warning for amqp

### PR DESCRIPTION
**Pull request by mrunge**
warning "amqp.h is deprecated, use rabbitmq-c/amqp.h instead."

### CODE REVIEW

**Comment by mrunge** [comment]
The container-build for the CI issued a warning In file included from src/amqp.c:38:
/usr/include/amqp.h:7:2: error: #warning "amqp.h is deprecated, use rabbitmq-c/amqp.h instead." [-Werror=cpp]
    7 | #warning "amqp.h is deprecated, use rabbitmq-c/amqp.h instead."
      |  ^~~~~~~
In file included from src/amqp.c:39:
/usr/include/amqp_framing.h:8:2: error: #warning "amqp_framing.h is deprecated, use rabbitmq-c/framing.h instead. [-Werror=cpp]
    8 | #warning "amqp_framing.h is deprecated, use rabbitmq-c/framing.h instead.
      |  ^~~~~~~
In file included from src/amqp.c:42:
/usr/include/amqp_ssl_socket.h:9:2: error: #warning "amqp_ssl_socket.h is deprecated, use rabbitmq-c/ssl_socket.h instead. [-Werror=cpp]
    9 | #warning "amqp_ssl_socket.h is deprecated, use rabbitmq-c/ssl_socket.h instead.
      |  ^~~~~~~
In file included from src/amqp.c:43:
/usr/include/amqp_tcp_socket.h:7:2: error: #warning "amqp_tcp_socket.h is deprecated, use rabbitmq-c/tcp_socket.h instead." [-Werror=cpp]
    7 | #warning "amqp_tcp_socket.h is deprecated, use rabbitmq-c/tcp_socket.h instead."
      |  ^~~~~~~
cc1: all warnings being treated as errors

**Comment by mrunge** [comment]
Apparently, that change happened in the newest distribution releases

**Comment by eero-t** [comment]
Maybe `configure.ac` should add "rabbitmq-c" to include path instead?

(With a TODO to fix that once distros with the old path go all out of support.)

**Comment by octo** [comment]
Rebased on `main` and added a commit to check for the new header files in the configure script.

**Review by octo — APPROVED** [review]
Thanks Matthias!

**Pull request merged**
