### PR TITLE
Add slow queries statistics to mysql module

### PR DESCRIPTION
**Pull request by skob**
Add slow queries statistics to mysql module

### CODE REVIEW

**Comment by rubenk** [comment]
Thanks for your contribution!

Please use a more descriptive first line of your commit message. "Update mysql.c" doesn't tell a reader what this change does. I think it's fine if you used "Add slow queries statistics to mysql module" for example.

Secondly, did you test this change? There's no type defined in types.db for slow_queries. If you want this to work, you'll need to add a type.

**Comment by skob** [comment]
You right ...
Sorry

**Comment by rubenk** [comment]
Looks good, please rebase your single commit on master.

**Comment by skob** [comment]
ok ?

**Comment by rubenk** [comment]
Please squash them together.

**Comment by skob** [comment]
done

**Comment by rubenk** [comment]
Thank you.

**Comment by skob** [comment]
Thank you :-)

**Comment by mentalstring** [comment]
Can't seem to get this to work for me. I'm running 5.6.0 and types.db does contain mysql_slow_queries. Running SHOW STATUS does include Slow_queries and it is non 0. But, the statistic doesn't seem to be collected. Am I missing something? /cc @skob

**Pull request merged**
