### PR TITLE
lvm update: Check for the CAP_SYS_ADMIN capability.

### PR DESCRIPTION
**Pull request by octo**
Fixes: #2426

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
```
src/lvm.c:190:12: error: conflicting types for 'lvm_init'
 static int lvm_init(void) {
            ^
In file included from src/lvm.c:29:0:
/usr/include/lvm2app.h:260:7: note: previous declaration of 'lvm_init' was here
 lvm_t lvm_init(const char *system_dir);
       ^
Makefile:6048: recipe for target 'src/lvm_la-lvm.lo' failed
make[1]: *** [src/lvm_la-lvm.lo] Error 1
```

Please, don't merge PR untill it passes CI. ;-)

**Comment by rpv-tomsk** [comment]
Failed compilaton issue was fixed.

**Comment by octo** [comment]
Sorry, it failed so fast I assumed it was the clock issue again 😢

We really need to get that fixed!

**Comment by rpv-tomsk** [comment]
>We really need to get that fixed!

What is the issue cause?

**Comment by octo** [comment]
Me neither, that's the problem. I suspect a VM is missing a kernel module, causing it's (virtual) "hardware" clock to drift. When it's sever enough, the next VM will complain about a timestamp in the future, but every once in a while they're in sync enough for everything to work …

**Pull request merged**
