### PR TITLE
write_riemann plugin: reindent

### PR DESCRIPTION
**Pull request by rubenk**
The code has become a mix of tabs and spaces due to various
merges over the years. I tossed a coint and went with 4 spaces here.

The diff is easier to review if you add &w=1 to the url on github.

### CODE REVIEW

**Comment by octo** [comment]
As discussed in #1791, I'd like to suggest to go with `clang-format -style=LLVM` (the default style). It's not too different from collectd's overall style and I'd like to avoid creating our own style definition.

**Comment by rubenk** [comment]
Good idea, thanks. I'll try it on this file, let's see how it handles it :)

**Comment by rubenk** [comment]
I must say it does a pretty good job! The only thing is that it seems to reorder includes so we need to be careful with that. Then again, depending on include order is often a bug in hiding. WDYT?

**Comment by octo** [comment]
Looks good :)

It appears that clang-format orders `"includes"` before `<includes>`, which suits us. We might want to add a configuration along the lines of:

```yaml
IncludeCategories:
  - Regex:    '"collectd.h"'
  - Priority: -1
```

This will make sure that `"collectd.h"` is always included first.

**Comment by rubenk** [comment]
Ok, I'll do that. While at it, do you mind if I set IndentWidth: 4? I like it so much more than 2 <ducks> ;)

**Pull request merged**
