### PR TITLE
Cherry-picked #2717 and #2741 to collectd-5.8

### PR DESCRIPTION
**Pull request by rpv-tomsk**
This adressed to solve compilation issue on Solaris platform:

```
src/libcollectdclient/network_parse_test.c: In function 'test_parse_time':
src/libcollectdclient/network_parse_test.c:286:19: error: implicit declaration of function 'htobe64' [-Werror=implicit-function-declaration]
     uint64_t be = htobe64(cases[i].in);
```

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
Also merged change from #2741/

**Comment by rpv-tomsk** [comment]
cc @dago

**Comment by rpv-tomsk** [comment]
JFYI, @mfournier 

Hi!

Marc, `pull-requests-github_trigger-aggregation` hangs for 30+ min here.
This is not necessarily a problem, it can be released after an hour of waiting, as it was before.

**Comment by dago** [comment]
You should also merge #2761 for AIX support.

**Comment by rubenk** [comment]
Something keeps breaking:
```
ruben@rubenkerkhof: collectd (collectd-5.8 %=) > git cherry-pick -x aadf9ba1040ee6ac3347bd7627d311f6e01a0af0
[collectd-5.8 e6d43976] Fix make distcheck on Mac OS
 Date: Wed May 16 13:24:55 2018 +0200
 3 files changed, 3 insertions(+), 2 deletions(-)
 rename src/{ => libcollectdclient/collectd}/stdendian.h (100%)
ruben@rubenkerkhof: collectd (collectd-5.8 %>) > git push origin collectd-5.8
Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 812 bytes | 406.00 KiB/s, done.
Total 7 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/collectd-5.8.
remote: error: Required status check "pull-requests-github_trigger-aggregation" is expected.
To github.com:collectd/collectd.git
 ! [remote rejected]   collectd-5.8 -> collectd-5.8 (protected branch hook declined)
error: failed to push some refs to 'git@github.com:collectd/collectd.git'
```

**Pull request merged**
