### PR TITLE
Support for Varnish 6 and remove Varnish 2, 3 and 5

### PR DESCRIPTION
**Pull request by ismaelpuerto**
ChangeLog: varnish plugin: Support for Varnish 6, deprecated 2, 3 and 5.
ChangeLog: varnish plugin: Added counters for vmod-goto.

I keep Varnish 4 because Varnish Software keep support for Varnish Plus 4. Deleted Varnish 2, 3 and 5 because does't maintened: https://varnish-cache.org/releases/

### CODE REVIEW

**Comment by dago** [comment]
@ismaelpuerto There definitely a failing CI test. Would you mind having a look?

**Comment by ismaelpuerto** [comment]
Hello @dago, fail test of "trusty" because use old version of varnish, Ubuntu trusty born at 2014. Technically, trusty is a version not supported without subscription. https://wiki.ubuntu.com/Releases

**Comment by dago** [comment]
@ismaelpuerto I see, I am a bit reluctant to throw out support for old versions when there is the possibility some it is still used in the field. However, I could imagine that people using varnish on platforms will probably run newer OS versions and people with older OSes probably do so for other datacenter non-web stuff.

**Comment by mrunge** [comment]
I'd be good with dropping unsupported versions.

**Comment by dago** [comment]
@mrunge I am now merging this, but we need to take out building on "trusty" then. Can you tell me where this can be changed in the CI?

**Comment by kkepka** [comment]
if you would like to remove building on trusty at all, then quickshot would be on [L38-40 in .cirrus.yml](https://github.com/collectd/collectd/blob/master/.cirrus.yml#L40), but i can double check it on side if you want

**Comment by dago** [comment]
@kkepka We can continue to build on trusty, but then Varnish needs to be disabled. Would you be willing to adjust the configuration?

**Comment by kkepka** [comment]
ok, just `--disable-varnish` there is not enough, as it fails on `/checks/check-built-plugins.sh`, will look for right place to disable test for varnish on trusty

**Comment by dago** [comment]
@kkepka Can you please follow up on the CI issue with trusty? The broken CI makes it hard to see real build issues.

**Comment by kkepka** [comment]
yes i can, getting into it right now

**Comment by kkepka** [comment]
short backtrace of reason for https://github.com/collectd/ci-docker/pull/3:
- ci fails with missing varnish plugin on trusty
- failing script [check-built-plugins.sh](https://github.com/collectd/ci-docker/blob/trusty_amd64/checks/check-built-plugins.sh) uses `SUPPORTED_PLUGIN_LIST` env var to check if supported plugins have been built
- content of this var is set in [Dockerfile](https://github.com/collectd/ci-docker/blob/trusty_amd64/Dockerfile) during ci container image build by travis on per target branch (`trusty_amd64`) image/distro

**Comment by rubenk** [comment]
Can we revert this for now, at least until we managed to merge 5.10 and 5.11 back into master and released 5.11?

**Comment by mrunge** [comment]
@rubenk would you open a PR to revert or shall I?

**Comment by rubenk** [comment]
@mrunge please do

**Comment by mrunge** [comment]
Submitted https://github.com/collectd/collectd/pull/3412

**Comment by rubenk** [comment]
Ubuntu 18.04 still has varnish 5 and is widely used (also for Travis). Can we keep support for Varnish 5 a little longer?

**Comment by mrunge** [comment]
https://github.com/collectd/collectd/pull/3414 has all reverts minus the noop commit https://github.com/collectd/collectd/pull/3360/commits/039ccb92bca8950066531131db7133ac567e3769 from @dago

**Pull request merged**
