### PR TITLE
iptables plugin: remove dead code

### PR DESCRIPTION
**Pull request by rubenk**
ip version is either IPv4 or IPv6

CID #37962

### CODE REVIEW

**Comment by octo** [comment]
Can you please remove the

```c
if (( ip_version == IPV4 ) || ( ip_version == IPV6 ))
```

condition and out-dent the large block?

Also, it looks as if `ip_version` might be left at zero, in which case I'd argue to add something like:

```c
if (( ip_version != IPV4 ) && ( ip_version != IPV6 ))
  return -1;
```

**Comment by rubenk** [comment]
Is this what you had in mind?

**Comment by octo** [comment]
Exactly, thank you!

**Comment by octo** [comment]
Cherry-picked into *collectd-5.4* as 7462900ca1749634a7fa9325c2e71f49e13d0095

**Pull request closed without merging**
