### PR TITLE
memcached plugin: Report "listen_disabled_num" as "operations".

### PR DESCRIPTION
**Pull request by octo**
Fixes: #2386

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
As per https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L681, the source field of this metric represents a 'Number of times server has stopped accepting new connections'.  
This is not a number of operations, but a number of events. 
Unfortunately, Collectd now has no such type as `events`, so I can't propose the type to use.

**Comment by octo** [comment]
"listen [was] disabled" sounds like an operation that was performed, not an event that just happened, but I know nothing about memcached, so I might be way off here ;-)

**Comment by rpv-tomsk** [comment]
What would we do this this?
Proposals: `events_rate` (new common type to be added).

**Comment by rpv-tomsk** [comment]
[Auto]Merged. ;-)

Thanks for a work!

**Pull request merged**
