### PR TITLE
Bug#1059 : Remove any white spaces in ethstats stat names 

### PR DESCRIPTION
**Pull request by TomGudman**
Please review, I am a github rookie ;-)

### CODE REVIEW

**Comment by TomGudman** [comment]
See #1059

**Comment by rubenk** [comment]
Thanks for the PR Tom!

While I agree that we should strip leading spaces, which essentially fixes your issue, I don't think we should replace all spaces with underscores. That is a change in behaviour and might break existing setups. Otherwise it looks good.

**Comment by TomGudman** [comment]
I decided to also replace spaces with underscores because all other servers I had with "real" NICs heavily used underscores. I agree that it may break something somewhere but using spaces in filename is bad practice IMO. Also, maybe we could make this 'space-to-underscore' option subject to a boolean config flag in <Plugin ethstats> but that may complexify the code and it's above my limited C skills ;-) FWIW, the above code is running fine on 400+ hosts. 

Decision is up to you ;-) I don't mind either way since we package collectd locally so we can always include our own patches if required. 

Cheers,
Thomas

**Comment by rubenk** [comment]
Hey Thomas,

I'd rather have underscores than spaces too, but I'd rather not break backwards compatibility now.
I've merged only the first part into collectd-5.4, collectd-5.5 and master as 21602de.

Thanks for your contribution!

**Pull request closed without merging**
