### PR TITLE
New Capabilities plugin

### PR DESCRIPTION
**Pull request by kwiatrox**
ChangeLog: capabilities plugin: New plugin to read static platform data

Read decoded SMBIOS data using dmidecode and expose it through httpd.
Uses libmicrohttpd and libjansson.
It is a new approach to abandoned util #2000 which was using dmidecode to read BIOS information.

Signed-off-by: Kamil Wiatrowski <kamilx.wiatrowski@intel.com>

### CODE REVIEW

**Comment by rubenk** [comment]
How is this approach different from #2000?

**Comment by kwiatrox** [comment]
> How is this approach different from #2000?

Most important differences:
Old solution #2000: added only BIOS data to global variables, was part of core collectd.
New plugin: separate plugin (thus can be enabled or disabled), read wider range of data, format data as JSON, expose data for users using libmicrohttpd.

**Comment by paweltox** [comment]
Why did you implement exposing data to user with libmicrohttpd instead of using existing write_http plugin?

**Comment by kwiatrox** [comment]
> Why did you implement exposing data to user with libmicrohttpd instead of using existing write_http plugin?

write_http is one of the collectd write plugins that works in typical collectd data model, it sent metrics and notifications using http.
The capabilities plugin does not collect any dynamic data into metrics or notifications, but only exposes static data that does not change during operation.
It provides micro http webserver and works in pull model. The similar pull model is for example used in write_prometheus plugin.

**Comment by JoshHilliker** [comment]
This would be extremely helpful.   It would be great to get this out as soon as possible.

**Comment by dago** [comment]
This is further tracked in PR #3384

**Comment by dago** [comment]
Closing as #3384 has been merged.

**Pull request closed without merging**
