### PR TITLE
processes plugin: Do not gather processes IO and context switch data when unneeded

### PR DESCRIPTION
**Pull request by rpv-tomsk**
Processes IO and context switch values are not used when only summary is submitted.

Added new function `ps_fill_details()` as part of prepare for #836 / #1041 implementation.

### CODE REVIEW

**Comment by octo** [comment]
Hi @rpv-tomsk, thanks for the patch! I don't think the title is quite fitting, though: `ps_fill_details()` is called unconditionally – there is no change from the previous behavior as far as I can see … What did I miss?

Best regards,
—octo

**Comment by rpv-tomsk** [comment]
Hi!

The `ps_fill_details()`  called from `ps_list_add()` after `ps_list_match()` check.

Before this patch processes IO and context switch values was gathered by `ps_read_process()`.

**Comment by rpv-tomsk** [comment]
Ouch, I'm overoptimized my patch.

In current state, `ps_fill_details` does not check if it was called before for this entry.
There was flag for this check at prev stage, but I removed it right before make PR.

**Comment by rpv-tomsk** [comment]
Patch updated.

**Comment by octo** [comment]
> The `ps_fill_details()` is  called *[…]* after `ps_list_match()` check.

That makes sense, thanks for the explanation. Under which circumstances could `ps_fill_details()` be called more than once?

**Comment by rpv-tomsk** [comment]
> Under which circumstances could ps_fill_details() be called more than once?

When single `entry` / `cmdline` will match some (more than one)  `procstat_t` in `list_head_g` chain.

**Comment by octo** [comment]
Thanks @rpv-tomsk!

**Pull request merged**
