### PR TITLE
Added missing include of 'config.h' and cherry-picked #2761 for AIX support in collectd-5.8.

### PR DESCRIPTION
**Pull request by rpv-tomsk**
This adressed to solve compilation issues.

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
cc @mfournier 

>pull-requests-github_trigger-aggregation Expected — Waiting for status to be reported

Marc, it hangs again (40 min for now).

**Comment by rubenk** [comment]
@rpv-tomsk I think you'll need aadf9ba1040ee6ac3347bd7627d311f6e01a0af0 too otherwise it breaks OSX

**Comment by rpv-tomsk** [comment]
Hi, Ruben!

Ok, let's continue this game ))

**Comment by rubenk** [comment]
Great, please merge 5.8 back into master again and resolve the conflicts.

**Comment by rpv-tomsk** [comment]
Done. Maybe it's a time to plan next 5.8 minor release?

**Pull request merged**
