### PR TITLE
modbus: Add scale and shift to modbus

### PR DESCRIPTION
**Pull request by cekstam**
Adding the "Scale" and "Shift" parameters from the snmp-plugin to the modbus plugin in order to be able to correct amplified data.

### CODE REVIEW

**Comment by cekstam** [comment]
Commit 3127b45acf1af66b849cb83e02843b5efad18362 includes a run of `contrib/format.sh src/modbus.c`, but it seems to fail , and commit 8270e0d09971aecd4ea32360486f18ea578a93e2 includes a modbus.c done with clang-format version 6.0.0.

Any pointers on how to fix this?

**Comment by rpv-tomsk** [comment]
cc @rubenk
Ruben, let's review two commits related to modbus plugin?

I think they are good enough.

It may be better to merge this after #2670, to simplify conflict resolve (however, nothing complicated).

**Comment by rubenk** [comment]
Sure, go ahead.

I know nothing about modbus and can't test this so will have to trust that this works.

**Comment by rpv-tomsk** [comment]
I had polished this too when doing merge.

Thanks for your work, @cekstam !

**Pull request merged**
