### PR TITLE
utils_time.h: Use more composite literals.

### PR DESCRIPTION
**Pull request by octo**

### CODE REVIEW

**Comment by rubenk** [comment]
Nice cleanup! LGTM.

**Comment by octo** [comment]
Oh noes!

```
curl.c: In function 'cc_submit_response_time':
curl.c:644:26: internal compiler error: Segmentation fault
```

**Comment by octo** [comment]
That line seems to have a composite literal within a composite literal. Maybe these old versions of GCC didn't drink the kool-aid yet …

**Comment by octo** [comment]
Thanks for reviewing this @rubenk! I'll submit when I find out how to make *precise* happy.

**Comment by rubenk** [comment]
The funny thing is it does build on RHEL5 :) Speaking of which, we should really drop support for those old distros ;)

**Pull request merged**
