### PR TITLE
write_riemann: TLS support via riemann-c-client

### PR DESCRIPTION
**Pull request by algernon**
This series does two things:

1. Adds a `write_riemann` variant that uses [riemann-c-client][rcc]

    When [riemann-c-client][rcc] is available, collectd will use a variant of the `write_riemann` plugin that uses the library instead of recoding bits and pieces of a Riemann client. It accepts the same options as the original driver, and works in the same way too.

    If the library is not found, but `protobuf-c` is, the build system will fall back to the former variant of the plugin.

2. Adds TLS support to the plugin, when using the `write_riemann_rcc` variant.

    When compiled against `riemann-c-client`, the plugin will accept `Protocol TLS`, along with the new `TLSCAFile`, `TLSCertFile`, and `TLSKeyFile` options, and open a TLS connection towards riemann.

    The old plugin is also enhanced to handle these options and the `Protocol TLS` setting, but will raise an error when encountering these.

 [rcc]: https://github.com/algernon/riemann-c-client

With this setup, the `write_riemann` plugin will retain all features it currently has, but will gain new ones if `riemann-c-client` is available.

### CODE REVIEW

**Comment by mfournier** [comment]
Thanks a lot @algernon !

Initial reaction: I'm a bit concerned about the code duplication between write_riemann.c and write_riemann_rcc.c. Just wondering why you chose this approach vs macro conditionals on the presence/absence of riemann-c-client on the system ?

But as said on IRC, I like the idea of leveraging your library (and the additional features it offers) if it's available, and fallback to the existing code when it's not.

**Comment by algernon** [comment]
The main reason I chose this approach was because I dislike the macro conditionals approach. It makes it harder to follow the code, so I'd rather live with a bit of code duplication instead.

Mind you, I can rewrite the patchset to use macro conditionals, but that may take some time, as I ran out of C-time for today.

Or, I can keep the macro use to minimal, and conditionally include `write_riemann_pbc.c` or `write_riemann_rcc.c`, which implement different versions of some of the functions...

**Comment by faxm0dem** [comment]
I'm getting some build errors:
```
write_riemann_rcc.c: In function 'wrr_connect':
write_riemann_rcc.c:91:11: error: 'RIEMANN_CLIENT_OPTION_TLS_CA_FILE' undeclared (first use in this function)
           RIEMANN_CLIENT_OPTION_TLS_CA_FILE, host->tls_ca_file,
           ^
write_riemann_rcc.c:91:11: note: each undeclared identifier is reported only once for each function it appears in
write_riemann_rcc.c:92:11: error: 'RIEMANN_CLIENT_OPTION_TLS_CERT_FILE' undeclared (first use in this function)
           RIEMANN_CLIENT_OPTION_TLS_CERT_FILE, host->tls_cert_file,
           ^
write_riemann_rcc.c:93:11: error: 'RIEMANN_CLIENT_OPTION_TLS_KEY_FILE' undeclared (first use in this function)
           RIEMANN_CLIENT_OPTION_TLS_KEY_FILE, host->tls_key_file,
           ^
write_riemann_rcc.c:94:11: error: 'RIEMANN_CLIENT_OPTION_NONE' undeclared (first use in this function)
           RIEMANN_CLIENT_OPTION_NONE);
           ^
write_riemann_rcc.c:90:17: error: too many arguments to function 'riemann_client_create'
  host->client = riemann_client_create(host->client_type, node, port,
                 ^
In file included from /usr/local/include/riemann/riemann-client.h:27:0,
                 from write_riemann_rcc.c:37:
/usr/local/include/riemann/client.h:40:19: note: declared here
 riemann_client_t *riemann_client_create (riemann_client_type_t type,
                   ^
write_riemann_rcc.c: In function 'wrr_value_list_to_message':
write_riemann_rcc.c:446:3: error: implicit declaration of function 'riemann_message_append_events' [-Werror=implicit-function-declaration]
   riemann_message_append_events(msg, event, NULL);
   ^
write_riemann_rcc.c: In function 'wrr_batch_add_value_list':
write_riemann_rcc.c:531:3: error: implicit declaration of function 'riemann_message_append_events_n' [-Werror=implicit-function-declaration]
   status = riemann_message_append_events_n(host->batch_msg,
   ^
write_riemann_rcc.c: In function 'wrr_config_node':
write_riemann_rcc.c:724:25: error: 'RIEMANN_CLIENT_TLS' undeclared (first use in this function)
     host->client_type = RIEMANN_CLIENT_TLS;
```

**Comment by algernon** [comment]
@faxm0dem you need riemann-c-client 1.5.0+. And for TLS to work, you will also need GnuTLS 3.3.0+ (when compiling riemann-c-client).

**Comment by faxm0dem** [comment]
Okay, too bad only 2.8.5 is available in EL6.
Thanks, I'm testing this right away

**Comment by pyr** [comment]
Hi @algernon, would you be opposed to me factoring out the TLS code or do you think your library brings something more to the table which would justify the added complexity in building ?

**Comment by pyr** [comment]
(thanks btw!)

**Comment by faxm0dem** [comment]
I'll report back if I see any performance improvements with @algernon's implementation

**Comment by algernon** [comment]
The most valuable thing the external library brings, is that it is a library. Code you don't have to maintain, where you can benefit from current (TLS) and future (eg, pipelining) features. Reimplementing features of a library that is otherwise license-compatible seems rather pointless to me. Yes, you can then build on distros which don't have riemann-c-client - but if you factor out my TLS code, you'll need GnuTLS 3.3, and you're pretty much in the same situation. If you redo it with OpenSSL or an older GnuTLS (which is also on my roadmap, although with very low priority), then that's even more work.

Either way, you'll have to bring in OpenSSL or GnuTLS. If you pull in GnuTLS 3.3 by borrowing code from my library, then you're no further than using the library to begin with.

In the long run, a transition period where both variants are maintained helps riemann-c-client get into distros (because it has more than one user [syslog-ng]), which means that later on, the in-house Riemann client can be dropped, and voila, complexity gone. Thus, in the long run, you will end up with simpler code, for the price of having to maintain two variants for a bit. I don't think that's such a big price to pay.

**Comment by octo** [comment]
Hi @algernon and than you very much for your PR!

I'm with @mfournier in that I'm a bit concerned about code duplication. Also, I'd prefer if there was *one* plugin which would use the library if available and the Protobufs otherwise.

I'd suggest to split this into three files, `write_riemann.c`, `write_riemann_lib.c` and `write_riemann_pb.c`, with the first file being the "main" .c file of the plugin. In `write_riemann.c` we then include one of the other two, depending on whether the library is available, e.g.:
```c
#if HAVE_RIEMANN_C_CLIENT
# include "write_riemann_lib.c"
#else
# include "write_riemann_pb.c"
#endif
```

That way we can at least re-use the configuration handling and potentially some more scaffolding, such as the outer *flush* callback. Does that sound feasible?

Best regards,
—octo

**Comment by algernon** [comment]
Yeah, that sounds reasonable. I'll redo the patch sometime next week, as time allows.

**Comment by algernon** [comment]
FWIW, I will not have time in the foreseeable future to update the PR. I'd prefer to keep it open though, so it stays on my radar, and if someone wants to update it, I can point them here.

**Comment by pyr** [comment]
@algernon now that riemann-c-client is ubiquitous in distros, I think this makes sense. Are you willing to rebase and kill the old hand-rolled client code?

**Comment by algernon** [comment]
Yeah, sure, I can do that. It will take some time (a month or two, maybe), because I'm neck deep in other things, but if all goes well, I'll have renewed interest in getting this merged by the end of the month.

So, yep, I'll do it, but at a rather slow pace, if you don't mind.

**Comment by pyr** [comment]
No worries, such is the life of Open source :-)

**Comment by faxm0dem** [comment]
\ö/

**Comment by algernon** [comment]
Updated the PR, but it is still a work in progress. In a followup commit, I'll upgrade the dependency to `riemann-c-client` 1.8.0+, as that makes some of the code nicer, and allows us to set a timeout (for TLS handshake, and other network ops too).

**Comment by algernon** [comment]
Looks like Jenkins is failing, because `libriemann-client-dev` is not installed. Sadly, Jessie does not have a new enough version, either. If need be, I can prepare a backports upload.

**Comment by algernon** [comment]
Updated the branch again. The second commit ups the dependency to 1.6.0+. There is one more feature we may want: setting a timeout. That requires 1.8.0+. The upcoming 1.9.0 will also add a way to set TLS options (such as ciphers to use, etc).

I do not have more time today to add the 1.8.0 stuff, will do so tomorrow. 

1.9.0 will be easier to support, as 1.8.0 has version macros, and we can conditionally compile features in, if a higher version is present. Thus, the dependency may not need a bump.

**Comment by algernon** [comment]
And with the third commit, we bring it to 1.8.0+, adding support for timeouts. At the moment, I believe this is the final form of the PR.

The formatting of `write_riemann.c` appears to be a bit inconsistent though. I'll see if I can fix that easily.

**Comment by pyr** [comment]
Let's fix the formatting after the PR to avoid cluttering the PR

**Comment by pyr** [comment]
I'll review and test the PR starting today.

**Comment by pyr** [comment]
Hey there, I'm testing this in production starting today, will follow-up shortly.

**Comment by pyr** [comment]
@algernon have you tested the code? No luck in sending out events so far.

**Comment by pyr** [comment]
(I'm testing plain TCP for starters)

**Comment by pyr** [comment]
@algernon in `wrr_send`. The first error check does not release the lock before returning which if you hit it results in a dead-lock. (I can't commit on the diff itself since github doesn't want to show the full diff)

**Comment by pyr** [comment]
@algernon you also seem to have disabled the code that avoid too many repetitive logs when the riemann host cannot be contacted.

**Comment by algernon** [comment]
No, haven't tested the newest code yet (barely had time to port it). I'll see what I can do ~tomorrow. Will likely reformat the file to be consistent, that will make review a whole lot easier.

**Comment by pyr** [comment]
Following up on my comments, there seems to be a remaining problem with batching. Haven't tested TLS yet.

**Comment by pyr** [comment]
I found a new deadlock when batching, will update my branch shortly.

**Comment by algernon** [comment]
@pyr You should have access to my fork too now.

Looks like I'll be busy today, not sure I will have the opportunity to work on this PR today :(

**Comment by pyr** [comment]
@algernon awesome, I'll update it then. I'm testing the following changes and will push when finished testing:

- Removal of the old protobuf file
- Add a "BatchFlushTimeout" option to flush at regular intervals
- Remove a deadlock when flushing

**Comment by pyr** [comment]
The PR as-is works for me, I'll be watching memory consumption.
I know @faxm0dem and @mfournier were interested, you can test either this, or a backport to collectd-5.5.1 here: https://github.com/exoscale/collectd/tree/feature/tls-riemann-5.5.1

**Comment by faxm0dem** [comment]
I'm building this now on EL7 and later EL6 to test on a bunch of servers

**Comment by faxm0dem** [comment]
Won't be able to test this sorry

```
Requested 'riemann-client >= 1.8.0' but version of riemann-client is 1.6.1
```

**Comment by pyr** [comment]
Memory consumption is stable. I'd vote for merging.

**Comment by pyr** [comment]
@faxm0dem the rationale was that by the time 5.6 hits the distro you're on, so will have riemann-c-client 1.8

**Comment by faxm0dem** [comment]
I understand - if you feel safe that the UDP part will work smoothly I'm :+1: too for now

**Comment by pyr** [comment]
I'll add the doc bits today.

**Comment by rubenk** [comment]
Can we keep the write_riemann plugin working without TLS support, seeing that README documents it as optional?

EPEL6 doesn't have a riemann-c-client at all, and even Fedora Rawhide is still on 1.6 (https://apps.fedoraproject.org/packages/riemann-c-client). It might take years for all these distros to get 1.8.

**Comment by pyr** [comment]
@rubenk but do you think collectd will be bumped to 5.6.x before that?

**Comment by algernon** [comment]
I poked @czanik regarding `riemann-c-client` in Fedora, he'll be pushing an update soonish, so at least rawhide will be covered.

**Comment by rubenk** [comment]
@pyr possibly. I'd like to keep that option open if it's not too much effort.
@algernon ah great, thanks!

**Comment by pyr** [comment]
@algernon thanks a lot for your work on this PR.

**Comment by mfournier** [comment]
Thanks so much for making this happen @algernon & @pyr ! Sorry I wasn't able to give feedback in time !

A couple of comments:
 - it seems that merging this broke the jenkins builds, as none of the configured plaftorms have the required lib. Not a big issue, I'll reconfigure the jobs so new pull-requests don't get flagged as failing because of this
 - @algernon, if you're able to backport a recent riemman-c-client to jessie, it would be great ! This would allow us to build & check this plugin on at least one of the target platforms.
 - would it be possible to add the documentation bits for `BatchFlushTimeout` ? Thanks !
 
And to answer to @rubenk's concerns about keeping support for older distros, let's see how fast backporting riemann-c-client in EPEL and debian backport goes. If a lot of people complain about lacking write_riemann support for older distros, we can always re-add the old code via an big `#ifdef` -block and schedule to get rid of it for good in 5.7. What do you think ?

**Comment by pyr** [comment]
@mfournier didn't i add the doc bits already, let me check

**Comment by algernon** [comment]
FWIW, the debian backport will be in the backports repo, not in stock Jessie, but I suppose that's ok. ETA: This sunday, on the Debian side.

**Comment by mfournier** [comment]
@pyr oh sorry, of course it is !

@algernon :+1: thanks !

**Comment by rubenk** [comment]
@algernon just a friendly reminder, have you heard anything from @czanic yet? There's still no riemann-c-client 1.8 build in Fedora according to https://apps.fedoraproject.org/packages/riemann-c-client/overview/

**Comment by rubenk** [comment]
We're planning to release collectd 5.6 next month, and I still don't see riemann-c-client 1.8 in Fedora / EPEL. Should we revert this PR for 5.6, or at least make it backwards-compatible?

**Comment by blalor** [comment]
Please provide *some* kind of tls support for Riemann in collectd 5.6. 

-- 
Brian Lalor
blalor@bravo5.org

**Comment by octo** [comment]
Do I understand this correctly that this breaks the *write_riemann plugin* for everyone not having *riemann-c-client* >= 1.8?

**Comment by rubenk** [comment]
@octo that's right.

**Comment by octo** [comment]
Alright, this is probably something we should mention in 5.6's release notes, otherwise we'll be facing a number of confused users.

**Comment by mfournier** [comment]
Yes, it's a bit of a shame. I'll try to get in touch with the debian & fedora maintaners, and see if we can have the required riemann-c-client version in backports & Fedora/EPEL as soon as possible. This way, at least we could provide support for the bulk of our users which rely on binary packages.

**Comment by octo** [comment]
Debian appears to [have version 1.8](https://packages.debian.org/source/sid/riemann-c-client) in *unstable*, so we should be good there.

**Comment by czanik** [comment]
I can update it in Fedora, but EPEL is a different beast. No version updates are allowed there.

**Comment by rubenk** [comment]
@czanik as long it's a minor version update and it's backwards compatible it's fine to update it in EPEL too.

**Comment by rubenk** [comment]
@algernon is the only thing that needs 1.8 the timeout code in 113cbf06e13f7ea70e08651ab71ffcf916ccb02f? If so, it should be easy enough to make that conditional.

**Comment by algernon** [comment]
Making that optional is also an option, yes. As far as I remember, that's the only thing that needs a more recent riemann-c-client, but that's off the top of my head, and I may be wrong, it has been a while I looked at this code.

**Comment by rubenk** [comment]
@algernon thanks, seems you're right. The fix was easy enough, but I'd rather have a newer version of riemann-cl-client in the distro's.

@czanik anything blocking you from updating it in Fedora? If you need any help, let me know.

**Comment by algernon** [comment]
I uploaded a backport to jessie-backports (pending review, as far as I know), but wheezy is something I'm not able to do, because two build-dependencies appear to be missing: protobuf-c and a more recent gnutls. I'll try to play around a little to see if I can work that around easily, but if it turns out that I'd have to backport those too, I'm afraid I won't be able to do that.

**Pull request merged**
