### PR TITLE
Update the format of contrib/snmp-data.conf

### PR DESCRIPTION
**Pull request by vitkabele**
ChangeLog: Update the format of snmp-data.conf file to not issue deprecation warning on startup.

s/InstancePrefix/TypeInstancePrefix/g
s/Instance/TypeInstanceOID/g

Signed-off-by: Vit Kabele <vit@kabele.me>

### CODE REVIEW

**Comment by eero-t** [comment]
In which version the new name was added, and old one deprecated?    And are there still maintained distro versions, which would include old enough version not to supporte the new name?

**Comment by vitkabele** [comment]
Hello,
the deprecation warning (and replacement options were added in b17fa8a7c71eb9fbc67702d8f1cf8a53fb2fe8a7, related to #2636. Released on June 13, 2019 as [collectd-5.9.0 (c829100a9f7ffc2dfa2c38489bc4df4b23316930)](https://github.com/collectd/collectd/releases/tag/collectd-5.9.0).

As for the maintained distro versions. Is there a way how to determine this other than going manually through all different repos?
I only know that Debian does not include this file in the basic installation anyway.

**Comment by eero-t** [comment]
> As for the maintained distro versions. Is there a way how to determine this other than going manually through all different repos? I only know that Debian does not include this file in the basic installation anyway.

Sorry for the late reply.   There are some things from which checking the package versions is a bit more convenient:
* https://ftp.redhat.com/pub/redhat/linux/enterprise/  (RHEL6 - RHEL9 are ones currently maintained according to Wikipedia)
* https://www.debian.org/distrib/packages
* https://packages.ubuntu.com/
* https://src.fedoraproject.org/
* https://build.opensuse.org/
* https://svnweb.mageia.org/packages/
* https://packages.gentoo.org/

Oldest enterprise / LTS distro versions should have the oldest package versions, so I would check them first.

**Comment by vitkabele** [comment]
Hello,
so apparently at least Ubuntu 18.04 is still out there using collectd 5.7. I however don't think that merging it to the head would somehow affect these distros right? It is not going to be installed there and if someone wants the version of the file related to the old release, it is always possible to take it from the respective tag.
The file on HEAD should however be in-sync with the code on HEAD i think.

**Review by mrunge — APPROVED** [review]
Thank you for your patch and sorry that this took so long

**Comment by mrunge** [comment]
Any potential CI errors are not related to this patch

**Pull request merged**
