### PR TITLE
uuid plugin: remove support for HAL

### PR DESCRIPTION
**Pull request by rubenk**
HAL has been deprecated for a long time.

### CODE REVIEW

**Comment by octo** [comment]
LGTM

I think the build failure is due to #1865, not this PR. It should be fixed by 579c00afb0ad01cbd0577b4391fa320b158585b0.

**Comment by rubenk** [comment]
Thanks for fixing it. I'll wait for Jenkins to turn green before I merge this.

**Comment by octo** [comment]
Manually triggered Jenkins. Let's see …

**Comment by octo** [comment]
All green.

**Pull request merged**
