### PR TITLE
Add fallback for endianness conversion

### PR DESCRIPTION
**Pull request by dago**
There is currently a failing test and I am not sure why this happens. Does this work on Linux?

### CODE REVIEW

**Comment by dago** [comment]
The failure on Solaris Sparc looks like this, I haven't looked too deep in the message parsing, does this look familiar to you?

```
====================================================
   collectd 5.8.0.131.g45df07a+: ./test-suite.log
====================================================

# TOTAL: 15
# PASS:  14
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_libcollectd_network_parse
====================================

lcc_network_parse(raw_packet_data[0]) = 22, want 0
lcc_network_parse(raw_packet_data[1]) = 22, want 0
lcc_network_parse(raw_packet_data[2]) = 22, want 0
lcc_network_parse(raw_packet_data[3]) = 22, want 0
lcc_network_parse(raw_packet_data[4]) = 22, want 0
parse_values() = 22, want 0
Warning: using insecure memory!
sizeof(iv) = 8
lcc_network_parse(): invalid 'sz' field: sz = 3584, b->len = 1337
ok - lcc_network_parse(raw_packet_data[0])
lcc_network_parse(): invalid 'sz' field: sz = 3584, b->len = 1281
ok - lcc_network_parse(raw_packet_data[1])
lcc_network_parse(): invalid 'sz' field: sz = 3584, b->len = 1314
ok - lcc_network_parse(raw_packet_data[2])
lcc_network_parse(): invalid 'sz' field: sz = 3584, b->len = 1319
ok - lcc_network_parse(raw_packet_data[3])
lcc_network_parse(): invalid 'sz' field: sz = 3584, b->len = 1342
ok - lcc_network_parse(raw_packet_data[4])
FAIL test_libcollectd_network_parse (exit status: 255)
```

**Comment by dago** [comment]
Merged master so the only remaining changes are in endianess code.
Before merging let's clarify why the check is failing, do you have an idea?

**Comment by dago** [comment]
There was one set of conditionals not working - it needs to be `_BYTE_ORDER` instead of `__BYTE_ORDER` and now the testsuite passes also on Sparc.

**Comment by dago** [comment]
BTW, when this works feel free to enable the CI checks on Solaris also for Pull Requests in addition to the regular commit history.

**Comment by rubenk** [comment]
Thanks @dago!

**Comment by rubenk** [comment]
Unfortunately this breaks on Mac OS:

```
/Library/Developer/CommandLineTools/usr/bin/make  all-am
  CC       src/libcollectdclient/libcollectdclient_la-client.lo
  CC       src/libcollectdclient/libcollectdclient_la-network.lo
  CC       src/libcollectdclient/libcollectdclient_la-network_buffer.lo
  CC       src/libcollectdclient/libcollectdclient_la-network_parse.lo
../src/libcollectdclient/network_parse.c:124:10: error: implicit declaration of function 'bswap16' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  *out = be16toh(tmp);
         ^
../src/stdendian.h:217:20: note: expanded from macro 'be16toh'
#define be16toh(x) bswap16((x))
                   ^
1 error generated
make[1]: *** [src/libcollectdclient/libcollectdclient_la-network_parse.lo] Error 1
make: *** [all] Error 2
```

@dago any ideas?

**Comment by dago** [comment]
I fixed this in #2741, it was a define which I commented out for testing and forgot to put it back in as it is not needed on Solaris and Linux.

**Comment by rubenk** [comment]
Great, works ok now on OSX.

**Comment by rpv-tomsk** [comment]
Hi!

We have almost the same in `collectd-5.8` branch:
```
src/libcollectdclient/network_parse_test.c: In function 'test_parse_time':
src/libcollectdclient/network_parse_test.c:286:19: error: implicit declaration of function 'htobe64' [-Werror=implicit-function-declaration]
     uint64_t be = htobe64(cases[i].in);
```

How should this be resolved? Do we need to add the same into `collectd-5.8`?

**Comment by rpv-tomsk** [comment]
Created #2788 for this.

**Pull request merged**
