### PR TITLE
Nginx vhost

### PR DESCRIPTION
**Pull request by Zanop**
Add Vhost config option to allow for requesting the servers status from specific vhost. This is needed in case nginx exposes the server status only for specific vhost/s.

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
Why this change is needed ?

I'm simply use the following config without any problems in my setup:

<Plugin nginx>
URL "http://nginx-status/nginx_status?auto"
</Plugin>

This sets required "Host: nginx-status"  header to requests of status from specific vhost.
All this works without any patches.

**Comment by Zanop** [comment]
Hello, there are several scenarios:

1. For special purposes like api calls or for security reasons(you dont want status info seen by outsiders) you have named virtual host which does not actually resolve by the dns but instead you request that vhost to issue commands/check status.
2. You have multiple servers/IPs for A record for load balancing reasonds. You want to check specific server's status but if you call just by URL, say "vhost.domain.com" DNS resolver will send you to any one of those IPs. By having the Vhost option I can specify exactly which server I want to check with "http://XX.XX.XX.XX/nginx_status" and then the Vhost will determine which vhost on that server I will be checking.
3. You are replacing the server for site.domain.com with a new one which you are currently configuring. For the sake of having exactly the same server configuration on the new one you have vhost site.domain.com on it but your A record is not yet pointing to it because it is in dev/testing. You want collectd to pull data from the new server, so you have to specify its address which is different from site.domain.com which still points to the old one currently in production.

Probably can think of more uses but having this option adds a lot of flexebility which is very usefull for any devop.

regards,
Vladimir Smolensky

**Comment by rpv-tomsk** [comment]
All you need in these cases - put record into /etc/hosts.

**Comment by Zanop** [comment]
That is exactly what Im trying to avoid. Puting things in hosts afects the whole machine and Im trying to limit the chnges only to services I need. Also its an ugly hack that can lead to side effects.

**Comment by rpv-tomsk** [comment]
>That is exactly what Im trying to avoid. Puting things in hosts afects the whole machine and Im trying to limit the chnges only to services I need. 

Collecting stats - is the service too. You have to do changes it to work anyway, and putting a line into /etc/hosts is no different from other changes. Also I can say what any change affects the whole machine, not only changes of /etc/hosts file.

I see no problem about that change affects whole machine. On the contrary, putting a line into /etc/hosts you can simply do "curl http://nginx-status/nginx_status?auto" and get result.

>Also its an ugly hack that can lead to side effects.

Strange opinion. File /etc/hosts is specially intended for such changes and changing it is not a hack. 
What are the side effects of such changes? I do not know such.

**Comment by Poil** [comment]
:+1: @Zanop

**Comment by rpv-tomsk** [comment]
Note about patch contents / proposed code changes:

    - I see no reasons to declare globally 'vhost' and 'headers' both.
    - curl_slist_append() can return NULL. curl* plugins check this, your code should check this too.
    - Freeing of 'headers' variable (curl_slist_free_all() call) is missing.

**Comment by rpv-tomsk** [comment]
IMHO (I'm not member of project core team):

Project should be consistent. Nginx is not only one supported webserver, there is an 'apache' plugin exists too. The 'bind' and 'ascent' plugins also uses HTTP-requests for gathering stats. 

Currently, all them successfully works without custom 'Host' header and I see no real reasons to commit proposed patch.

curl* plugins has option 'Header', but I think such generic option would be superfluous for 'not generic' plugins.

In my view:

- If you want to add your proposed option, all plugins should be touched.
- Documentation patch should be provided too.

**Comment by Zanop** [comment]
Hi, I've added NULL check although I don't think is needed, from libbcurl docs:

> Pass a NULL to this option to reset back to no custom headers.

As for freeing headers, I don't think I can since according to libcurl docs:

> When this option is passed to curl_easy_setopt, libcurl will not copy the entire list so you must keep it around until you no longer use this handle for a transfer before you call curl_slist_free_all on the list.

I can't find  plugin_deregister callback when I can do this.

**Comment by Zanop** [comment]
As for the docs, Im not sure if I have to edit collectd.conf.pod collectd.conf.in or both?

**Comment by rpv-tomsk** [comment]
Hi!

I believe, both files should be touched. The new option should be added as commented out line to collectd.conf.in.  

> I can't find plugin_deregister callback where I can do this.

It does not exists, but you can add it yourself, right? Don't forget about curl_easy_cleanup(curl);.

**Pull request closed without merging**
