### PR TITLE
[collectd 6] src/mmc.c port to collectd 6

### PR DESCRIPTION
**Pull request by hnez**
ChangeLog: mmc plugin: Port to collectd 6

The `mmc` plugin was added to the `main` branch after the `collectd-6` branch was split off.
This PR:

  - Cherry-picks the commit that added the `mmc` plugin to the `main` branch (see #3887)
  - Cherry-picks my commits that added support for more eMMCs (#4006 and #4053)
  - Ports the plugin to collectd 6 API.

This brings the plugin to feature parity with the `main` branch.

### CODE REVIEW

**Comment by elfiesmelfie** [comment]
> @elfiesmelfie Details link does not show what fails with the v6 RH el6_x86_64 build.  Could you help?

There appear to be some errors in building the mmc plugin:

```
src/mmc.c:34:29: error: linux/mmc/ioctl.h: No such file or directory src/mmc.c: In function 'mmc_micron_cmd56': src/mmc.c:268: error: variable 'cmd' has initializer but incomplete type src/mmc.c:269: error: unknown field 'opcode' specified in initializer cc1: warnings being treated as errors src/mmc.c:269: error: excess elements in struct initializer src/mmc.c:269: error: (near initialization for 'cmd') src/mmc.c:270: error: unknown field 'arg' specified in initializer src/mmc.c:270: error: excess elements in struct initializer src/mmc.c:270: error: (near initialization for 'cmd') src/mmc.c:271: error: unknown field 'flags' specified in initializer src/mmc.c:271: error: excess elements in struct initializer src/mmc.c:271: error: (near initialization for 'cmd') src/mmc.c:272: error: unknown field 'blksz' specified in initializer src/mmc.c:272: error: excess elements in struct initializer src/mmc.c:272: error: (near initialization for 'cmd') src/mmc.c:273: error: unknown field 'blocks' specified in initializer src/mmc.c:273: error: excess elements in struct initializer src/mmc.c:273: error: (near initialization for 'cmd') src/mmc.c:268: error: storage size of 'cmd' isn't known src/mmc.c:276: error: implicit declaration of function 'mmc_ioc_cmd_set_data' src/mmc.c:278: error: 'MMC_IOC_CMD' undeclared (first use in this function) src/mmc.c:278: error: (Each undeclared identifier is reported only once src/mmc.c:278: error: for each function it appears in.) src/mmc.c:268: error: unused variable 'cmd' src/mmc.c: In function 'mmc_read_sandisk': src/mmc.c:388: error: variable 'cmd_en_report_mode' has initializer but incomplete type src/mmc.c:389: error: unknown field 'opcode' specified in initializer src/mmc.c:389: error: excess elements in struct initializer src/mmc.c:389: error: (near initialization for 'cmd_en_report_mode') src/mmc.c:390: error: unknown field 'arg' specified in initializer src/mmc.c:390: error: excess elements in struct initializer src/mmc.c:390: error: (near initialization for 'cmd_en_report_mode') src/mmc.c:391: error: unknown field 'flags' specified in initializer src/mmc.c:391: error: excess elements in struct initializer src/mmc.c:391: error: (near initialization for 'cmd_en_report_mode') src/mmc.c:388: error: storage size of 'cmd_en_report_mode' isn't known src/mmc.c:393: error: variable 'cmd_read_report' has initializer but incomplete type src/mmc.c:394: error: unknown field 'opcode' specified in initializer src/mmc.c:394: error: excess elements in struct initializer src/mmc.c:394: error: (near initialization for 'cmd_read_report') src/mmc.c:395: error: unknown field 'arg' specified in initializer src/mmc.c:395: error: excess elements in struct initializer src/mmc.c:395: error: (near initialization for 'cmd_read_report') src/mmc.c:396: error: unknown field 'flags' specified in initializer src/mmc.c:396: error: excess elements in struct initializer src/mmc.c:396: error: (near initialization for 'cmd_read_report') src/mmc.c:397: error: unknown field 'blksz' specified in initializer src/mmc.c:397: error: excess elements in struct initializer src/mmc.c:397: error: (near initialization for 'cmd_read_report') src/mmc.c:398: error: unknown field 'blocks' specified in initializer src/mmc.c:398: error: excess elements in struct initializer src/mmc.c:398: error: (near initialization for 'cmd_read_report') src/mmc.c:393: error: storage size of 'cmd_read_report' isn't known src/mmc.c:412: error: 'MMC_IOC_CMD' undeclared (first use in this function) src/mmc.c:393: error: unused variable 'cmd_read_report' src/mmc.c:388: error: unused variable 'cmd_en_report_mode' make[1]: *** [src/mmc_la-mmc.lo] Error 1
```

**Comment by eero-t** [comment]
> > @elfiesmelfie Details link does not show what fails with the v6 RH el6_x86_64 build.  Could you help?
> 
> There appear to be some errors in building the mmc plugin:
> 
> ```
> src/mmc.c:34:29: error: linux/mmc/ioctl.h: No such file or directory 
> ...
> ```
> Source: https://api.cirrus-ci.com/v1/task/4589352408317952/logs/build.log

Thanks!  I assume the missing kernel header to be causing also the other problems, as other builds went fine.   What kernel is used by the RH EL6 build?

**Comment by elfiesmelfie** [comment]
> Thanks!  I assume the missing kernel header to be causing also the other problems, as other builds went fine.   What kernel is used by the RH EL6 build?
> 

EL6 is CentOS 6. Active support ended on 2017, and security support ended in 2020. There won't be updates, so perhaps we should remove it from CI.

https://endoflife.date/centos

**Comment by hnez** [comment]
Hi,

I was a bit surprised that this PR failed the CI run, as it is just a port of a plugin already in `main` and I did not remember it failing there. As it turns out this is just a bit of fallout from `collectd-6`s divergence from `main`, as CentOS6 was already disabled in `main` by #3784.
Should I open a PR that cherry-picks that change?

**Comment by eero-t** [comment]
> As it turns out this is just a bit of fallout from collectd-6s divergence from main, as CentOS6 was already disabled in main by https://github.com/collectd/collectd/pull/3784. Should I open a PR that cherry-picks that change?

Yes, please!

**Comment by hnez** [comment]
> > As it turns out this is just a bit of fallout from collectd-6s divergence from main, as CentOS6 was already disabled in main by #3784. Should I open a PR that cherry-picks that change?
> 
> Yes, please!

Alright then. While I was at it I've also picked some other changes and created #4084. Reviews welcome.

**Review by mrunge — APPROVED** [review]

**Pull request merged**
