### PR TITLE
memory.c: add "Dirty" and "Writeback" with conf option

### PR DESCRIPTION
**Pull request by zzzyhtheonly**
"Dirty" and "Writeback" help debug IO delay issues, e.g.,  when we see io-await getting high, with the help of those two metrics it becomes easier to learn if our IOs are stuck on flushing Dirty pages. 
So it might be useful to let Collectd include those two metrics. 
 
Changelog: add "Dirty" and "Writeback" with conf option in the memory plugin

### CODE REVIEW

**Comment by eero-t** [comment]
Code looks OK.

`ReportDirty` option name seems too specific to a single Linux-specific meminfo metric though. IMHO it should be a more generic one telling user that option is about disk IO / usage related memory metrics.  Any suggestions?

**Comment by zzzyhtheonly** [comment]
> Code looks OK.
> 
> `ReportDirty` option name seems too specific to a single Linux-specific meminfo metric though. IMHO it should be a more generic one telling user that option is about disk IO / usage related memory metrics. Any suggestions?

Change to `ReportMem4IOwrite`.

**Comment by zzzyhtheonly** [comment]
By the way, do not know why `format.sh` check fails...

**Comment by eero-t** [comment]
> By the way, do not know why `format.sh` check fails...

I've seen local `clang-format` to order includes differently form the remote version used by `format.sh`.  Just run the suggested command, and commit the result.

If it is indeed due to different include ordering, see: https://github.com/collectd/collectd/pull/4177/commits/ce8a26c9ad07ecd63aff2296d46aa3e7893727db

**Comment by zzzyhtheonly** [comment]
`format.sh` is resolved by another computer re-run. Guess it caused by the alignment of`    /* #endif KERNEL_LINUX */`

But this time `freebsd` fails :(

**Comment by eero-t** [comment]
Only failing check is for `epics` plugin, nothing to do with this.  Changes are small & fine, only question is about the option name. I'm not completely sure about the new one either, but do not have a good suggestion myself.  @octo?

**Pull request closed without merging**
