### PR TITLE
Merge collectd-5.7 to collectd-5.8

### PR DESCRIPTION
**Pull request by rpv-tomsk**
I'm unable to do this in generic way, so will try this one.

```
# git push upstream collectd-collectd-5.8:refs/heads/collectd-5.8
Username for 'https://github.com':
Password for 'https://github.com':
Counting objects: 22, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.26 KiB, done.
Total 8 (delta 7), reused 0 (delta 0)
remote: Resolving deltas: 100% (7/7), completed with 7 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/collectd-5.8.
remote: error: Required status check "pull-requests-github_trigger-aggregation" is expected.
To https://github.com/collectd/collectd.git
 ! [remote rejected] collectd-collectd-5.8 -> collectd-5.8 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/collectd/collectd.git'
```

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
If anybody can comment how should I do such merges - you are welcome )

Thanks.

**Comment by rubenk** [comment]
Nope, same issue here unfortunately. @octo or @mfournier would you mind looking into this? Perhaps something changes on the Github side but imho we should be able to merge collectd branches without depending on the status of the pull request CI job.

**Comment by petarkozic** [comment]
Does anyone know when we can expect this update in repo:

https://pkg.ci.collectd.org/

Thanks !

**Comment by rpv-tomsk** [comment]
@octo , @mfournier 

Florian, Marc - can you please take care on this issue, please?

**Comment by petarkozic** [comment]
@octo 
Sorry on disturb, do you have some info when we can expect update on repo ?

**Comment by mfournier** [comment]
Hello @rpv-tomsk @rubenk !

Sorry, I missed the notifications for this issue :-(
It seems jenkins fails to finish the job which should have either set the PR status to failed or succeeded. So nothing was done wrong, just a CI glitch which prevented the defined workflow to be respected.

I opened #2776, which is a copy of these commits + a dummy one I created with `git commit --allow-empty` to force jenkins to re-run (`git commit --amend --no-edit && git push -f ...` would also do the job, but is less explicit).

Once the job passed, the green button appeared and allowed me to merge the PR.

Thanks for your patience !

**Comment by rpv-tomsk** [comment]
Thanks, Marc!

**Pull request merged**
