### PR TITLE
Enable travis builds

### PR DESCRIPTION
**Pull request by pyr**
This is not as featured as the collectd-ci infrastructure but can give a quick additional data point on commits.
What do you think @mfournier ?

### CODE REVIEW

**Comment by pyr** [comment]
@rubenk good idea

**Comment by mfournier** [comment]
Why not ? Although I think this is quite basic and simplistic compared to the stuff done with jenkins (and redundant obviously). The biggest criticism I have towards travis in this case, is that ubuntu 12.04 is the only platform available to run tests.

What is the context behind this @pyr ? Does "quick data point" imply you need a faster feedback on commits than what jenkins offers ?

**Comment by pyr** [comment]
@mfournier it's more to have feedback on my branches by default before pull-requests, really.

**Comment by mfournier** [comment]
Ok, I see! I had this use-case in mind actually, but didn't get around to implement anything in jenkins yet.

Meanwhile I noticed that travis added MacOSX support recently. As this is an annoying platform to integrate into jenkins, we might want to divert the .travis.yml for this at some point.

**Pull request merged**
