### PR TITLE
Add ovs-dpdk extended metrics

### PR DESCRIPTION
**Pull request by teknoraver**
Signed-off-by: Matteo Croce <mcroce@redhat.com>
Signed-off-by: Ryan McCabe <rmccabe@redhat.com>

### CODE REVIEW

**Comment by mrunge** [comment]
Thank you, this looks good to me.

**Comment by sunkuranganath** [comment]
Looks good. Thank you.

**Comment by teknoraver** [comment]
ping, any update on this?

Regards,
Matteo

**Comment by mrunge** [comment]
Matteo, could you please rebase your patch?

**Comment by teknoraver** [comment]
It seems that ovs_stats_plugin_read() was split into ovs_stats_submit_port() and ovs_stats_submit_interfaces().
I have to carefully select where to move each element then

**Comment by abays** [comment]
There was a commit message (```"ovs_stats bonds support with separate interface stats"```), but you are correct in that it did not provide details on the refactored ```ovs_stats_plugin_read()```.  Both ```ovs_stats_submit_interfaces()``` and ```ovs_stats_submit_port()``` take the same objects: ```bridge_list_t *bridge``` and ```port_list_t *port```.  ```ovs_stats_submit_port()``` is always called when the bridge criterion is matched, but ```ovs_stats_submit_interfaces()``` is only called if the ```InterfaceStats``` config option is ```true```.

**Comment by rpv-tomsk** [comment]
Thanks for your work !

**Pull request merged**
