### PR TITLE
sensors plugin: add support for energy and current inputs

### PR DESCRIPTION
**Pull request by dangowrt**
Add support for current and energy values to log INA209, LTC4151, ...

### CODE REVIEW

**Comment by rubenk** [comment]
Thanks for your contribution!

These symbols seem to be introduced in api version 0x402: https://github.com/groeck/lm-sensors/commit/bb840c486cf096093beb48d4060609b08a34f289. I think this might need a version check.

**Comment by clemensg** [comment]
@dangowrt Any updates on this?

**Comment by clemensg** [comment]
I created #2255

**Comment by rubenk** [comment]
Should be fixed by b2b559936dd8e1c476257021add9310c414e4df4

**Pull request closed without merging**
