### PR TITLE
Collectd 5.9

### PR DESCRIPTION
**Pull request by mrunge**
Merge back fixes to be able to release 5.9.2

### CODE REVIEW

**Comment by mrunge** [comment]
Adding unlisted change here. All is included in the changelog and I don't want to steal credit from original authors.

**Comment by rpv-tomsk** [comment]
hehe,

Dear maintainer, you should wait until codeowner permit you do your work.

You do not trusted enough to do your work yourself.

And, of course, Collectd CI does his work to "help" you on this hard way.

**Comment by mrunge** [comment]
CI fails due to 
```
../../src/openldap.c:74:5: warning: 'ldap_unbind_ext_s' is deprecated: first deprecated in macOS 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]

    ldap_unbind_ext_s(st->ld, NULL, NULL);

    ^

/usr/include/ldap.h:1956:1: note: 'ldap_unbind_ext_s' has been explicitly marked deprecated here

ldap_unbind_ext_s LDAP_P((

^

../../src/openldap.c:89:8: warning: 'ldap_initialize' is deprecated: first deprecated in macOS 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]

  rc = ldap_initialize(&st->ld, st->url);
```

**Comment by mrunge** [comment]
Thank you

**Comment by rubenk** [comment]
Can you merge the 5.9 branch back into master again?

**Comment by mrunge** [comment]
I think I can't, as I can not push any changes to protected branches.

For quite some time, fixes were created and applied to master branch first, and cherry-picked to stable branches as result. There should be no fix in 5.9.x, which is not on master as well.

**Comment by rubenk** [comment]
You should be able to send a PR?

Our normal process was to apply fixes to stable branches and merge those back into master. I did not always follow that though, but it's how we're supposed to work.

If we don't merge 5.9 back we'll miss the changelog in the master branch, the adjustments to the spec files and ./version-gen will not update it's version.

**Comment by mrunge** [comment]
Right. good point. The changelog would be lost otherwise.

Yes, I know this is a change from previous workflow in collectd. I'll send a PR asap.

**Pull request merged**
