### PR TITLE
Fix bug that leads to CPPFLAGS gets overridden with CFLAGS when libxm…

### PR DESCRIPTION
**Pull request by dago**
…ms is enabled

ChangeLog: Build system: Fix bug that leads to CPPFLAGS gets overridden with CFLAGS when libxmms is enabled
ChangeLog: Network plugin: Fix typo in message and formatting

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
What makes you to do these useless appruves? =)

**Comment by dago** [comment]
Why is this ChangeLog check still in waiting state? I added the respective line in the description right from the start this time.

**Comment by mrunge** [comment]
Unfortunately, I don't have a clue how to trigger  the checks again, other than adding new commits here.

If you want to add a useful commit, you could fix the typo in https://github.com/collectd/collectd/blob/master/src/network.c#L384

**Comment by dago** [comment]
Ok, done, let's see if this works now.

**Comment by mrunge** [comment]
Thank you again for your work.

I'll just go ahead and merge this, even when we don't know why the ChangeLog check did not report anything.

**Pull request merged**
