### PR TITLE
ipmi plugin: Add support for power supply presence.

### PR DESCRIPTION
**Pull request by octo**
Fixes: #735

### CODE REVIEW

**Comment by octo** [comment]
This PR is waiting for someone with access to a system with IPMI and a power supply to confirm that this patch actually works as discussed in #735. Only then will we merge.

**Comment by rpv-tomsk** [comment]
Add support for IPMI Chassis Intrusion sensors #2014

As stated in https://github.com/collectd/collectd/issues/735

>the OpenIPMI lib […] doesn't permit to retrieve values from this kind of sensors by ipmi_sensor_id_get_reading();

So this discrete sensor  can't be added by this way. That will not work.
Discrete sensors state must be requested by `ipmi_sensor_id_get_states()`

```
#ipmitool -v sdr

Sensor ID              : PS2 Status (0x51)
 Entity ID             : 10.2 (Power Supply)
 Sensor Type (Discrete): Power Supply (0x08)
 Sensor Reading        : 0h
 Event Message Control : Per-threshold
 States Asserted       : Power Supply
                         [Presence detected]
 Assertion Events      : Power Supply
                         [Presence detected]
 Assertions Enabled    : Power Supply
                         [Presence detected]
                         [Failure detected]
                         [Predictive failure]
                         [Power Supply AC lost]
                         [Config Error]
                         [Power Supply Inactive]
 Deassertions Enabled  : Power Supply
                         [Presence detected]
                         [Failure detected]
                         [Predictive failure]
                         [Power Supply AC lost]
                         [Config Error]
                         [Power Supply Inactive]
 OEM                   : 0
```

Also I don't like idea to put these discrete sensors on metrics.
We should send notifications instead.

**Comment by vmytnykx** [comment]
Hi @rpv-tomsk, @octo 

The System Even Log (SEL) feature should solve the problem. When discrete sensor state is changed, the sensor change event is sent to SEL (see the example of events sent to SEL (`ipmitool sel list`) during power supply (PS) lost below). 
```
62c | 12/06/2016 | 16:19:23 | Power Supply PS2 Status | Power Supply AC lost | Asserted
62d | 12/06/2016 | 16:19:24 | Power Unit Pwr Unit Redund | Fully Redundant | Deasserted
62e | 12/06/2016 | 16:19:24 | Power Unit Pwr Unit Redund | Redundancy Lost | Asserted
62f | 12/06/2016 | 16:19:24 | Power Unit Pwr Unit Redund | Non-Redundant: Sufficient from Redundant | Asserted
```
OpenIPMI API allows to subscribe to receive notification(s) if new record(s) is(are) added to the SEL. E.g.: it allows collectD IPMI plugin to send notification in case of discrete sensor change. The implementation of SEL is already implemented in #2091.

Regards,
 Volodymyr

**Comment by rubenk** [comment]
I just checked this patch on a Supermicro board. This board has only one sensor for both its power supplies however:
```
ruben@test1: collectd (ipmi %)$ sudo ipmitool sensor | grep PS
PS Status        | 0x0        | discrete   | 0x0100| na        | na        | na        | na        | na        | na
```

With this patch applied, nothing is output for the PS status:
```
ruben@test1: collectd (ipmi %)$ sudo ~/opt/sbin/collectd -C ~/opt/etc/collectd.conf -f
[2017-05-25 13:55:37] plugin_load: plugin "ipmi" successfully loaded.
[2017-05-25 13:55:37] plugin_load: plugin "network" successfully loaded.
[2017-05-25 13:55:37] plugin_load: plugin "write_log" successfully loaded.
[2017-05-25 13:55:37] Initialization complete, entering read-loop.
[2017-05-25 13:55:37] ipmi plugin: sensor_list_add: Ignore sensor Intrusion system_chassis (23.1), because I don't know how to handle its type (0x5, physical_security). If you need this sensor, please file a bug report.
[2017-05-25 13:55:37] ipmi plugin: sensor_list_add: Ignore sensor CPU2 Temp processor (3.2), because I don't know how to handle its type (0xc0, invalid). If you need this sensor, please file a bug report.
[2017-05-25 13:55:37] ipmi plugin: sensor_list_add: Ignore sensor CPU1 Temp processor (3.1), because I don't know how to handle its type (0xc0, invalid). If you need this sensor, please file a bug report.
[2017-05-25 13:55:37] ipmi plugin: sensor_list_add: Ignore sensor  management controller firmware (46.1), because I don't know how to handle its type (0xdc, invalid). If you need this sensor, please file a bug report.
[2017-05-25 13:55:37] ipmi plugin: sensor_list_add: Ignore sensor  management controller firmware (46.1), because I don't know how to handle its type (0xdc, invalid). If you need this sensor, please file a bug report.
[2017-05-25 13:55:37] ipmi plugin: sensor_list_add: Ignore sensor  management controller firmware (46.1), because I don't know how to handle its type (0xdc, invalid). If you need this sensor, please file a bug report.
[2017-05-25 13:55:37] ipmi plugin: sensor_list_add: Ignore sensor  management controller firmware (46.1), because I don't know how to handle its type (0xdc, invalid). If you need this sensor, please file a bug report.
[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.temperature-P2-DIMM3B_Temp_memory_device__32_12_ 33 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.temperature-P2-DIMM3A_Temp_memory_device__32_11_ 33 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.temperature-P2-DIMM2B_Temp_memory_device__32_10_ 38 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.temperature-P2-DIMM2A_Temp_memory_device__32_9_ 36 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.temperature-P2-DIMM1B_Temp_memory_device__32_8_ 35 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.temperature-P2-DIMM1A_Temp_memory_device__32_7_ 38 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.temperature-P1-DIMM3B_Temp_memory_device__32_6_ 36 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.temperature-P1-DIMM3A_Temp_memory_device__32_5_ 36 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.temperature-P1-DIMM2B_Temp_memory_device__32_4_ 38 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.temperature-P1-DIMM2A_Temp_memory_device__32_3_ 38 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.temperature-P1-DIMM1B_Temp_memory_device__32_2_ 35 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.temperature-P1-DIMM1A_Temp_memory_device__32_1_ 38 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.fanspeed-Fan8_fan_cooling__29_8_ 0 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.fanspeed-Fan7_fan_cooling__29_7_ 0 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.fanspeed-Fan6_fan_cooling__29_6_ 0 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.fanspeed-Fan5_fan_cooling__29_5_ 0 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.fanspeed-Fan4_fan_cooling__29_4_ 0 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.fanspeed-Fan3_fan_cooling__29_3_ 4185 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.fanspeed-Fan2_fan_cooling__29_2_ 4185 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.fanspeed-Fan1_fan_cooling__29_1_ 4185 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.voltage-VBAT_system_board__7_1_ 3.216 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.voltage-+12V_system_board__7_1_ 12.296 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.voltage-+5V_system_board__7_1_ 5.12 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.voltage-+3_3VSB_system_board__7_1_ 3.264 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.voltage-+3_3V_system_board__7_1_ 3.288 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.voltage-+1_5V_system_board__7_1_ 1.52 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.voltage-CPU2_DIMM_system_board__7_1_ 1.592 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.voltage-CPU1_DIMM_system_board__7_1_ 1.592 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.voltage-CPU2_Vcore_system_board__7_1_ 0.952 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.voltage-CPU1_Vcore_system_board__7_1_ 0.96 1495713347

[2017-05-25 13:55:47] write_log values:
test1_tilaa_nl.ipmi.temperature-System_Temp_system_board__7_1_ 27 1495713347

^C[2017-05-25 13:55:50] Exiting normally.
[2017-05-25 13:55:50] collectd: Stopping 5 read threads.
[2017-05-25 13:55:50] collectd: Stopping 5 write threads.
```

**Comment by rpv-tomsk** [comment]
That was expected  :-)

> So this discrete sensor can't be added by this way. That will not work.
> Discrete sensors state must be requested by ipmi_sensor_id_get_states()

**Comment by rpv-tomsk** [comment]
New features was added to trunk and will be released in collectd-5.8, please check if they are good for you. Feel free to (re)open tickets if needed.

**Pull request closed without merging**
