### PR TITLE
python plugin: Fix SIGINT handling.

### PR DESCRIPTION
**Pull request by trenkel**
Fixes bug #1848.

### CODE REVIEW

**Comment by rubenk** [comment]
Very nice! Can you please rebase on master? The tests fail due to a merge conflict.

**Comment by trenkel** [comment]
git says: Already up-to-date.

**Comment by rubenk** [comment]
My guess is that your local master is not up to date and you need to update it first.
Current master is at:
```
$ git rev-parse HEAD
996c5b6bdf9a22759b81d6b0ed47fea690db4c05
```

**Comment by trenkel** [comment]
I tried https://xkcd.com/1597/ and it's not working.

**Comment by rubenk** [comment]
Hehehe, I know the feeling ;)
I've fixed up the single conflict and merged it as 92498b8

**Pull request closed without merging**
