### PR TITLE
WIP: Build PIE executables by default

### PR DESCRIPTION
**Pull request by rubenk**
This can be disabled with --disable-hardening

Changelog: build hardened binaries by default

### CODE REVIEW

**Comment by mrunge** [comment]
Any comments before merging this?

**Comment by rubenk** [comment]
Well, it's not ready yet ;-)

**Comment by dago** [comment]
@rubenk Are you still interested in continuing to work on this PR and get this in a mergable state?

**Comment by rubenk** [comment]
Thanks for the reminder. I ran out time and energy to pursue this, and adding this to autotools is hard. I'd rather spend the effort on converting to something like meson, which does this almost out of the box.

**Pull request closed without merging**
