### PR TITLE
Add snprintf wrapper to avoid "Truncation Warnings" with GCC 8.2/3 compiler 

### PR DESCRIPTION
**Pull request by zebity**
ChangeLog: Add ssnprintf wrapper function to 67 *.c and _ssnprintf to 1 file, to stop GCC 8.2/3 Truncation Warnings

Added ssnprintf wrapper function to all *.c files which report with truncation warnings from GCC 8.2/3 toolset. Update tested with Ubuntu 19.04 / GCC 8.3.
Completes work started under issue: https://github.com/collectd/collectd/pull/2895
And allow clean Debian/Ubuntu build of collectd

The following files auto edited to add wrapper function:
```
collectd/src/aquaero.c
collectd/src/ascent.c
collectd/src/ceph.c
collectd/src/collectd.c
collectd/src/daemon/configfile.c
collectd/src/disk.c
collectd/src/dpdkevents.c
collectd/src/dpdkstat.c
collectd/src/gmond.c
collectd/src/intel_pmu.c
collectd/src/intel_rdt.c
collectd/src/interface.c
collectd/src/ipmi.c
collectd/src/iptables.c
collectd/src/lpar.c
collectd/src/lua.c
collectd/src/lvm.c
collectd/src/mic.c
collectd/src/modbus.c
collectd/src/mqtt.c
collectd/src/mysql.c
collectd/src/netapp.c
collectd/src/netlink.c
collectd/src/nginx.c
collectd/src/notify_desktop.c
collectd/src/notify_email.c
collectd/src/onewire.c
collectd/src/openldap.c
collectd/src/oracle.c
collectd/src/ovs_events.c
collectd/src/ovs_stats.c
collectd/src/perl.c
collectd/src/postgresql.c
collectd/src/protocols.c
collectd/src/python.c
collectd/src/redis.c
collectd/src/routeros.c
collectd/src/rrdcached.c
collectd/src/rrdtool.c
collectd/src/sigrok.c
collectd/src/smart.c
collectd/src/snmp_agent.c
collectd/src/snmp.c
collectd/src/threshold.c
collectd/src/utils/cmds/cmds_test.c
collectd/src/utils/config_cores/config_cores.c
collectd/src/utils/db_query/db_query.c
collectd/src/utils/dns/dns.c
collectd/src/utils/dpdk/dpdk.c
collectd/src/utils/format_graphite/format_graphite_test.c
collectd/src/utils/format_stackdriver/format_stackdriver.c
collectd/src/utils/gce/gce.c
collectd/src/utils/oauth/oauth.c
collectd/src/utils/ovs/ovs.c
collectd/src/utils/rrdcreate/rrdcreate.c
collectd/src/varnish.c
collectd/src/virt.c
collectd/src/write_kafka.c
collectd/src/write_prometheus.c
collectd/src/write_redis.c
collectd/src/write_riemann.c
collectd/src/write_stackdriver.c
collectd/src/zfs_arc.c
collectd/src/zone.c
```

Auto edit via sed, where file: auto-sed-03.txt is file list above:
```
find collectd -name "*.c" -exec sh -c "( grep '{}' auto-sed-03.txt && mv '{}' '{}'.sed.bak && cat '{}'.sed.bak | sed 's/ snprintf(/ ssnprintf(/g' > '{}')" \;
```

Hand edited the following 3 special case files:
```
src/collectdctl.c - added static special wrapper _ssnprintf
src/utils/common/common.c/.h - added ssnprintf wrapper function
```

Code compiled with all modules except the following:
```
    apple_sensors . . . . no
    aquaero . . . . . . . no (libaquaero5.h not found)
    gpu_nvidia  . . . . . no
    grpc  . . . . . . . . no (protoc3 not found)
    intel_pmu . . . . . . no (jevents.h not found)
    java  . . . . . . . . no (jar not found)
    lpar  . . . . . . . . no (AIX only)
    mic . . . . . . . . . no (MicAccessApi not found)
    mysql . . . . . . . . no (mysql_config failed)
    netapp  . . . . . . . no (netapp_api.h not found)
    oracle  . . . . . . . no (ORACLE_HOME is not set)
    pf  . . . . . . . . . no
    python  . . . . . . . no
    routeros  . . . . . . no (routeros_api.h not found)
    sigrok  . . . . . . . no (pkg-config could not find libsigrok)
    tape  . . . . . . . . no
    xmms  . . . . . . . . no
    zone  . . . . . . . . no
```
NOTE: lvm module compiles with error due to "deprecated warning" in /usr/include/lvm2app.h

```
#warning "liblvm2app is deprecated, use D-Bus API instead."
```
I commented out warning in system header file to get around warning.
see: https://github.com/collectd/collectd/issues/2820

### CODE REVIEW

**Comment by zebity** [comment]
clang-format check appears to have gone into space.... ;-) .
It has been in pending status for over 8 hours now.

**Comment by zebity** [comment]
Suggestions please, I have done merge with upstream to ensure commits are still current and run everything through clang-format (locally), but still getting failure...

**Comment by zebity** [comment]
kwiatrox, thanks for approval, I saw in the bug trail, that you had issue with Red Hat. Have you done a test with RHEL ? I do not have RHEL tool chain setup, so it would be useful to validate the changes againt RHEL distribution.

**Comment by blackknight36** [comment]
@zebity I have RHEL 8 VMs if you need somebody to run tests.

**Comment by mrunge** [comment]
Thank you, this looks good to me, it's working on my rhel8 env here without any seen issues so far.

**Comment by mrunge** [comment]
@zebity would you be able to resolve the conflict?

**Comment by ryan-mccabe** [comment]
I tested this on RHEL8, also, and WFM.

**Comment by rpv-tomsk** [comment]
I want to warn:

I see the message "**Code owner review required  / Waiting on code owner review from anaudx and/or rjablonx**". 

That means as a "Trusted contributor" I'm unable to merge not only my own PR, but this kind of PR too.

**Team, thanks for placing me into "UNTrusted contributors".**

**Comment by rpv-tomsk** [comment]
I see no points to continue work when rules are changing and breaking things every day.

**Comment by rpv-tomsk** [comment]
I spent some more time, trying to re-pass Collectd code through this stupid tool (clang-format).
I think that is idiocy to do changes like:

```
diff --git a/src/contextswitch.c b/src/contextswitch.c
index acf3a74..cf3d3da 100644
--- a/src/contextswitch.c
+++ b/src/contextswitch.c
@@ -73,7 +73,7 @@ static int cs_read(void) {
   }

   cs_submit(value);
-/* #endif HAVE_SYSCTLBYNAME */
+  /* #endif HAVE_SYSCTLBYNAME */

 #elif KERNEL_LINUX
   FILE *fh;
@@ -116,7 +116,7 @@ static int cs_read(void) {

   if (status == -2)
     ERROR("contextswitch plugin: Unable to find context switch value.");
-/* #endif  KERNEL_LINUX */
+    /* #endif  KERNEL_LINUX */

 #elif HAVE_PERFSTAT
   int status = 0;
```
or 
```
diff --git a/src/cpusleep.c b/src/cpusleep.c
index b5cbe66..ee26b0b 100644
--- a/src/cpusleep.c
+++ b/src/cpusleep.c
@@ -28,7 +28,7 @@
  * CPU sleep is reported in milliseconds of sleep per second of wall
  * time. For that, the time difference between BOOT and MONOTONIC clocks
  * is reported using derive type.
-**/
+ **/

 #include "collectd.h"

```

I think, we need to fix clang-format rules, not change Collectd code.

**Comment by zebity** [comment]
Hi Collectd'ers,

very pleased to see that this branch request is getting some headway, as I would really like see these updates flowing through into Debian branch.

To @rpv-toms 's comment about: "Want to notice, not all occurences of snprintf are replaced." the reason for this is that as I went through code I found that I got better results (ie less compile error and flow through impact) by winding out changes in all the case that are not covered by by set of changes.

I did not see any point in touching the code if it was not generating the error in the fist case, ie if if it ain't broken then don't "fix" it ;-).

I also come up with some surprise clang-format changes and run all the code through clang-format to get it through the build process.

Let me know if there is anything I can do to help, I have already done a couple of upstream merges since first hitting the GCC 8.2/3 compiler issues, so can have another go if needed ;-)

**Comment by zebity** [comment]
Hi collectd'ers,

In doing my updates I created some little helper tools/list to manage getting on the underlying Ubuntu / Debian packages installed to allow me to complete large coverage build. I have documented this process in my [blog](https://tips.graphica.com.au/tool-and-tips-on-building-collectd/). I think it would be helpful to have area within repository for these (/contrib/helpers or something like that). People could then add platform specific build helpers (RHEL, FreeBSD, Solaris) that are not part main code base but useful non the less.

**Comment by zebity** [comment]
Hi @rpv-tomsk & @mrunge , I have tried to resolve clang-format problem, but suspect have hit same problem as others.

I have got tree with no conflicts and did:
> git fetch
> git merge upstream/master
> git status (nothing to do)
> run everything updated through contrib/format.sh
> git add . --dry-run <<== reports nothing

Yet still getting build clang-format failure..

Seems we are stuck at the moment.

**Comment by mrunge** [comment]
Thank you for your continued work on this. I've quickly checked out your master branch and ran `clang-format -style=file -i src/*.c`.
That resulted in a ton of changed files then, it still fails, see https://github.com/collectd/collectd/pull/3212

TBH, I am not sure if that'd fix the issues here, but I totally agree with you all, this issue is quite annoying, especially, since there is no verbose output what is (considered to be) wrong.

**Comment by zebity** [comment]
hi @rpv-tomsk & @mrunge , 

I think I have go to bottom of clang-format problem..
I just setup up new clone repository, added remote upstream, did fetch and merge then a git add...
Here are the results:

`$ mkdir alt-build
cd alt-build
$ git clone https://github.com/zebity/collectd.git
$ git remote add upstream https://github.com/collectd/collectd.git
$ git fetch upstream
$ git merge upstream/master
$ find . -name "*.h" -exec sh -c "( contrib/format.sh '{}')" \;
$ find . -name "*.c" -exec sh -c "( contrib/format.sh '{}')" \;
$ git add . --dry-run
add 'src/apache.c'
add 'src/battery.c'
add 'src/bind.c'
add 'src/chrony.c'
add 'src/collectdctl.c'
add 'src/collectdmon.c'
add 'src/contextswitch.c'
add 'src/cpu.c'
add 'src/cpusleep.c'
add 'src/cpython.h'
add 'src/curl.c'
add 'src/curl_json.c'
add 'src/curl_xml.c'
add 'src/daemon/cmd.c'
add 'src/daemon/collectd.c'
add 'src/daemon/plugin.c'
add 'src/daemon/utils_cache.c'
add 'src/dns.c'
add 'src/email.c'
add 'src/exec.c'
add 'src/gpu_nvidia.c'
add 'src/intel_rdt_test.c'
add 'src/ipc.c'
add 'src/ipvs.c'
add 'src/java.c'
add 'src/libcollectdclient/client.c'
add 'src/libcollectdclient/network_parse.c'
add 'src/libcollectdclient/network_parse_test.c'
add 'src/liboconfig/aux_types.h'
add 'src/madwifi.c'
add 'src/madwifi.h'
add 'src/match_empty_counter.c'
add 'src/mcelog.c'
add 'src/memcached.c'
add 'src/memory.c'
add 'src/network.c'
add 'src/nfs.c'
add 'src/nut.c'
add 'src/pcie_errors.c'
add 'src/processes.c'
add 'src/sensors.c'
add 'src/serial.c'
add 'src/statsd.c'
add 'src/swap.c'
add 'src/tail_csv.c'
add 'src/tape.c'
add 'src/tcpconns.c'
add 'src/teamspeak2.c'
add 'src/turbostat.c'
add 'src/uptime.c'
add 'src/users.c'
add 'src/utils/common/common.c'
add 'src/utils/format_json/format_json.c'
add 'src/utils/format_json/format_json_test.c'
add 'src/utils/format_stackdriver/format_stackdriver_test.c'
add 'src/utils/latency/latency.c'
add 'src/utils/latency/latency_config.c'
add 'src/utils/latency/latency_test.c'
add 'src/utils/mount/mount.c'
add 'src/utils/mount/mount.h'
add 'src/utils/oauth/oauth_test.c'
add 'src/utils/proc_pids/proc_pids.c'
add 'src/utils/taskstats/taskstats.c'
add 'src/utils_tail_match.h'
add 'src/vmem.c'
add 'src/vserver.c'
add 'src/write_graphite.c'
add 'src/write_http.c'
add 'src/write_mongodb.c'`

So there is very large parts of code base that does not appear to be clang-fomatted...
Seems that likely solution is to create a new fork, apply formatting and then bring this in via a seperate pull request...

Once this is done this current branch should be to get through build process.

**Comment by mrunge** [comment]
@zebity I've had a one-liner `find -name *.[ch] -exec sh contrib/format.sh '{}' \;` to let the formatting happen. That was required to run through sources twice, before CI accepted it :-/

**Comment by rpv-tomsk** [comment]
>Run contrib/format.sh across entire *.h/*.c source tree (1st of 2)

Please move this into separate PR. 

See #3214 - this stupid clang-format makes me too angry, and I started to do tree-wide clang-format too. Ok, I found you do this too, so I will stop.


----
As you can see, "TEAM" founds new way to break Collectd development.
Not only administrative rules applied, but technical too.

I see only these, one after another changes appear which breaks development flow and destroy project.

I see, all goes to project closing. I don't understand, why @octo is unable to say these words loudly.

I think, active part of developers should go and do FORK.

**Comment by zebity** [comment]
@mrunge , good detective work 99 ;-)
The suspect file in second contrib/format pass was src/sensor.c .
This file was not even part of my original set of commits., so I don't know why my build got broken by it.

@rpv-tomsk , I suggested added seperate PR for clang-format run, but testing by @mrunge seemed to make this redundant. Apologies on second run, I only saw not on putting 2 run in separately after I had already done commit / push. Given the large number of files already hit by this PR, I think it is nice just to get the mechanical stuff out of the way so we can focus on the good stuff. Just want to thank you again for help in getting original virt bug fixed which was what got me into this project originally.

Can anyone advise on next steps to get this  and other recent updates into Debian train so I can just so a simple Ubuntu apt package install to get all this nice code off and working on production systems ;-)

**Comment by rpv-tomsk** [comment]
>Can anyone advise on next steps to get this and other recent updates into Debian train so I can just so a simple Ubuntu apt package install to get all this nice code off and working on production systems ;-)

I use my own repo for a long.

**Comment by rpv-tomsk** [comment]
> good detective work 

I think we need to do development, not detective work....
Unfortunately, most of the time we do exactly detective work.

**Comment by rpv-tomsk** [comment]
>Code owner review required
>Waiting on code owner review from anaudx, rjablonx, kwiatrox, and/or sunkuranganath. 
image

Thanks for your work, but nobody of us is able to merge this.

Propose to close this issue, ban this repo and do not spent more time on it (try another: beer, girls, etc. Life is short.).

AGAIN: "TEAM" does all to break Collectd development.

**Comment by rpv-tomsk** [comment]
>Can anyone advise on next steps to get this and other recent updates into Debian

Nobody can. Wait for @rjablonx and look for other barriers and requirements.

(I don't either try to think @octo will appear here and solves all this crap)

**Comment by rpv-tomsk** [comment]
Sorry, but "untrusted maintainers" can't do nothing with this PR.

GoodBye, team, I don't see what I can do here.

I leave project's "Trusted Contributors" team, that has no sense for me anymore.

**Comment by mrunge** [comment]
Thank you!
Unfortunately, automatism doesn't allow me to merge this.

@zebity I would like to pull this patch (and the other one I created for fixes to be merged back into 5.9 branch. Once they are merged, I'd tag 5.9.1.

Both @mfournier and @tokkee are Debian maintainers of collectd. They would be my first contact to ask for package updates. I am too far away from Debian, so I don't know if it's acceptable for other maintainers to update a package like collectd as well.

Let's do one step after another, but I clearly understand your desire to get an updated and official package.

**Comment by rpv-tomsk** [comment]
@mrunge 
Dear Matthias, 

That was good to co-work with you, but I leaved. 
After leaving (that already done), I have all the same permissions.
I still has permission to create new PR's, I can comment. 
That is enough for me now. 

As you only one active person of "Trusted Contributors" now, I wish you strong nerves and success in your work on project and others.

Maybe some days something will change, but I don't believe.

Regards,
Pavel.

**Comment by mrunge** [comment]
@rpv-tomsk I'm really, really sorry to  see you go. I understand your frustration. Is there a way back for you?

We clearly see, the current "code-owner" implementation leaves more issues than it solves. Let me try to get hold of @octo and let's see how to fix it. 

@sunkuranganath or @kwiatrox  Sunku and/or Kamil would you be able to review/approve this here?

**Comment by rpv-tomsk** [comment]
>We clearly see, the current "code-owner" implementation leaves more issues than it solves.

That is strange what "Trusted contributor"'s code (PR) requires review from "untrusted" one.
That is strange content in `CODEOWNERS`  file. This exact problem can be easily solved by appending `@collectd/trusted-contributors` into each line.

I dislike idea of "code-owner" implementation because I know (as maintainer) code quality.
Two code owners can merge PR of each other.
I also could open new Github account, create PR and merge it as Maintainer. 
But that is not acceptable way for me. 

I don't think I would make all those changes I done if I were limited by 'codeowners'.
I don't like to wait for days for minor changes to be reviewed and merged. 
That breaks my work on project.

>Is there a way back for you?

I see no reasons for now.  I don't want to be "untrusted maintainer".

However, I can put new PR, but:

I don't want to fight with clang-format.
I don't want to write code to left it unmerged.   (For now, two: #3027 - I simply use it, #3159 - also good addition left w/o review and no discussion. That is tested and ready, but I still don't use it on my prod. I don't ever count third  #3214 as I'm angry on clang-format issue).

**Comment by zebity** [comment]
@mrunge and @sunkranganath , thanks for assistance in getting this merge through. As part of cleanup we can also now close off pull request: https://github.com/collectd/collectd/pull/2895
by @vincentbernat which first attempted to resolve the GCC 8.2/3 compiler issue.

@mrunge on your Debian point, I will take advise and do this step by step... . So once you have done your 5.9.1 tagging etc I will try and case up the Debian team, I know that currrently they are compiling with warning / stop flag turned off.

@rpv-tomsk now that this has gone through, I am happy to provide any help (including running code through formatter if that is what is required) to get your backlog of updates through). I have seen all your commits and contribution here an it would be sad to loose your participation. As a programmer I have always found that you can't fight the computer. It just plows on regardless of how much you rile at it. Think of clang-format the same way, it is just a machine and it ain't going to listen to you and me, so might as well forget about it. I really hope you continue to contribute here, your ability to pin point my initial bug so quickly is exactly what is needed. Big hug to the Russian Bear, if you where in Australia I would invite you over for a beer ;-)

**Comment by rpv-tomsk** [comment]
>As a programmer I have always found that you can't fight the computer. It just plows on regardless of how much you rile at it.

But that computer is under somebody's control.  That is too stupid situation, when active part of community can't do their work after 'somebody' silently applies new and new rules which breaks that work - and absolutely no response or no any way of contact/discussion.

I think, the task of project owner is to help in project-d developing, while we see opposite: for example, 'clang-format' rules silently changed several days ago.

Again: I see no feedback/discussion on these problems from @octo or other "owner".
Hi silently sits and looks, where this situation leads. 
Or, maybe completely ignores the project state, that is no better.

**Comment by zebity** [comment]
@faxm0dem,
thanks for finding defect and fix of this large pull request to address compile issues. I am now removing fork and create new one to complete outstanding and unfixed replication of issue in src/collectdctl.c is this has not already been applied.

**Pull request merged**
