### PR TITLE
[intel_rdt] Fix build for LIBPQOS < 2

### PR DESCRIPTION
**Pull request by elfiesmelfie**
ChangeLog: intel_rdt: Update intel_rdt to build on libpqos < 2

### CODE REVIEW

**Comment by mrunge** [comment]
Thank you for working on this.
These #ifdef LIBPQOS2 are spread across the whole file, followed by an #endif and within a few lines, there is another #ifdef LIBPQOS2. It looks like there is room for improvement.

**Review by paweltox — APPROVED** [review]
Looks good to me.

**Review by kwiatrox — APPROVED** [review]
It might look clearer if whole `rdt_config_events` function is moved after the `#ifdef LIBPQOS2` block. But the fix in general works and looks good.

**Comment by mrunge** [comment]
Thanks again, let's get it merged.

**Pull request merged**
