### PR TITLE
Uuid plugin fixes / updates

### PR DESCRIPTION
**Pull request by rubenk**

### CODE REVIEW

**Comment by rubenk** [comment]
Rebased and ready.

**Comment by octo** [comment]
LGTM

I'd actually also like to remove the *dmidecode* part because it uses *popen()*.

**Comment by rubenk** [comment]
Thanks.

My plan is to remove dmidecode and support for HAL after 5.6.
Ancient kernels don't have /sys/class/dmi yet.

**Comment by octo** [comment]
@rubenk sounds like a plan

**Pull request merged**
