### PR TITLE
[collectd 6, WIP] Fix more GCC "-Wpedantic" warnings

### PR DESCRIPTION
**Pull request by eero-t**
This continues https://github.com/collectd/collectd/pull/4243:
* Change _all_ `__FUNCTION__` instances to C99 `__func__`, also in plugins
   * I decided it's safe to do after all because collectd requires C99, and all these changes are to C-files (not C++)
* Fix `-Wpedantic` array/struct initialization warnings in `mdevents.c` plugin modified by above commit
   * This commit is main one needing review
* Fix `-Wpendantic`/`-Wformat` warning in `cmds_test.c`

### CODE REVIEW

**Comment by eero-t** [comment]
After this PR, all `-Wpendantic` warnings are fixed in collected core, and the `__func__` modified plugins, except for these which I could not fix:
```
$ includes="-I. -Isrc -Isrc/daemon -Isrc/libcollectdclient -I/usr/include/dpdk"
$ corefiles=$(find src/ -mindepth 2 -name '*.c' | grep -v -e format_kairosdb.c -e _windows.c)
$ funcfiles=$(git grep -l -e __func__ -e __FUNCTION__ | grep -F -v dpdk.h)
$ for i in $(echo $corefiles $funcfiles | tr ' ' '\n' | sort -u); do \
   echo "*** $i ***"; \
   gcc $includes -DHAVE_CONFIG_H -O3 -Werror -Wall -Wpedantic -c -o /dev/null $i; \
done
...
src/daemon/plugin.c: In function ‘plugin_load_file’:
src/daemon/plugin.c:443:30: error: ISO C forbids initialization between function pointer and ‘void *’ [-Werror=pedantic]
  443 |   void (*reg_handle)(void) = dlsym(dlh, "module_register");
      |
...
src/dcpmm.c:32:10: fatal error: pmw_api.h: No such file or directory
   32 | #include "pmw_api.h"
      |          ^~~~~~~~~~~
...
src/intel_pmu.c:34:10: fatal error: jevents.h: No such file or directory
   34 | #include <jevents.h>
      |          ^~~~~~~~~~~
```
(`__func__` changes in last two plugins are done with same `sed` pattern as others, so they should be as fine as those other files.)

**Review by octo — APPROVED** [review]
LGTM

**Comment by eero-t** [comment]
Removed "WIP" from the titles as they may look a bit funny in the merged PRs list.   These compiler warning PRs are just tested to build with stricter options, and to pass CI tests.  With the increasing test / CI coverage, I hope this is enough.

PS. I'll do some real testing (with Sysman & Prometheus plugins) in next couple of days, so please no new RC releases until I've had time to do that (after which I'll be away for a week). :-)

**Comment by octo** [comment]
> please no new RC releases until I've had time to do that

My plan was to do ~weekly releases.

**Pull request merged**
