### PR TITLE
Mysql fixes

### PR DESCRIPTION
**Pull request by rubenk**
Provides a fix for #1098

### CODE REVIEW

**Comment by ChrisLundquist** [comment]
It uses `AC_SEARCH_LIBS` which looks promising, as I had just stumbled upon it. I will give this a shot Monday.

**Comment by pyr** [comment]
@ChrisLundquist any luck ?

**Comment by pyr** [comment]
@rubenk can you provide a bit more insight as to why you're doing this? i.e: is this fixing a known issue?

**Comment by rubenk** [comment]
@pyr this fixes #1098

**Comment by mfournier** [comment]
Thanks a lot @rubenk ! I merged this patchset to the collectd-5.4 branch.

**Pull request closed without merging**
