### PR TITLE
ipstats plugin: Count incoming, outgoing, forwarded packets (new plugin)

### PR DESCRIPTION
**Pull request by ometol**
ChangeLog: New ipstats plugin: Count incoming, outgoing, forwarded packets on FreeBSD

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
>ips_packets             rx:DERIVE:0:U, tx:DERIVE:0:U, fwd:DERIVE:0:U

Is that is possible to put rx/tx/fwd into type instance? 
That is preferred way, also it allows to reuse existing type `packets`.
What do you think?

**Comment by ometol** [comment]
Hi, the reusing of the packets type sounds very reasonable, I'll look into how to do that.

Also, I wrote a bit of text into collectd.conf.pod, but then noticed it was documentation on config directives, which this plugin does not have at this point.  Would you like me to just add a general purpose note to it about the plugin?

**Comment by rpv-tomsk** [comment]
> Would you like me to just add a general purpose note to it about the plugin?
Yes, take `xencpu` as example.

**Comment by rpv-tomsk** [comment]
>Hi, the reusing of the packets type sounds very reasonable, I'll look into how to do that.

```
static void ipstats_submit(const char *family, derive_t rx, derive_t tx, derive_t fwd) {
    value_list_t vl = VALUE_LIST_INIT;
    vl.values_len = 1;
    
    sstrncpy(vl.plugin, "ipstats", sizeof(vl.plugin));
    sstrncpy(vl.plugin_instance, family, sizeof(vl.plugin_instance));
    sstrncpy(vl.type, "packets", sizeof(vl.type));
    
    sstrncpy(vl.type, "rx", sizeof(vl.type));
    vl.values = &(value_t){.derive = rx};
    plugin_dispatch_values(&vl);
    
    sstrncpy(vl.type, "tx", sizeof(vl.type));
    vl.values = &(value_t){.derive = tx};
    plugin_dispatch_values(&vl);

    sstrncpy(vl.type, "fwd", sizeof(vl.type));
    vl.values = &(value_t){.derive = fwd};
    plugin_dispatch_values(&vl);
} /* void ipstats_submit */
```

**Comment by ometol** [comment]
Op 21 jun. 2019, om 10:40 heeft Pavel Rochnyak <notifications@github.com> het volgende geschreven:
> 
> Hi, the reusing of the packets type sounds very reasonable, I'll look into how to do that.
> 
> static void ipstats_submit(const char *family, derive_t rx, derive_t tx, derive_t fwd) {
>     value_list_t vl = VALUE_LIST_INIT;
>     vl.values_len = 1;
>     
>     sstrncpy(vl.plugin, "ipstats", sizeof(vl.plugin));
>     sstrncpy(vl.plugin_instance, family, sizeof(vl.plugin_instance));
>     sstrncpy(vl.type, "packets", sizeof(vl.type));
>     
>     sstrncpy(vl.type, "rx", sizeof(vl.type));
>     vl.values = &(value_t){.derive = rx};
>     plugin_dispatch_values(&vl);
>     
>     sstrncpy(vl.type, "tx", sizeof(vl.type));
>     vl.values = &(value_t){.derive = tx};
>     plugin_dispatch_values(&vl);
> 
>     sstrncpy(vl.type, "fwd", sizeof(vl.type));
>     vl.values = &(value_t){.derive = fwd};
>     plugin_dispatch_values(&vl);
> } /* void ipstats_submit */

Oh great, thanks!

I'll commit this very soon, just need to find a moment to do it.

Appreciated!

-- 
Marco van Tol

**Comment by ometol** [comment]
Hi, how is this?  I used type_instance btw, but I think that's what you meant also.

Many thanks!

**Comment by rpv-tomsk** [comment]
Can you please update README, add 'FREEBSD only' info like 

```
    - tape
      Bytes and operations read and written on tape devices. Solaris only.

    - wireless
      Link quality of wireless cards. Linux only.


    - zone
      Measures the percentage of cpu load per container (zone) under Solaris 10
      and higher
```

I will merge this PR then.
Thanks.

**Comment by ometol** [comment]
Op 22 jun. 2019, om 06:52 heeft Pavel Rochnyak <notifications@github.com> het volgende geschreven:
> 
> Can you please update README, add 'FREEBSD only' info like
> 
>     - tape
>       Bytes and operations read and written on tape devices. Solaris only.
> 
>     - wireless
>       Link quality of wireless cards. Linux only.
> 
> 
>     - zone
>       Measures the percentage of cpu load per container (zone) under Solaris 10
>       and higher
> 
> I will merge this PR then.
> Thanks.

Done, thanks!

-- 
Marco van Tol

**Comment by rpv-tomsk** [comment]
I looked into structures content
https://github.com/freebsd/freebsd/blob/master/sys/netinet/ip_var.h
https://github.com/freebsd/freebsd/blob/master/sys/netinet6/ip6_var.h

Don't you think about convert/improve this plugin to be more generic and support all fields, in configurable way? I.e. add two options to select fields to report.

**Comment by ometol** [comment]
That's a good idea actually.  I could default to how I set it up, but support everything through config.
I'm also thinking about adding arp and neighbor discovery packet statistics, which are available in other sysctl's already.

I need a bit more time to do all that, but it's definitely something that crosses my mind every now and again :)

**Comment by ometol** [comment]
I changed just ipstats.c, and apparently not fully in the desired format, but I can fix that.  I will also change the documentation once we figured out this is the right way forward.

But is how I did it now for IPv4 what you had in mind?  I can do the same for IPv6 altho that address family has a few arrays in "struct ip6stat" that I think I'll avoid for now.  But the rest could be done the same way I did IPv4.

What do you think?

**Comment by rpv-tomsk** [comment]
Hi,

Maybe we need to have one config option with many supported values?
Config example for such case:

```
<Plugin ipstats>
  Reportv4 "total badsum"
  Reportv4 "tooshort"          ## Multiple uses allowed too
  Reportv6 "xxx xxxy xxyz"
</Plugin>
```

However, this contradicts to 'defaults' when no explicit configuration. 
If any options are preselected as defaults when no explicit configuration, 
this option can't be used to switch they off.

Or, we need to do special processing and turn off defaults when plugin configured.

Such scheme used in 'virt' plugin 'ExtraStats' option,  'powerdns' plugin 'Collectd' option, possible can be found in others...

What do you think?

**Comment by rpv-tomsk** [comment]
For next step I'm thinking about many copies of similar code in 'submit' part

Maybe that can be reworked with use macroses, or even with use table of supported options and, possibly, `offsetoff`?

**Comment by rpv-tomsk** [comment]
СС @mrunge 

Mattias, can you please take  part in this discussion?

Thanks.

**Comment by mrunge** [comment]
Yes, this looks like a lot of code duplication. 

Since we have that in multiple other plugins as well, I would be fine with this for now.

**Comment by mrunge** [comment]
@ometol Marco, could you please run contrib/format.sh src/ipstats.c to fix clang-format? I'd be fine to merge this after.

**Comment by ometol** [comment]
Op 8 aug. 2019, om 12:43 heeft Matthias Runge <notifications@github.com> het volgende geschreven:
> 
> @ometol Marco, could you please run contrib/format.sh src/ipstats.c to fix clang-format? I'd be fine to merge this after.

Hi Matthias,

Thanks for your e-mail.  Sorry for the late reply, I have been on Holidays in de mean time.

I was also working on the proposed solution to use some sort of a table to avoid code duplication, but that takes a bit more time.

I will let you know when I have changed the code to use said table.

Thanks!

-- 
Marco van Tol

**Comment by ometol** [comment]
Op 18 aug. 2019, om 12:33 heeft Marco van Tol <marco@tols.org> het volgende geschreven:
> Op 8 aug. 2019, om 12:43 heeft Matthias Runge <notifications@github.com> het volgende geschreven:
>> 
>> @ometol Marco, could you please run contrib/format.sh src/ipstats.c to fix clang-format? I'd be fine to merge this after.
> 
> Hi Matthias,
> 
> Thanks for your e-mail.  Sorry for the late reply, I have been on Holidays in de mean time.
> 
> I was also working on the proposed solution to use some sort of a table to avoid code duplication, but that takes a bit more time.
> 
> I will let you know when I have changed the code to use said table.

Hi again,

So I just committed and pushed the way I thought of laying out the tables.  Let me know if it's usable like this please.

The only thing is, now I have 2 different arrays with config keys, one for IPv4 and one for IPv6.  But plugin_register_config() only supports passing one of them :-)

The way I coded it now, it does exactly what I needed it to do initially, which is counting received, transmitted, forwarded for IPv4 and IPv6.  But I don't call plugin_register_config() with the correct arguments.  I'm trying to think of a solution.

Oh, and I need to update the documentation.

-- 
Marco van Tol

**Comment by ometol** [comment]
Hi, I updated both the code and the documentation.  What else would you like to see happen before merging it?  Thank you very much in advance!

**Comment by ometol** [comment]
Op 18 sep. 2019, om 20:53 heeft Marco van Tol <marco@tols.org> het volgende geschreven:
> Op 18 aug. 2019, om 12:33 heeft Marco van Tol <marco@tols.org> het volgende geschreven:
>> Op 8 aug. 2019, om 12:43 heeft Matthias Runge <notifications@github.com> het volgende geschreven:
>>> 
>>> @ometol Marco, could you please run contrib/format.sh src/ipstats.c to fix clang-format? I'd be fine to merge this after.
>> 
>> Hi Matthias,
>> 
>> Thanks for your e-mail.  Sorry for the late reply, I have been on Holidays in de mean time.
>> 
>> I was also working on the proposed solution to use some sort of a table to avoid code duplication, but that takes a bit more time.
>> 
>> I will let you know when I have changed the code to use said table.
> 
> Hi again,
> 
> So I just committed and pushed the way I thought of laying out the tables.  Let me know if it's usable like this please.
> 
> The only thing is, now I have 2 different arrays with config keys, one for IPv4 and one for IPv6.  But plugin_register_config() only supports passing one of them :-)
> 
> The way I coded it now, it does exactly what I needed it to do initially, which is counting received, transmitted, forwarded for IPv4 and IPv6.  But I don't call plugin_register_config() with the correct arguments.  I'm trying to think of a solution.
> 
> Oh, and I need to update the documentation.

Hi, everything should be okay now.  I just pushed a little change that had a warning that was spamming the logs.

I had used it for debugging before.

It should be ready to merge.  Let me know if you want changes to it.

Thanks!

-- 
Marco van Tol

**Pull request merged**
