### PR TITLE
Disk.c now includes ZFS filesystem i/o

### PR DESCRIPTION
**Pull request by btoneill**
The closet you can get to getting good zpool stats is vopstats from the kernel kstats. Added this into collectd so each ZFS mounted filesystem you get the i/o stats for them.

### CODE REVIEW

**Comment by rubenk** [comment]
Your second commit undoes changes you did in the first one, which makes it very hard to review. Can you please squash both commits together and rebase on current master?

**Comment by btoneill** [comment]
Uggg, sorry about that. I can do that.

**Comment by btoneill** [comment]
Any better now? I'm new with git. I can try to redo it the entire thing as well....

**Comment by rubenk** [comment]
Thanks, but redoing might be better. You now have 8 commits instead of 1 ;)

**Comment by btoneill** [comment]
I actually have a bunch more changes I need to make to disk.c, so, I'll do
it as a brand new one.

All the stats for disk_time for solaris are completely wrong and useless in
the current files... I need to redo the logic...

**Comment by rubenk** [comment]
Hi @btoneill any luck? I'm going to close this PR, looking forward to your changes in a new one.

**Comment by btoneill** [comment]
I have a bunch of stuff to merge, but, haven't had time. Close this one,
and the new one will handle things...

**Pull request closed without merging**
