### PR TITLE
netapp plugin: Fix complation problems.

### PR DESCRIPTION
**Pull request by octo**
Fixes: #2120

### CODE REVIEW

**Comment by rubenk** [comment]
LGTM, apart from the commit title (s/complation/compilation) ;)

**Comment by octo** [comment]
@rubenk fixed, thanks :)

**Comment by octo** [comment]
Ping @milky-milk? Does this fix the compilation problems for you?

**Comment by milky-milk** [comment]
@octo Yes, thank you so much!

**Pull request merged**
