### PR TITLE
GenericJMX plugin: Support boolean input

### PR DESCRIPTION
**Pull request by Caden94**
ChangeLog: GenericJMX plugin: Support boolean input.

### CODE REVIEW

**Comment by rpv-tomsk** [comment]
cc @rubenk

Hi, Ruben!

What do you think, should this file being checked by `clang-format` or not?

**Comment by Caden94** [comment]
Added "ChangeLog: …" line to the pull request description

**Comment by Caden94** [comment]
How do I trigger a check rerun?

**Comment by rjablonx** [comment]
@Caden94, closing pull request and then opening same pull request again on github was re-triggering some checks but I don't know if ChangeLog check can be re-triggered that way - I think you can try it.

**Comment by octo** [comment]
Hi @Caden94,

the `ChangeLog: …` line needs to be added to the PR description, not the commit message. You can edit the PR description by going to the first entry, click on the three dots (`…`) in the upper right corner and select "Edit".

Also, #3061 aims at improving the docs around this; your input would be very helpful :)

Best regards,
—octo

**Comment by Caden94** [comment]
> @Caden94, closing pull request and then opening same pull request again on github was re-triggering some checks but I don't know if ChangeLog check can be re-triggered that way - I think you can try it.

Thanks @rjablonx reopen works for me.

**Comment by Caden94** [comment]
> Hi @Caden94,
> 
> the `ChangeLog: …` line needs to be added to the PR description, not the commit message. You can edit the PR description by going to the first entry, click on the three dots (`…`) in the upper right corner and select "Edit".
> 
> Also, #3061 aims at improving the docs around this; your input would be very helpful :)
> 
> Best regards,
> —octo

Thanks @octo for improving the documentation.

**Comment by Caden94** [comment]
Hi Team, please let me know if anything needs to be revised.

**Comment by Caden94** [comment]
Ping!

**Pull request merged**
